
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="deviation">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ADMIN - DEALER MAINTENANCE</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
&nbsp;
<div align="center">
  <table width="509" border="0">
    <tr>
      <td width="236"><div align="center"><strong>DEALER</strong></div></td>
      <td width="56">&nbsp;</td>
      <td width="78">&nbsp;</td>
    </tr>
    <tr>
      <td><strong>
        <?=$this->form->dealer?>
      </strong></td>
      <td><strong>
        <input type="submit" name="button" id="button" value="Add" />
      </strong></td>
      <td>&nbsp;</td>
    </tr>
  <?php foreach($this->details as $detail) :?>
    <tr>
      <td><strong><?=$detail->name?></strong></td>
      <td><input type="submit" name="button" id="button" value="Update" /></td>
      <td><input name="button" type="submit" onclick="javascript: if (confirm('Are you sure you want to delete this Brand List Detail?')) window.location='<?=$this->baseUrl().'/admin/dealerdelete/id/'.$detail->id?>'" value="Delete" /></td>
    </tr>
  <?php endforeach; ?>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</div>
</form>
