<style type="text/css">
table.sample {
	border-width: 2px 2px 2px 2px;
	border-spacing: 2px;
	border-style: outset outset outset outset;
	border-color: black black black black;
	border-collapse: collapse;
	background-color: white;
}
table.sample th {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
table.sample td {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
</style>
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 9pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form method="post" name="reqsubmit">
<table width="60%" border="0" align="center">
  <tr>
    <td colspan="4"><strong>WISH LIST</strong></td>
    </tr>
  <tr>
    <td width="28">&nbsp;</td>
    <td width="107" align="left">Topic:</td>
    <td width="262" align="left"><?=$this->requestDetail->request_name?></td>
    <td width="31">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="left"> By:</td>
    <td align="left"><?=$this->viewMa(strtolower($this->requestDetail->by))?></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="left">Type</td>
    <td align="left"><?=$this->requestDetail->type?></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="left" valign="top">Description</td>
    <td align="left" valign="top"><?=$this->requestDetail->remarks?></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4"><strong>REPLY</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="left">Status:</td>
    <td align="left"><?=$this->form->status?></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="left">Reply :      </td>
    <td align="left"><?=$this->form->finished_remarks?></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2" align="center"><input type="submit" name="Submit" id="button" value="Update"/></td>
    <td>&nbsp;</td>
  </tr>
</table>
<br />
</form>
<script language="JavaScript" type="text/javascript">
var frmvalidator = new Validator("reqsubmit")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("finished_remarks","req","Submit Remarks is Required!!");
frmvalidator.addValidation("status","dontselect=''","Status Required!!");
</script>