
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="add">
<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid none solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>
      <?=$this->reportTitle?>
      Report Generation</strong></td>
    <td width="13%" rowspan="2" align="center" onclick="window.location.href='<?=$this->baseUrl()?>/index/'" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'"><strong> Return </strong></td>
  </tr>
  <tr>
    <td><ul id="nav">
      <li><a href="<?=$this->baseUrl()?>/report/accountsprocess">ACCOUNTS PROCESS</a></li>
      <li><a href="<?=$this->baseUrl()?>/report/accountspending"">PENDING</a></li>
      <li><a href="#">BOOKING</a>
        <ul>
          <li><a href="<?=$this->baseUrl()?>/report/mabooktrack">MARKETING</a></li>
          <li><a href="<?=$this->baseUrl()?>/report/ldbooktrack">L&amp;D</a></li>
        </ul>
      </li>
    </ul></td>
  </tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr><td width="2%">&nbsp;</td>
  <td width="23%"><strong> Date Book</strong></td>
  <td width="8%">&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td colspan="6">From
    <?=$this->form->startdate?>
    To
  <?=$this->form->enddate?></td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td><?=$this->form->submit?></td>
  <td>&nbsp;</td>
  <td width="14%">&nbsp;</td>
  <td>&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td width="18%">&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
</table>


<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" id="hor-zebra">
   <thead> 
  <tr>
    <th width="9%" align="center"><strong>CAP NO.</strong></td>
    <th width="22%" align="center"><strong>Borrower</strong></td>
    <th width="7%" align="center"><strong>Loan Type</strong></td>
    <th width="10%" align="center"><strong>Type of Application</strong></td>
    <th width="12%" align="center"><strong>PN Number    
    </strong><th width="12%" align="center"><strong>PN Amount    
    </strong>
    <th width="12%" align="center"><strong>Amount Financed </strong></th>
    <th width="12%" align="center"><strong>Date Booked</strong></tr>
  </thead>
  <? $totalLoanAmount=0;  if ($this->rowResult){?>
  <?php foreach($this->rowResult as $row) :
  $color="black"; 
  $bookDetails = $this->getBookDetails($row->capno);
  ?>  
  
  <tr class ="odd" style="color:<?=$color?>" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='#e8edff';this.style.color='<?=$color?>'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td align="center"><?=$row->capno?></td>
    <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$this->viewTypeLoan($row->loantype)?></td>
    <td align="center"><?=$row->application_type?></td>
    <td align="center"><?=$bookDetails->pn_number?></td>
    <td align="center">P<?=number_format($bookDetails->pn_amount,2)?>
    <? $totalPnAmount = $totalPnAmount+$bookDetails->pn_amount; ?></td>
    <td align="center">P<?=number_format($bookDetails->amount_financed,2)?>
	<? $totalLoanAmount = $totalLoanAmount+$bookDetails->amount_financed; ?></td>
    <td align="center"><?=date('m-d-Y',strtotime($row->date_booked))?></td>
  </tr>
  <?php endforeach; ?>

  <? } ?>
</table>
  <? //$this->paginationControl($this->rowResult, 'Sliding', 'pagination.phtml'); ?>

<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" RULES=NONE FRAME=BOX>

    <tr>
      <td colspan="6" align="right">
      <? if($this->isSubmit) { ?>
      <input type="submit" name="submit" id="submit" value="Export as PDF" /></td>
      <? } ?>
    </tr>
    <tr><td width="8%">&nbsp;</td>
      <td width="23%"><strong>Total No. of Accounts:
          <?=$this->totalaccounts?>
      </strong></td>
      <td colspan="2"><strong>Total PN Amount: 
        P<?=number_format($totalPnAmount,2)?>
      <input type="hidden" name="totalPn" value="<?=$totalPnAmount?>"/> 
      </strong></td>
      <td width="42%" colspan="2"><strong>Total Amount of Loan: P
	  <?=number_format($totalLoanAmount,2)?>
      <input type="hidden" name="totalLoan" value="<?=$totalLoanAmount?>"/> 
      </strong></td>
    </tr>
</table>
</form>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("add")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("borrower_pres_address_no","req","Address No is Required!!");
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");



 function DoCustomValidation()
	{
	  var frm = document.forms["add"];
   	  if (frm.typeloan.value == '0'){
	    	  sfm_show_error_msg("Please Choose Loan Type");
			  return false }
	   else if (frm.source_application.value == '0')
	  {
	    	  sfm_show_error_msg("Please Choose Source Application");
			  return false
	  } 
	    else if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.promo_avail.value == '1' && frm.promo.value == '1')
	  {
	    	  sfm_show_error_msg("Please Choose a Promo");
			  return false
	  }
	  	 else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Last Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_fname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse First Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }
	  	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_mname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }

	  
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>
