<form action="" method="post" name="product">
	<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
		border-style: solid solid solid solid;border-color: black black black black;
		border-collapse: collapse;background-color: white;">
		<tr>
			<td width="77%" align="left" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick=""><strong>
		        <?=$this->title;?></strong></td>
			<td width="11%" align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick="window.location.href='<?=$this->baseUrl()?>/creditscore/uploadmemo/prod/<?=$this->prodType?>/namever/<?=$this->namever?>/func/editmodel/'"><strong>
		        eDOCS</strong></td>
			<td width="12%" align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick="window.location.href='<?=$this->baseUrl()?>/creditscore/pendingmodels/prod/<?=$this->prodType?>'"><strong>
		        RETURN</strong></td>
		</tr>
	</table>
<center>
<p>&nbsp;</p>
<table width="540" border="0">
  <tr>
    <td width="254" align='right'><b/>Model Name</td>
    <td width="17"><?=$this->form->name?></td>
    <td width="255" style="color:#F00"><b/><?=$this->errorModelName?></td>
  </tr>
  <tr colspan="2"></tr>
  <tr>
    <td align='right'><b/>Validity Period:</td>
	<td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align='right'><b/>From</td>
    <td><?=$this->form->vpfrom?></td>
    <td style="color:#F00"><b/><?=$this->errorDateName?></td>
  </tr>
  <tr>
    <td align='right'><b/>To</td>
    <td><?=$this->form->vpto?></td>
    <td>&nbsp;</td>
  </tr>
  <tr><td colspan="3">&nbsp;</td></tr>
  <tr>
    <td colspan="3" align='center'><?=$this->form->submit; ?></td>
  </tr>
</table>  
</center>	
</form>
</body>
<p>&nbsp;</p>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("product");
frmvalidator.EnableMsgsTogether();
var re = new RegExp("(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}");
frmvalidator.addValidation("dateFrom","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("dateTo","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("name","alphanumeric","Alphanumeric only");

</script>