<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  

<form action="" method="post" name="product">
	<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
		border-style: solid solid solid solid;border-color: black black black black;
		border-collapse: collapse;background-color: white;">
		<tr>
			<td width="88%" align="left" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick=""><strong>
		        <?=$this->title;?></strong></td>
			<td width="12%" align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick="window.location.href='<?=$this->baseUrl()?>/creditscore/home'"><strong>
		        RETURN</strong></td>
		</tr>
	</table>
<center>
<p></p>
<table width="336" border="0">
  <tr><td align='right'><b/>Model</td><td><?=$this->form->modelName?></td></tr>
  <tr><td align='right'><b/>Status</td><td><?=$this->form->status?></td></tr>
  <tr><td colspan="2" align='center'><?=$this->form->search; ?></td></tr>
</table>
<p></p>
<body>
	<table width="883" cellspacing="1" cellpadding="2" class="scrolltable" id="myScrollTable" >
		<thead>
			<tr align="center" >
				<th width="160" rowspan="2" class="c1">Model</th>
				<th colspan="2" class="c2">Validity Period</th>
				<th width="130" rowspan="2" class="c3">Regular/Promo</th>
				<th width="150" rowspan="2" class="c3">Business Center</th>
				<th width="130" rowspan="2" class="c3">Status</th>
				<th width="135" rowspan="2" class="c3">Action</th>
			</tr>	
			<tr align="center">
				<th width="70" class="c1">From</th>
				<th width="70" class="c2">To</th>
			</tr>
		</thead>
		<tbody>
        	<?php $count = 0;?>
       		<?php foreach($this->table as $row) : ?>  
              	<? $count++; ?>
                <tr align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'; Tip('<?=$this->getRemark($row->namever, $this->prodType)?>');"
		        onmouseout="this.style.background='white';this.style.color='black'; UnTip();">
        			<td><?=$row->namever?></td>
                    <td><?=date("m-d-Y", strtotime($row->vpfrom))?></td>
                    <td><?=date("m-d-Y", strtotime($row->vpto))?></td>
                    <td><?=$this->RegularPromo($row->namever)?></td>
                    <td><?=$this->BusinessCenter($row->namever)?></td>
                    <td><?=$row->status?></td>
                    <?php 
						$style = "";
						if($row->status == 'APPROVED') $style =  "style=\"visibility:hidden\"";
						else if($row->status == 'APPROVAL' && $this->rolePermission('creditscore_pendingCRA','') === TRUE) $style = "style=\"visibility:hidden\"";
						else if(($row->status == 'EDIT' || $row->status == 'RTS') && $this->rolePermission('creditscore_pendingCRO','') === TRUE) $style =  "style=\"visibility:hidden\"";
						$ver = $row->version;
						$ver = (int)$ver;
						$editApprove = 'Edit';
						$editUpdate = ($ver > 1)? "updatemodelspecific" : "editmodel";	
						if($row->status == 'APPROVAL' && $this->rolePermission('creditscore_pendingCRO','') === TRUE){
							$editUpdate = 'approvemodelspecific';
							$editApprove = 'Approve';
						}
					?>
                    <td><a href="<?=$this->baseUrl()?>/creditscore/<?php echo $editUpdate;?>/prod/<?=$this->prodType?>/namever/<?=$row->namever;?>/place/pendingmodels" <?php echo $style;?>><?php echo $editApprove;?> / </a>
                        <a href="<?=$this->baseUrl()?>/creditscore/viewmodelspecific/prod/<?=$this->prodType?>/namever/<?=$row->namever;?>/place/pendingmodels">View</a></td>
        		</tr> 
    		<?php endforeach; ?>
		</tbody>
	</table>
</body>
          
</center>	
</form>
<? if($count > 17){ ?>
	<script type="text/javascript">var t = new ScrollableTable(document.getElementById('myScrollTable'), 400);</script>
<? } ?>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("product");
frmvalidator.EnableMsgsTogether();
var re = new RegExp("(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}");
frmvalidator.addValidation("modelName","alphanumeric","Alphanumeric only");

</script>