<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  

<form action="" method="post" name="product">
	<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
		border-style: solid solid solid solid;border-color: black black black black;
		border-collapse: collapse;background-color: white;">
		<tr>
			<td align="left" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick=""><strong>
		        <?=$this->title;?></strong></td>            
			<td width="12%" align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
		        onmouseout="this.style.background='white';this.style.color='black'" onClick="window.location.href='<?=$this->baseUrl()?>/creditscore/home/'"><strong>
		        RETURN</strong></td>
		</tr>
	</table>
<center>
<p></p><p></p>
<body>
	<table width="336" border="0">
	  <tr><td align='right'><b/>Model</td><td><?=$this->form->modelName?></td></tr>
	  <tr><td align='right'><b/>Status</td><td><?=$this->form->status?></td></tr>
	  <tr><td colspan="2" align='center'><?=$this->form->submit; ?></td></tr>
	</table>
<p></p>
	<table width="750" cellpadding="2" cellspacing="1" class="scrolltable" id="myScrollTable" >
		<thead>
			<tr align="center">
				<th width="161" rowspan="2" class="c1">Model</th>
				<th colspan="2" class="c2">Validity Period</th>
				<th width="110" rowspan="2" class="c3">Regular/Promo</th>
				<th width="140" rowspan="2" class="c3">Business Center</th>
				<th width="106" rowspan="2" class="c3">Status</th>
			</tr>	
			<tr align="center">
				<th width="100" class="c1">From</th>
				<th width="100" class="c2">To</th>
			</tr>
		</thead>
		<tbody>
        	<?php foreach($this->table as $row) : ?>   
             <tr align="center" onMouseOver="this.style.background='red';this.style.cursor='pointer';this.style.color='white'; Tip('<?=$this->getRemark($row->namever, $this->prodType)?>');"
		        				onmouseout="this.style.background='white';this.style.color='black'; UnTip();" 
                                onClick="window.location.href='<?=$this->baseUrl()?>/creditscore/viewmodelspecific/prod/<?=$this->prodType?>/namever/<?=$row->namever;?>/place/viewmodel'">
        		<td><?=$row->namever?></td>
                <td><?=date("m-d-Y", strtotime($row->vpfrom))?></td>
                <td><?=date("m-d-Y", strtotime($row->vpto))?></td>
                <td><?=$this->RegularPromo($row->namever)?></td>
                <td><?=$this->BusinessCenter($row->namever)?></td>
                <td><?=$row->status?></td>
        	</tr>
     		<?php endforeach; ?>
		</tbody>
	</table>
</body>    	
</form>
<? if(count($this->table) > 17){ ?>
<script type="text/javascript">var t = new ScrollableTable(document.getElementById('myScrollTable'), 400);</script>
<? } ?>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("product");
frmvalidator.EnableMsgsTogether();
var re = new RegExp("(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}");
frmvalidator.addValidation("modelName","alphanumeric","Alphanumeric only");

</script>