
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="add">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>Dashboard</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td width="23%">&nbsp;</td>
  <td width="21%">&nbsp;</td>
  <td width="33%">&nbsp;</td>
  <td width="9%">&nbsp;</td>
  <td width="12%">&nbsp;</td>
</tr>
<tr><td width="2%">&nbsp;</td>
  <td colspan="4"><strong>Date Process From
    <?=$this->form->startdate?>
    To
    <?=$this->form->enddate?>
  </strong></td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2" align="center"><?=$this->form->submit?></td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  </tr>
</table>


<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
   <thead> 
  <tr>
    <th width="26%" rowspan="2" align="center">
    <th colspan="2" align="center"><strong>Recommendation
    </strong>
    <th colspan="3" align="center"><strong>Credit Decision    
    </strong>
    <th width="8%" rowspan="2" align="center">  </tr>
  <tr>
    <th width="16%" align="center"><strong>Approval        
    </strong>
    <th width="17%" align="center"><strong>Rejection    
    </strong>
    <th width="12%" align="center"><strong>Approved    
    </strong>
    <th width="11%" align="center"><strong>Reject    
    </strong>
    <th width="10%" align="center"><strong>Pass    
    </strong>    </tr>
   </thead>
  <tr>
    <td><strong>Credit Anayst</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
  <? foreach($this->getRoleUsername('CA') as $x) {?>  
  <tr>
    <td> - <?=$this->viewMa($x->username)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CA - ReAp',$this->startdate,$this->enddate)?>
    <? /*foreach($this->returnAccounts('get',$x->username,'CA - ReAp','','') as $y){
		echo $y->capno.';<br>'; } */
		?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CA - ReR',$this->startdate,$this->enddate)?></td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">&nbsp;</td>
  </tr>
  <? } ?>
    <tr>
    <td><strong>Credit Officer</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
  <? foreach($this->getRoleUsername('CO') as $x) {?>  
  <tr>
    <td> - <?=$this->viewMa($x->username)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CO - ReAp',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CA - ReR',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CO - Ap',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CO - R',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CO - RP',$this->startdate,$this->enddate)?></td>
    <td align="center">&nbsp;</td>
  </tr>
  <? } ?>    
    <tr>
    <td><strong>Credit Services Head</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
  <? foreach($this->getRoleUsername('CSH') as $x) {?>  
  <tr>
    <td> - <?=$this->viewMa($x->username)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CSH - ReAp',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CSH - ReR',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CSH - Ap',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CSH - R',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CSH - RP',$this->startdate,$this->enddate)?></td>
    <td align="center">&nbsp;</td>
  </tr>
  <? } ?>   
  <tr>
    <td><strong>Credit Management Group</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
  <? foreach($this->getRoleUsername('CMGH') as $x) {?>  
  <tr>
    <td> - <?=$this->viewMa($x->username)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CMGH - ReAp',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CMGH - ReR',$this->startdate,$this->enddate)?></td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'CMGH - P',$this->startdate,$this->enddate)?></td>
    <td align="center">&nbsp;</td>
  </tr>
  <? } ?>   
  <tr>
    <td><strong>President</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
  <? foreach($this->getRoleUsername('PRES') as $x) {?>  
  <tr>
    <td> - <?=$this->viewMa($x->username)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'PRES - ReAp',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'PRES - ReAp',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'PRES - Ap',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('normal','count',$x->username,'PRES - R',$this->startdate,$this->enddate)?></td>
    <td align="center">0</td>
    <td align="center">&nbsp;</td>
  </tr>
  <? } ?>   
  <tr>
    <td><strong>SubCrecom</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>

  <tr>
    <td> - </td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center">&nbsp;</td>
  </tr>
    <tr>
    <td><strong>Crecom</strong></td>   
    <td colspan="6" align="center" bgcolor="#CCFFFF">&nbsp;</td>
    </tr>
<? foreach($this->getMemberUsername('crecom') as $x) {?>  
  <tr>
    <td> -  
      <?=$this->viewMa($x[username])?> (<?=$x[role]?>)</td>
    <td align="center">0</td>
    <td align="center">0</td>
    <td align="center"><?=$this->returnAccounts('crecom','count',$x[username],'Approved',$this->startdate,$this->enddate)?></td>
    <td align="center"><?=$this->returnAccounts('crecom','count',$x[username],'Disapproved',$this->startdate,$this->enddate)?></td>
    <td align="center">0</td>
    <td align="center">&nbsp;</td>
  </tr>
 <? } ?>
</table>
  <? //$this->paginationControl($this->rowResult, 'Sliding', 'pagination.phtml'); ?>
</form>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("add")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("borrower_pres_address_no","req","Address No is Required!!");
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");



 function DoCustomValidation()
	{
	  var frm = document.forms["add"];
   	  if (frm.typeloan.value == '0'){
	    	  sfm_show_error_msg("Please Choose Loan Type");
			  return false }
	   else if (frm.source_application.value == '0')
	  {
	    	  sfm_show_error_msg("Please Choose Source Application");
			  return false
	  } 
	    else if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.promo_avail.value == '1' && frm.promo.value == '1')
	  {
	    	  sfm_show_error_msg("Please Choose a Promo");
			  return false
	  }
	  	 else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Last Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_fname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse First Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }
	  	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_mname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }

	  
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>
