<style type="text/css">
input {background-color:ffffff;font-family:Arial;font-size:8pt;color:000000;}
input.btn { 
color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
} 
input:focus, input.sffocus { background: #659EC7; }
</style>

  
     <script type="text/javascript">
    <!--
    $(function () {
        var cat = $('#categorySelect');
        var el = $('#elementSelect');
		var cat2 = $('#categorySelect2');
        var el2 = $('#elementSelect2');

        // note that we're assigning in reverse order
        // to allow the chaining change trigger to work
        cat.selectChain({
            target: el,
            url: '<?=$this->baseUrl();?>/inc/query.php?city=<?=$this->borrower_pres_address_city?>',
            data: { ajax: true }
        }).trigger('change');
		
		 cat2.selectChain({
            target: el2,
            url: '<?=$this->baseUrl();?>/inc/query2.php',
            data: { ajax: true }
        }).trigger('change');

    });
    //-->
 </script>
<script src="<?=$this->baseUrl();?>/js/select-chain.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>


<SCRIPT language="JavaScript">
function submitform()
{
 if(document.account.onsubmit())
 {//this check triggers the validations
    document.account.submit();
 }
}
</SCRIPT> 

<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td colspan="4">&nbsp;<strong>BORROWER PROFILE - CA PAGE</strong></td>
</tr>
<tr>
  <td width="63%"></td>
  <td width="23%" align="center" style="border-left:hidden"><a href="#" class="dropdown" onclick="window.open('<?=$this->baseURL();?>/index/deviationlist/cap/<?=$this->capno?>/page/ca','mywindow','width=800,height=300,scrollbars=yes,resizable=no, menubar =yes');"><?=$this->viewDeviation($this->capno)?></a> |
    <b><?=$this->detail->account_status2?>
     | 
     <?=$this->detail->application_type?>
    </b></td>
  <td width="14%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>'">BACK</td>
</tr>
</table>
<table width="100%" border="0">
  <tr>
    <td><?=$this->form->profile?></td>
    <td align="right"><b>
      <?=$this->viewAccountStatus($this->detail->account_status)?>
    </b></td>
  </tr>
</table>

<form action="" method="post" name="account">
  <table width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
    <tr>
      <td><?=$this->detail->dosri?></td>
      <td><?=$this->form->relation?></td>
      <td width="12%">&nbsp;</td>
      <td width="20%">&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td width="19%" colspan="2" align="right"><input type="button" name="score" value="Score" class="btn" />&nbsp;
      <?=$this->viewScore($this->detail->score,$this->highcap,'view')?>        &nbsp;</td>
    </tr>
    <tr>
      <td width="14%">Cap No.</td>
      <td width="14%"><?=$this->capno?></td>
      <td colspan="6">Borrower's Name:
        <?=$this->detail->borrower_lname?>
,
<?=$this->detail->borrower_fname?>
,
<?=$this->detail->borrower_mname?>&nbsp;&nbsp;</td>
    </tr>
    <tr>
      <td width="14%">Date Created</td>
      <td width="14%"><?=$this->application_date?></td>
      <td colspan="6">&nbsp;</td>
    </tr>
    <tr>
      <td>Type of Loan</td>
      <td><?=$this->viewTypeLoan($this->detail->loantype)?></td>
      <td colspan="2">Permanent Address</td>
      <td width="8%">Tin Id.</td>
      <td width="13%"><?=$this->detail->tin_id?></td>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td>Loan Purpose</td>
      <td><?=$this->detail->loan_purpose?></td>
      <td>Street </td>
      <td><?=$this->detail->pres_address_st?></td>
      <td>Landline</td>
      <td colspan="3"><?=$this->detail->landline?> | <?=$this->detail->phone_ver?></td>
    </tr>
    <tr>
      <td>Source of Application</td>
      <td><?=$this->detail->source_application?></td>

      <td>Barangay:      </td>
      <td><?=$this->detail->pres_address_brgy?></td>
      <td>Mobile</td>
      <td><?=$this->detail->mobile?></td>
      <td colspan="2">Total Income</td>
    </tr>
    <tr>
      <td>Marketing Assistant:</td>
      <td><?=$this->viewMa($this->detail->created_by)?></td>
      <td>City</td>
      <td><?=$this->detail->pres_address_city?></td>
      <td>Email</td>
      <td><?=$this->detail->email?></td>
      <td colspan="2"><img src="<?=$this->baseUrl();?>/images/peso_sign.png" width="12%"/><?=number_format($this->totalincome,2)?></td>
    </tr>
    <tr>
      <td>Credit Analyst:</td>
      <td><?=$this->viewCa($this->detail->submitted_ca)?></td>
      <td>Province:</td>
      <td><?=$this->detail->pres_address_province?></td>
      <td>Gender </td>
      <td><?=$this->viewGender($this->detail->gender)?></td>
      <td colspan="2">Total Combined Income</td>
    </tr>
    <tr>
      <td>Credit Officer:</td>
      <td><?=$this->viewMa($this->detail->submitted_co)?></td>
      <td>Zip Code:</td>
      <td><?=$this->detail->pres_zipcode?></td>
      <td>Civil Status</td>
      <td><?=$this->viewCivilStatus($this->detail->civilstatus)?></td>
      <td colspan="2"><img src="<?=$this->baseUrl();?>/images/peso_sign.png" width="12%"/>
      <?=number_format($this->totalcombinedincome,2)?></td>
    </tr>
    <tr>
      <td colspan="8">
      
            
  </td>
    </tr>
  </table>

	  <div class="tabber">
     
     <? if ($this->roleAccess('details','')){ ?> 
	  <div class="tabbertab">
  <h2>DETAILS</h2>
  <table width="100%">
    <tr>
      <td width="14%">&nbsp;</td>
      <td width="21%">&nbsp;</td>
      <td width="14%">&nbsp;</td>
      <td width="17%">&nbsp;</td>
      <td width="16%">&nbsp;</td>
      <td width="18%">&nbsp;</td>
    </tr>
    <tr>
      <td>Length of            Stay:</td>
      <td><?=$this->detail->residence_yrs?>
        Yr.        /
        <?=$this->detail->residence_months?>
        Mo.</td>
      <td>Date of Birth:</td>
      <td><?=date('m/d/Y',strtotime($this->detail->birthdate))?></td>
      <td>Age:</td>
      <td><?=$this->detail->age?></td>
    </tr>
    <tr>
      <td> Residence Type: </td>
      <td><?=$this->viewResidenceType($this->detail->residence_type)?></td>
      <td>Place of Birth:</td>
      <td><?=$this->detail->birthplace?></td>
      <td>No. of Dependents</td>
      <td><?=$this->detail->dependentno?></td>
      </tr>
    <tr>
      <td>Neighborhood Type:</td>
      <td><?=$this->viewNeighborhoodType($this->detail->neighborhoodtype)?></td>
      <td>Mother's Maiden:</td>
      <td><?=$this->detail->maiden_name?></td>
      <td>Citizenship:</td>
      <td><?=$this->viewCitizenship($this->detail->citizenship)?></td>
      </tr>
    </table>
  <table width="80%" id="prev_table" <? if($this->detail->residence_yrs_prev == ''){ ?>style="display:none" <? }?> >
    <tr>
      <td colspan="4"><strong>Previous Address</strong></td>
    </tr>
    <tr>
      <td width="19%">Length of            Stay:</td>
      <td width="18%"><?=$this->detail->residence_yrs_prev?>
        Yr.
        <?=$this->detail->residence_months_prev?>
        Mo.</td>
      <td width="18%">Street:</td>
      <td width="45%"><?=$this->detail->prev_address_st?></td>
    </tr>
    <tr>
      <td>Residence Type:</td>
      <td><?=$this->viewResidenceType((int)$this->detail->residence_type_prev)?></td>
      <td>City / Municipality: </td>
      <td><?=$this->detail->prev_address_city?></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>Barangay : </td>
      <td><?=$this->detail->prev_address_brgy?></td>
    </tr>
    <tr>
      <td>Zip Code: </td>
      <td><?=$this->detail->prev_zipcode?></td>
      <td>Province: </td>
      <td><?=$this->detail->prev_address_province?></td>
    </tr>
  </table>
  <!-- End of Form for Main Details -->
<iframe src ="<?=$this->baseUrl();?>/index/employment/cap/<?=$this->capno?>/page/ca/" width="100%" height="500" frameborder="0">
  <p>Your browser does not support iframes.</p>
</iframe>

	  </div>
    <? } ?>
         <? if ($this->roleAccess('obligations','')){ ?>
      <div class="tabbertab">
	  <h2>OBLIGATIONS</h2>
      <iframe src ="<?=$this->baseUrl();?>/index/obligation/cap/<?=$this->capno?>/page/ca/" width="100%" height="500" frameborder="0">
  <p>Your browser does not support iframes.</p>
</iframe>
	  </div>
      
                  <div class="tabbertab">
              <h2>ASSETS</h2>
                    <iframe src ="<?=$this->baseUrl();?>/index/otherasset/cap/<?=$this->capno?>/page/ca/" width="100%" height="500" frameborder="0">
                <p>Your browser does not support iframes.</p>
                </iframe>
        </div>
         <? } ?>
             <? if ($this->roleAccess('unit','')){ ?>
      <div class="tabbertab">
	  <h2>UNIT</h2>
	  <table width="100%" border="0">
<tr>
	      <td>Dealer&nbsp;: &nbsp; &nbsp; &nbsp;</td>
	      <td><?=$this->detail->dealer?></td>
	      <td <? if($this->detail->branch_refferror != ''){ ?>style="display:none" <? }?>>Dealer Agent:</td>
	      <td <? if($this->detail->branch_refferror != ''){ ?>style="display:none" <? }?>><?=$this->detail->dealer_agent?></td>
	      <td height="24" <? if($this->detail->branch_refferror != ''){ ?>style="display:none" <? }?>>Dealer Coordinator</td>
	      <td <? if($this->detail->branch_refferror != ''){ ?>style="display:none" <? }?>><?=$this->viewMa($this->detail->dealer_coordinator)?></td>
	      <td>&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr <? if(!$this->detail->branch_refferror){ ?>style="display:none" <? }?>>
	      <td width="14%">Branch: </td>
	      <td width="13%"><?=$this->detail->branch?></td>
	      <td width="12%">Branch Referror:</td>
	      <td width="12%"><?=$this->detail->branch_refferror?></td>
	      <td width="14%" height="24">Marketing Officer</td>
	      <td width="10%"><?=$this->viewMa($this->detail->submitted_mo)?></td>
	      <td width="12%">&nbsp;</td>
	      <td width="13%">&nbsp;</td>
        </tr>
	    <tr>
	      <td>Brand:</td>
	      <td><?=$this->detail->veh_brand?></td>
	      <td height="24">Unit:</td>
	      <td><?=$this->detail->veh_unit?></td>
	      <td>Vehicle Type:</td>
	      <td><?=$this->detail->veh_type?></td>
	      <td>Year Model:</td>
	      <td><?=$this->detail->veh_yrmodel?></td>
        </tr>
	    <tr>
	      <td>Vehicle Status:</td>
	      <td><?=$this->viewVehStatus($this->detail->veh_status)?></td>
	      <td>Vehicle Age:</td>
	      <td><?=$this->detail->veh_age?></td>
	      <td>Vehicle Use:</td>
	      <td><?=$this->viewVehUse($this->detail->veh_use)?></td>
	      <td>&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
                <? if($this->detail->veh_status == 2){ ?>
	    <tr>
	      <td>Appraisal Value</td>
	      <td>P
          <?=number_format($this->detail->appraisal_value,2)?></td>
	      <td colspan="2">Request for Waver 
          <?=$this->detail->appraisal_waver_request?></td>
	      <td>Car History</td>
	      <td><?=$this->viewCarHistory($this->detail->car_history)?></td>
	      <td colspan="2">Appraisal Report
          <?=$this->cidetail->ci_appraisal_report?></td>
        </tr>
        <tr>
	      <td>Appraisal Date</td>
	      <td><? if($this->detail->appraisal_date) {
			  echo date('m/d/Y',strtotime($this->detail->appraisal_date)); } ?></td>
	      <td>Appraised By</td>
	      <td><?=$this->detail->appraised_by?></td>
	      <td colspan="4">Remarks
	        <?=$this->cidetail->remarks_appraisal?></td>
        </tr>
        <? } ?>
	    </table>
	  <table width="100%" border="0" style="display:none">
  <tr>
    <td width="12%">Motor No.:</td>
    <td width="12%"><?=$this->vehdetail->motor_no?></td>
    <td width="11%">Color:</td>
    <td width="12%"><?=$this->vehdetail->veh_color?></td>
    <td width="13%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="11%">&nbsp;</td>
    <td width="14%">&nbsp;</td>
  </tr>
  <tr>
    <td height="24">Serial No.:</td>
    <td><?=$this->vehdetail->serial_no?></td>
    <td>Plate No:</td>
    <td><?=$this->vehdetail->plate_no?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>LTO Off:</td>
    <td colspan="3"><?=$this->vehdetail->lto_off?></td>
    <td>Ref Doc:</td>
    <td><?=$this->vehdetail->ref_doc?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>OR No.:</td>
    <td><?=$this->vehdetail->or_no?></td>
    <td>OR Date:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->or_date))?></td>
    <td>Ref No:</td>
    <td><?=$this->vehdetail->ref_no?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>CR No.:</td>
    <td><?=$this->vehdetail->cr_no?></td>
    <td>CR Date:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->cr_date))?></td>
    <td>Ref Date:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->ref_date))?></td>
    <td>UV Date:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->uv_date))?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Date Delivered:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->date_delivered))?></td>
    <td>Last Seen:</td>
    <td><?=date("m/d/Y",strtotime($this->vehdetail->last_seen))?></td>
  </tr>
 </table>
	  </div>
      <? } ?>
      <? if ($this->roleAccess('loan','')){ ?>
      <div class="tabbertab">
	  <h2>LOAN</h2>
	  <table width="100%" border="0">
	    <tr>
	      <td width="13%">Selling Price:</td>
	      <td width="38%">P
	        <?=number_format($this->detail->selling_price,2)?>
            LCP 
            <?=number_format($this->detail->lcp,2)?>
            Discount 
             <?=$this->detail->veh_discount?>
%</td>
	      <td>Term (mos.):</td>
	      <td><?=$this->detail->loanterm?>
	        months</td>
        </tr>
	    <tr>
	      <td>Downpayment:</td>
	      <td>P
	        <?=number_format($this->detail->downpayment_actual,2)?>
	        |
	        <?=number_format($this->detail->downpayment_percent,2)?>
	        %</td>
	      <td width="19%">Amount of Loan:</td>
	      <td width="30%">P
	        <?=number_format($this->detail->amountloan,2)?></td>
        </tr>
	    <tr>
	      <td>Addon Rate: </td>
	      <td><?=$this->detail->rate?>
	        %	        </td>
	      <td>Monthly Amortization:</td>
	      <td>P
	        <?=number_format($this->detail->monthly_amortization,2)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;</td>
	      <td><?=$this->detail->addon_rate?></td>
	      <td>GMI Ratio (%):</td>
	      <td><?=number_format($this->detail->gmi_ratio,2)?>
	        %</td>
        </tr>
	    <tr>
	      <td>&nbsp;</td>
	      <td>&nbsp;</td>
	      <td>&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    </table>
      </div>
      <? } ?>
     <? if ($this->roleAccess('cv','')){ ?>
      <div class="tabbertab">
	  <h2>CV</h2>
	  <table width="100%" border="0">
	    <tr>
	      <td width="18%">&nbsp;</td>
	      <td width="18%" align="center">FINDINGS</td>
	      <td width="16%" align="center">STATUS</td>
	      <td width="4%" align="center">&nbsp;</td>
	      <td width="44%">REMARKS</td>
        </tr>
	    <tr>
	      <td><strong>NFIS -
	        <?=$this->cvdetail->date_nfis?>
	        </strong></td>
	      <td align="center"><?=$this->cvdetail->nfis?></td>
	      <td align="center"><?=$this->cvdetail->nfis2?></td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_nfis)?></td>
        </tr>
	    <tr>
	      <td><strong>CMAP </strong></td>
	      <td align="center"><?=$this->cvdetail->cmap?></td>
	      <td align="center"><?=$this->cvdetail->cmap2?></td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_cmap)?></td>
        </tr>
	    <tr>
	      <td><strong>SOURCE OF INCOME VERIFICATION</strong></td>
	      <td align="center">&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;EMPLOYMENT VERIFICATION</td>
	      <td align="center"><?=$this->cvdetail->empver2?></td>
	      <td align="center"><?=$this->cvdetail->empver?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cvdetail->model_cv_empver)?></td>
	      <td><?=stripslashes($this->cvdetail->remarks_empver)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;BUSINESS VERIFICATION</td>
	      <td align="center"><?=$this->cvdetail->busver2?></td>
	      <td align="center"><?=$this->cvdetail->busver?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cvdetail->model_cv_busver)?></td>
	      <td><?=stripslashes($this->cvdetail->remarks_busver)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;TRADE CHECKING</td>
	      <td align="center"><?=$this->cvdetail->trdchk2?></td>
	      <td align="center"><?=$this->cvdetail->trdchk?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cvdetail->model_cv_trdchk)?></td>
	      <td><?=stripslashes($this->cvdetail->remarks_trdchk)?></td>
        </tr>
	    <tr>
	      <td><strong>BACKGROUND INVESTIGATION</strong></td>
	      <td align="center"><?=$this->cvdetail->backgrd?></td>
	      <td align="center">&nbsp;</td>
	      <td align="center"><?=$this->viewModelCheck($this->cvdetail->model_cv_backgrd)?></td>
	      <td><?=stripslashes($this->cvdetail->remarks_backgrd)?></td>
        </tr>
	    <tr>
	      <td><strong>BANK FI REFERENCE CHECKING</strong></td>
	      <td align="center"><?=$this->cvdetail->bankref?></td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_bankref)?></td>
        </tr>
	    <tr>
	      <td><strong>CREDIT CHECKING</strong></td>
	      <td align="center"><?=$this->cvdetail->creditchk?></td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_creditchk)?></td>
        </tr>
	    <tr>
	      <td><strong>PAST DEALINGS W/ CBC</strong></td>
	      <td align="center"><?=$this->cvdetail->pastdealings?></td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_pastdealings)?></td>
        </tr>
	    <tr>
	      <td><strong>INCOME VERIFICATION</strong></td>
	      <td align="center"><?=$this->cvdetail->income?></td>
	      <td align="center"><?=$this->cvdetail->income2?></td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cvdetail->remarks_income)?></td>
        </tr>
	    </table>
      </div>
      <? } ?>
    
      <? if ($this->roleAccess('ci','')){ ?>
      <div class="tabbertab">
	  <h2>CI</h2>
	  <table width="100%" border="0">
	    <tr>
	      <td width="18%"><strong>CI Date
	        <?=$this->cidetail->date_ci?>
	        </strong></td>
	      <td width="17%" align="center">FINDINGS</td>
	      <td width="17%" align="center">STATUS</td>
	      <td width="4%">&nbsp;</td>
	      <td width="44%">REMARKS</td>
        </tr>
	    <tr>
	      <td><strong>SOURCE OF INCOME VERIFICATION</strong></td>
	      <td align="center">&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;EMPLOYMENT VERIFICATION</td>
	      <td align="center"><?=$this->cidetail->empver_ci2?></td>
	      <td align="center"><?=$this->cidetail->empver_ci?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cidetail->model_ci_empver)?></td>
	      <td><?=stripslashes($this->cidetail->remarks_empver_ci)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;BUSINESS VERIFICATION</td>
	      <td align="center"><?=$this->cidetail->busver_ci2?></td>
	      <td align="center"><?=$this->cidetail->busver_ci?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cidetail->model_ci_busver)?></td>
	      <td><?=stripslashes($this->cidetail->remarks_busver_ci)?></td>
        </tr>
	    <tr>
	      <td>TRADE CHECKING</td>
	      <td align="center"><?=$this->cidetail->trdchk_ci2?></td>
	      <td align="center"><?=$this->cidetail->trdchk_ci?></td>
	      <td align="center"><?=$this->viewModelCheck($this->cidetail->model_ci_trdchk)?></td>
	      <td><?=stripslashes($this->cidetail->remarks_trdchk_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>BACKGROUND INVESTIGATION</strong></td>
	      <td align="center"><?=$this->cidetail->backgrd_ci2?></td>
	      <td align="center">&nbsp;</td>
	      <td align="center"><?=$this->viewModelCheck($this->cidetail->model_ci_backgrd)?></td>
	      <td><?=stripslashes($this->cidetail->remarks_backgrd_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>RESIDENCE VERIFICATION</strong></td>
	      <td align="center"><?=$this->cidetail->residence_ci2?></td>
	      <td align="center"><?=$this->cidetail->residence_ci?></td>
	      <td align="center">&nbsp;</td>
	      <td><?=stripslashes($this->cidetail->remarks_residence_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>INCOME VERIFICATION</strong></td>
	      <td align="center"><?=$this->cidetail->income_ci?></td>
	      <td align="center"><?=$this->cidetail->income_ci2?></td>
	      <td>&nbsp;</td>
	      <td><?=stripslashes($this->cidetail->remarks_income_ci)?></td>
        </tr>
	    </table>
      </div>
      
<? } ?>
           <? if ($this->roleAccess('documents','')){ ?>
      <div class="tabbertab">
	  <h2>DOCUMENTS</h2>
	  <table width="100%" border="0">
	    <!--
  <tr style="display:none">
    <td width="4%">&nbsp;</td>
    <td width="14%">CFUSCA</td>
    <td width="4%">&nbsp;</td>
    <td width="16%">SEC Registration</td>
    <td width="5%">&nbsp;</td>
    <td width="16%">PN with CHM</td>
    <td width="4%">&nbsp;</td>
    <td width="17%">Disclosure Statement on Loan/Credit Transaction</td>
    <td width="4%">&nbsp;</td>
    <td width="16%">Address Verification / Ocular Inspection Report</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Valid ID's</td>
    <td>&nbsp;</td>
    <td>DTI Registration</td>
    <td>&nbsp;</td>
    <td>Deed of Assignment</td>
    <td>&nbsp;</td>
    <td>Vehicle Insurance Policy</td>
    <td>&nbsp;</td>
    <td>Special Power of Attorney</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Latest ITR</td>
    <td>&nbsp;</td>
    <td>Board Resolution</td>
    <td>&nbsp;</td>
    <td>Duplicate Sales Invoice</td>
    <td>&nbsp;</td>
    <td>OR of Insurance Premium Payment</td>
    <td>&nbsp;</td>
    <td>Affidavid of Denial</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Statement of Assets and Liabilities</td>
    <td>&nbsp;</td>
    <td>Secretary's Certificate</td>
    <td>&nbsp;</td>
    <td>Duplicate Delivery Report</td>
    <td>&nbsp;</td>
    <td>Appraisal Report</td>
    <td>&nbsp;</td>
    <td>Affidavid of one and the same</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Tax Certificate</td>
    <td>&nbsp;</td>
    <td>Partnership Resolution</td>
    <td>&nbsp;</td>
    <td>Official Receipt of Downpayment</td>
    <td>&nbsp;</td>
    <td>Deed of Absolute Sale</td>
    <td>&nbsp;</td>
    <td>Affidavid of Non-Tax Use</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Certificate of Employment</td>
    <td>&nbsp;</td>
    <td>Audited Financial Statement</td>
    <td>&nbsp;</td>
    <td>Official Receipt of Full Payment</td>
    <td>&nbsp;</td>
    <td>Car History Report</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Authority to Credit</td>
    <td>&nbsp;</td>
    <td>Arcticles of Incorporation and Amendment</td>
    <td>&nbsp;</td>
    <td>Stencils w/ Onion Skin</td>
    <td>&nbsp;</td>
    <td>PNP Motor Vehicle Clearance </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><table cellspacing="0" cellpadding="0">
      <tr>
        <td>Post Dated Checks</td>
      </tr>
    </table></td>
    <td>&nbsp;</td>
    <td><table cellspacing="0" cellpadding="0">
      <tr>
        <td>By Laws</td>
      </tr>
    </table></td>
    <td>&nbsp;</td>
    <td>Dealer Undertaking</td>
    <td>&nbsp;</td>
    <td>PO</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Authority to Debit</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>LTO CR</td>
    <td>&nbsp;</td>
    <td>Authority to DeliverDeliver</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>L&amp;D Signature Card</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>LTO OR</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  -->
	    <tr>
	      <td colspan="10" align="center"><input type="button" name="edocs" id="edocs" value="eDOCS" style="width:120px" onclick = "window.open('<?=$this->baseURL();?>/edocs/accountview/cap/<?=$this->capno?>','mywindow','width=800,height=600,scrollbars=yes,resizable=no')"/></td>
        </tr>
	    </table>
      </div>
      <? } ?>

      </div>
      
        </form> 
   
