
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="account-history">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ACCOUNT HISTORY - 
	  <?=$this->detail->borrower_lname?>, 
	  <?=$this->detail->borrower_fname?> 
	  <?=$this->detail->borrower_mname?>
	</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white; display:none">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="3">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr><td width="2%">&nbsp;</td>
  <td width="9%">&nbsp;</td>
  <td width="21%">&nbsp;</td>
  <td colspan="3">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>Cap No.</td>
  <td><?=$this->form->capno?></td>
  <td colspan="5">&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td width="5%">&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td width="18%">&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>Borrower</td>
  <td><?=$this->form->borrower_lname?></td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
</table>
</form>

<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td width="5%" align="center"><strong>RECON</strong></td>
    <td width="11%" align="center"><strong>PROCESS CODE</strong></td>
    <td width="14%" align="center"><strong>DEPARTMENT</strong></td>
    <td width="13%" align="center"><strong>USER</strong></td>
    <td width="11%" align="center"><strong>TIME/DATE</strong></td>
    <td width="9%" align="center"><strong>OLD TAT</strong></td>
    <td width="10%" align="center"><strong>NEW TAT</strong></td>
    <td width="27%" align="center"><strong>REMARKS</strong></td>
  </tr>
  <? if ($this->rows){ $sum_of_seconds = 0;  $temp_seconds=0;$temp_total=0; $old_recon=0; $new_recon=0;?>
  <?php
  	//set array variable
  	$department_name_arr =array();
  	$department_seconds = array();
  	$department_total = array();
  	$department_overall_total = array();
	foreach($this->rows as $row){
		$name = $this->viewAccountStatusDept($row->status);
		/*
		if($name==null){
			$name = $row->status;
		}
		*/
		if(!array_key_exists($name,$department_name_arr)){
			$department_name_arr[$name] = $name;
		}
		if (!array_key_exists($department_name_arr[$name], $department_seconds)){
			$department_seconds[$department_name_arr[$name]]=0;
			$department_total[$department_name_arr[$name]]=0;
		}
		$ctr++;
	}
  ?>
  <?php $recon_count = 0;  foreach($this->rows as $row) : ?>  
	<? $recon_no = substr($row->capno,-1); if($recon_no != $recon_count) {  ?>
<?php
	if($old_recon!=$new_recon){
		$temp_total = $temp_seconds;
		$temp_seconds =0;
		
		foreach($department_name_arr as $x){
			if($department_seconds[$x]!=0){
				$department_total[$x] = $department_seconds[$x];
				$department_seconds[$x] =0;
			}
		}
		
		$old_recon = $new_recon;
?>
<?php
		$output = "";
		foreach($department_name_arr as $x){
			if($department_total[$x]!=0){
				$a = $this->getTurnAroundTime($department_total[$x],NULL,"compute");
				$output .= " {$x} took <span style='color:red;'>{$a}.</span> ";
				$department_overall_total[$x] += $department_total[$x];
				$department_total[$x] =0;
			}
		}
		if($output!=""){
?>
<tr>
  	<td colspan="8" style="padding:4px;padding-left: 10px;">
		<p style="font-weight:bold;">
			<?=$output?>
		</p>
	</td>
 </tr>
<?php } ?>
<tr>
  	<td colspan="8" style="padding:4px;padding-left: 10px;">
  		<p style="font-weight:bold;">Total application time <span style="color: red;"><?php
		  if($temp_total!=0){
			echo $this->getTurnAroundTime($temp_total,NULL,"compute");
		  }else{
			echo "0 min";
		  }
		   $temp_total = 0; ?>. </span></p>
	</td>
  </tr>
<?php
	}
?>
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'">
    <td colspan="8" align="center"><strong>
    <? if($recon_no == 0) {
    	$new_recon++;
		echo "Original Application";
	}else {
		echo $this->getReconReprocess($row->capno).' '.$recon_no;
		$new_recon++;
	} 
	
	?>
    </strong></td>
  </tr>
      <?  } $recon_count=$recon_no;?>  
  
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td align="center"><?
	echo $recon_no;
	?></td>
    <td align="center"><?=$this->viewAccountStatus($row->status)?></td>
    <td align="center"><?=$this->viewUserDept($row->by)?></td>
<?php
	//store the name of the department
	$department_name = $this->viewAccountStatusDept($row->status);
?>
    <td align="center"><?=$this->viewMa($row->by)?></td>
    <td><?=date("m/d/Y/ h:ia",strtotime($row->date))?></td>
    <td><?=$this->dateTimeDiff($row->date_last,$row->date)?></td>
    <td>
    <?php
    	//echo "End[{$row->date}]<br/>Start[{$row->date_last}]";
    	//$tat = $this->getTurnAroundTime($row->date,$row->date_last,"turn_around");
    	$tat = $this->getTat($row->date,$row->date_last);
    	
		$sum_of_seconds += $this->getTurnAroundTime($tat,NULL,"timesum");
    	echo $tat;
    	$temp_seconds += $this->getTurnAroundTime($tat,NULL,"timesum");
		$department_seconds[$department_name] += $this->getTurnAroundTime($tat,NULL,"timesum");
    ?>
	</td>
    <td><?=$row->remarks?></td>
  </tr>
  <?php $date2 = $row->date; endforeach; ?>
  <? } ?>
<?php
	if($old_recon!=$new_recon){
		$temp_total = $temp_seconds;
		$temp_seconds =0;
		$old_recon = $new_recon;
		foreach($department_name_arr as $x){
			if($department_seconds[$x]!=0){
				$department_total[$x] = $department_seconds[$x];
				$department_seconds[$x] =0;
			}
		}
?>
<?php
		$output = "";
		foreach($department_name_arr as $x){
			if($department_total[$x]!=0){
				$a = $this->getTurnAroundTime($department_total[$x],NULL,"compute");
				$output .= " {$x} took <span style='color:red;'>{$a}.</span> ";
				$department_overall_total[$x] += $department_total[$x];
				$department_total[$x] =0;
			}
		}
		if($output!=""){
?>
<tr>
  	<td colspan="8" style="padding:4px;padding-left: 10px;">
		<p style="font-weight:bold;">
			<?=$output?>
		</p>
	</td>
 </tr>
<?php } ?>
 <tr>
  	<td colspan="8" style="padding:4px;padding-left: 10px;">
  		<p style="font-weight:bold;">Total application time<span style="color: red;"><?php
		  if($temp_total!=0){
			echo $this->getTurnAroundTime($temp_total,NULL,"compute");
		  }else{
			echo "0 min";
		  }
		   $temp_total = 0; ?>. </span></p>
	</td>
  </tr>
<?php
	}
?>
</table>
<div style="padding:4px; padding-bottom: 20px;">
<?php
		$output = "";
		foreach($department_name_arr as $x){
			if($department_seconds[$x]!=0){
				$a = $this->getTurnAroundTime($department_seconds[$x],NULL,"compute");
				$output .= " Overall {$x} took <span style='color:red;'>{$a}.</span> ";
				$department_seconds[$x] =0;
			}
		}
		if($output!=""){
?>
<p style="text-align:center;font-size: 14px; font-weight: bold;">
	<?=$output?>
</p>
<?php
		}
?>
<?php
		$output = "";
		foreach($department_name_arr as $x){
			if($department_overall_total[$x]!=0){
				$a = $this->getTurnAroundTime($department_overall_total[$x],NULL,"compute");
				$output .= "Overall {$x} took <span style='color:red;'>{$a}.</span> ";
				$department_overall_total[$x] =0;
			}
		}
		if($output!=""){
?>
<p style="text-align:center;font-size: 14px; font-weight: bold;">
	<?=$output?>
</p>
<?php
		}
?>
<p style="text-align:center;font-size: 14px; font-weight: bold;">Overall application time: <span style="color: red;"><?php echo $this->getTurnAroundTime($sum_of_seconds,NULL,"compute"); ?>. </span></p></div>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("add")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("borrower_pres_address_no","req","Address No is Required!!");
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");



 function DoCustomValidation()
	{
	  var frm = document.forms["add"];
   	  if (frm.typeloan.value == '0'){
	    	  sfm_show_error_msg("Please Choose Loan Type");
			  return false }
	   else if (frm.source_application.value == '0')
	  {
	    	  sfm_show_error_msg("Please Choose Source Application");
			  return false
	  } 
	    else if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.promo_avail.value == '1' && frm.promo.value == '1')
	  {
	    	  sfm_show_error_msg("Please Choose a Promo");
			  return false
	  }
	  	 else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Last Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_fname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse First Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }
	  	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_mname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }

	  
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
  </script>