<?
$time = microtime();
$time = explode(" ", $time);
$time = $time[1] + $time[0];
$start = $time;
?>
<style type="text/css">
input {background-color:ffffff;font-family:Arial;font-size:8pt;color:000000;}
input.btn { 
color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
} 
input:focus, input.sffocus { background: #659EC7; }
</style>
<script type="text/javascript">

/* Optional: Temporarily hide the "tabber" class so it does not "flash"
   on the page as plain HTML. After tabber runs, the class is changed
   to "tabberlive" and it will appear.
*/
document.write('<style type="text/css">.tabber{display:none;}<\/style>');

var tabberOptions = {

  /* Optional: instead of letting tabber run during the onload event,
     we'll start it up manually. This can be useful because the onload
     even runs after all the images have finished loading, and we can
     run tabber at the bottom of our page to start it up faster. See the
     bottom of this page for more info. Note: this variable must be set
     BEFORE you include tabber.js.
  */
  'manualStartup':true,

  /* Optional: code to run after each tabber object has initialized */

  'onLoad': function(argsObj) {
	  
    /* Display an alert only after tab2 */
    /*
	if (argsObj.tabber.id == 'tab2') {
      alert('Finished loading tab2!');
    }
	*/
  },

  /* Optional: code to run when the user clicks a tab. If this
     function returns boolean false then the tab will not be changed
     (the click is canceled). If you do not return a value or return
     something that is not boolean false, */

  'onClick': function(argsObj) {
	
    calcGmiRatio();
	//var t = argsObj.tabber; /* Tabber object */
    //var id = t.id; /* ID of the main tabber DIV */
    //var i = argsObj.index; /* Which tab was clicked (0 is the first tab) */
    //var e = argsObj.event; /* Event object */

    //if (id == 'loan') {
      //return confirm('Swtich to '+t.tabs[i].headingText+'?\nEvent type: '+e.type);
	  //alert("hello");
    //} 
	
	//
  },

  /* Optional: set an ID for each tab navigation link */
  'addLinkId': true

};

</script>
  
      <script type="text/javascript">
    <!--
    $(function () {
		

		var province = $('#categorySelect');
        var city = $('#citySelect');
		var brgy = $('#brgySelect');
		var zip = $('#zipSelect');
		
		var province2 = $('#prevcategorySelect');
        var city2 = $('#prevcitySelect');
		var brgy2 = $('#prevbrgySelect');
		var zip2 = $('#prevzipSelect');

        // note that we're assigning in reverse order
        // to allow the chaining change trigger to work
		/*
		brgy.selectChain({
            target: zip,
            //url: '/inc/select-brgy.php?defcity='+getCity(),
            url: '<?$this->baseUrl();?>/inc/select-brgy.php',
            data: { ajax: true, anotherval: "anotherAction" }            
        });      
		*/
		city.selectChain({
            target: brgy,
            url: '<?=$this->baseUrl();?>/inc/select-city.php?brgy=<?=$this->borrower_pres_address_brgy?>',
			data: { ajax: true, anotherval: "anotherAction" }            
        });      
		
        province.selectChain({
            target: city,
            url: '<?=$this->baseUrl();?>/inc/select-province.php?city=<?=$this->borrower_pres_address_city?>',
            data: { ajax: true }
        }).trigger('change');
		
		<!---Previous Address---!>
		/*
		brgy2.selectChain({
            target: zip2,
            url: '<?//$this->baseUrl();?>/inc/select-brgy-prev.php',
            data: { ajax: true, anotherval: "anotherAction" }            
        });      
		*/
		city2.selectChain({
            target: brgy2,
            url: '<?=$this->baseUrl();?>/inc/select-city-prev.php?brgy2=<?=$this->borrower_prev_address_brgy?>',
            data: { ajax: true, anotherval: "anotherAction" }            
        });      
		
        province2.selectChain({
            target: city2,
            url: '<?=$this->baseUrl();?>/inc/select-province-prev.php?city2=<?=$this->borrower_prev_address_city?>',
            data: { ajax: true }
        }).trigger('change');
		
		
		

    });
	


    //-->
 </script>

<script type="text/javascript" src="<?=$this->baseUrl();?>/js/mybic.js"></script>
<script>
//Ajax to Call the Total income
	//var ajaxObj;
	var spochk;

	function startAjax() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");

		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=totalincome&cap=<?=$this->capno?>", respTotalIncome);
	}

	
	function respTotalIncome(resp) {
		
		//document.getElementById('content').innerHTML = resp;
		document.forms["account"].totalcombineincome.value = resp;
	}
	
	function startZip() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");

		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=zipcode&city="+getCity()+"&brgy="+getBrgy(), respZipcode);
		//alert(getCity());
	}
	
	function startZipPrev() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");

		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=zipcode&city="+getCityPrev()+"&brgy="+getBrgyPrev(), respZipcodePrev);
		//alert(getCity());
	}
	
	function totalExistLoan() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=existloan&cap=<?=$this->capno?>", respExistLoan);
		//alert(getCity());
	}
		function spouseCheck() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=spousechk&cap=<?=$this->capno?>", respSpouse);
		//alert(getCity());
	}
	
	
	function respExistLoan(resp) {
		//document.getElementById('content').innerHTML = resp;
		document.forms["account"].totalexistloan.value = resp;
	}
	
	function respSpouse(resp) {
		spochk = resp;
	}

	function respZipcode(resp) {
		//document.getElementById('content').innerHTML = resp;
		document.forms["account"].pres_zipcode.value = resp;
		
	}
	
	function respZipcodePrev(resp) {
		
		//document.getElementById('content').innerHTML = resp;
		document.forms["account"].prev_zipcode.value = resp;
		
	}
	
	function getCity(){
		var city = document.forms["account"].borrower_pres_address_city;
		//alert("hello");
		return city.options[city.selectedIndex].value;
	}
	function getBrgy(){
		var brgy = document.forms["account"].borrower_pres_address_brgy;
		//alert("hello");
		return brgy.options[brgy.selectedIndex].value;
	}
	
	function getCityPrev(){
		var city = document.forms["account"].borrower_prev_address_city;
		//alert("hello");
		return city.options[city.selectedIndex].value;
	}
	function getBrgyPrev(){
		var brgy = document.forms["account"].borrower_prev_address_brgy;
		//alert("hello");
		return brgy.options[brgy.selectedIndex].value;
	}
	
	// New Pricelist Generation using MyBic March 30 2010
	
	function getPricelistDealer(){
		return document.getElementById("dealer_pricelist").value
	}
	function getPricelistYear(){
		return document.getElementById("listyear_pricelist").value
	}
	function getPricelistMonth(){
		return document.getElementById("listmonth_pricelist").value
	}
	function getPricelistBrand(){
		return document.getElementById("veh_brand_pricelist").value
	}
	function getPricelistUnit(){
		return document.getElementById("veh_unit_pricelist").value
	}
	
	function chainselectBrand() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=pricelistchainbrand&dealer="+getPricelistDealer()+"&year="+getPricelistYear()+"&month="+getPricelistMonth(), respchainselectBrand);
	}

	function respchainselectBrand(resp) {
		var sel = document.getElementById('veh_brand_pricelist');
		sel.length = 0;
		for ( var i in resp )
		{
		if(i == 0){
		sel.options[sel.options.length] = new Option('','');				
			}
    	sel.options[sel.options.length] = new Option(resp[i],resp[i]);
		}
	}
	
	function chainselectUnit() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		//ajaxObj.debug=1;
		ajaxObj.method="GET";
		ajaxObj.call("action=pricelistchainunit&dealer="+getPricelistDealer()+"&year="+getPricelistYear()+"&month="+getPricelistMonth()+"&brand="+getPricelistBrand(), respchainselectUnit);
	}
	
	function respchainselectUnit(resp) {
		var sel = document.getElementById('veh_unit_pricelist');
		sel.length = 0;
		for ( var i in resp )
		{
			if(i == 0){
		sel.options[sel.options.length] = new Option('','');
				
			}
    	sel.options[sel.options.length] = new Option(resp[i],resp[i]);
		}
	}
	
	function chainselectType() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		ajaxObj.method="GET";
		ajaxObj.call("action=pricelistchaintype&dealer="+getPricelistDealer()+"&year="+getPricelistYear()+"&month="+		getPricelistMonth()+"&brand="+getPricelistBrand()+"&unit="+getPricelistUnit(), respchainselectType);
	}
	function respchainselectType(resp) {
		var sel = document.getElementById('veh_type_pricelist');
		sel.length = 0;
		for ( var i in resp )
		{
    	sel.options[sel.options.length] = new Option(resp[i],resp[i]);
		}
	}
	
	function chainselectPrice() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		ajaxObj.method="GET";
		ajaxObj.call("action=pricelistchainprice&dealer="+getPricelistDealer()+"&year="+getPricelistYear()+"&month="+		getPricelistMonth()+"&brand="+getPricelistBrand()+"&unit="+getPricelistUnit(), respchainselectPrice);
	}
	function respchainselectPrice(resp) {
		var sel = document.getElementById('selling_price_pricelist');
		sel.length = 0;
		for ( var i in resp )
		{
    	sel.options[sel.options.length] = new Option(resp[i],resp[i]);
		}
	}
	
	function chainselectId() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		ajaxObj.method="GET";
		ajaxObj.call("action=pricelistchainid&dealer="+getPricelistDealer()+"&year="+getPricelistYear()+"&month="+		getPricelistMonth()+"&brand="+getPricelistBrand()+"&unit="+getPricelistUnit(), respchainselectId);
	}

	function respchainselectId(resp) {
		//alert(resp);
		var sel = document.getElementById('vehunitId');
		sel.value = resp;
		//alert(sel.value);
	}
	
	


</script>
<script type="text/javascript">
/*
function getCity(){
	var frm = document.forms["account"];
	return frm.selling_price2.options[frm.selling_price2.selectedIndex].value;
	//return ;	

}*/


function calcActDownpayment()
{
startAjax();
totalExistLoan();

var frm = document.forms["account"];

var x =  unformatNumber(frm.selling_price.value) * 1;
var rate = frm.rate.value / 100;
downpayment_actual = unformatNumber(frm.selling_price.value) * (frm.downpayment_percent.value / 100);
var loanamount = unformatNumber(frm.selling_price.value) - downpayment_actual;
frm.downpayment_actual.value = downpayment_actual.toFixed(2);
frm.amountloan.value = loanamount.toFixed(2);
var monthly =  ((parseFloat(frm.amountloan.value) * rate ) + parseFloat(frm.amountloan.value)) / parseInt(frm.loanterm.value);
frm.selling_price.value = x.toFixed(2);
frm.monthly_amortization.value =monthly.toFixed(2);
//calcGmiRatio();

var monthly = parseFloat(frm.monthly_amortization.value);
var totalexistloan = parseFloat(frm.totalexistloan.value);
var totalcombine = parseFloat(frm.totalcombineincome.value);
var gmi = ((monthly + totalexistloan) / totalcombine) * 100;
frm.gmi_ratio.value = fixAtTwo(gmi);	
}

function calcGmiRatio(){
startAjax();
totalExistLoan();
var frm = document.forms["account"];


var monthly = parseFloat(frm.monthly_amortization.value);
var totalexistloan = parseFloat(frm.totalexistloan.value);
var totalcombine = parseFloat(frm.totalcombineincome.value);
var gmi = ((monthly + totalexistloan) / totalcombine) * 100;
frm.gmi_ratio.value = fixAtTwo(gmi);	
vehdiscountvalue();
//alert(frm.selling_price2.value);

}
function vehdiscountvalue(){

	var frm = document.forms["account"];
	var sellprice = unformatNumber(frm.selling_price2.value);
	var discount = 	 sellprice - frm.veh_discount.value;
	frm.selling_price.value = discount.toFixed(2);	
	calcActDownpayment();
	
}
function calcPerDownpayment()
{
startAjax();
totalExistLoan();
var frm = document.forms["account"];
var x =  frm.selling_price.value * 1;
var rate = frm.rate.value / 100;
downpayment_percent = (frm.downpayment_actual.value / unformatNumber(frm.selling_price.value)) * 100;
var loanamount = unformatNumber(frm.selling_price.value) - frm.downpayment_actual.value;
frm.downpayment_percent.value = downpayment_percent;
frm.amountloan.value = loanamount.toFixed(2);
var monthly =  ((parseFloat(frm.amountloan.value) * rate ) + parseFloat(frm.amountloan.value)) / parseInt(frm.loanterm.value);
frm.selling_price.value = x.toFixed(2);
frm.monthly_amortization.value =monthly.toFixed(2);
calcGmiRatio();

}
function calcfields()
{
//To auto calculate the fields in the loan unit
startAjax();
var frm = document.forms["account"];
downpayment_actual = unformatNumber(frm.selling_price.value) * (frm.downpayment_percent.value / 100);
var rate = frm.rate.value / 100;
var monthly =  ((parseFloat(frm.amountloan.value) * rate ) + parseFloat(frm.amountloan.value)) / parseInt(frm.loanterm.value);
var downpayment = frm.downpayment_actual.value * 1; 
var loanamount = unformatNumber(frm.selling_price.value) - frm.downpayment_actual.value;
frm.amountloan.value = loanamount.toFixed(2);
frm.monthly_amortization.value =monthly.toFixed(2);
frm.selling_price.value = fixAtTwo(unformatNumber(frm.selling_price.value));
//var dealer_incentive3 = frm.amountloan.value * (frm.dealer_incentive.value / 100);
//frm.dealer_incentive2.value = dealer_incentive3.toFixed(2);
calcGmiRatio();
}

function fixAtTwo(anynum) 
{
	var numStr=anynum.toString();
	var decPos = numStr.indexOf(".");	
	if ( decPos == -1 )
		return numStr + ".00";
	else
	{
		// add two zeros to get at least two digits at the 
		// end of the string in case it ends at the decimal
		numStr += "00";	
		return numStr.substr(0,decPos+3);
	}
	
	
	
}

function formatNumber(num, prefix){
	
	prefix = prefix || '';
	num += '';
	var splitStr = num.split('.');
	var splitLeft = splitStr[0];
	var splitRight = splitStr.length > 1 ? '.' + splitStr[1] : '';
	var regx = /(\d+)(\d{3})/;
	while (regx.test(splitLeft)) {
	splitLeft = splitLeft.replace(regx, '$1' + ',' + '$2');
	}
	return prefix + splitLeft + splitRight;
	}
	 
	function unformatNumber(num) {
	return num.replace(/([^0-9\.\-])/g,'')*1;
	}
	
	function clearr(the_sub){
		if (the_sub == 0){
		document.getElementById('prevcitySelect').options.length = 0;
		document.getElementById('prevbrgySelect').options.length = 0;
		//document.getElementById('prevzipSelect').options.length = 0;
		}
		
	}
	function copyunit(){
	var frm = document.forms["account"];
	//alert(frm.selling_price2.value);
	frm.selling_price.value = frm.selling_price2.value; 	
	//calcfields();
	}
	
	function copyunitappraisal(){
	var frm = document.forms["account"];
	//alert(frm.selling_price2.value);
	frm.selling_price.value = frm.appraisal_value.value; 	
	//calcfields();
	}
	
	function clearprev(the_sub){
		// Function for the previous Address 
		var frm = document.forms["account"];
		var years = frm.lenghtstay.value;
		var months = frm.lenght_months.options[frm.lenght_months.selectedIndex].value / 12;
		var total = (years * 1) + months;
		var residenceType = frm.residencetype.value;
		//alert(the_sub);
		if(total < 2 || residenceType == 2){
		document.getElementById('prev_table').style.display = "";
		document.getElementById('prevcitySelect').disabled = false;
		document.getElementById('prevbrgySelect').disabled = false;
		document.getElementById('prevzipSelect').disabled = false;
		document.getElementById('prevcategorySelect').disabled = false;
		document.getElementById('prevstreetSelect').disabled = false;
		frm.lenghtstay_prev.disabled = false;
		frm.lenght_months_prev.disabled = false;
		frm.residencetype_prev.disabled = false;
		

		}
		else{
		document.getElementById('prev_table').style.display = "none";
		document.getElementById('prevcitySelect').options.length = 0;
		document.getElementById('prevbrgySelect').options.length = 0;
		//document.getElementById('prevzipSelect').options.length = 0;
		document.getElementById('prevcategorySelect').value = 0;
		document.getElementById('prevstreetSelect').value = '';
		document.getElementById('prevstreetSelect').disabled = true;
		document.getElementById('prevcitySelect').disabled = true;
		document.getElementById('prevbrgySelect').disabled = true;
		document.getElementById('prevzipSelect').disabled = true;
		document.getElementById('prevcategorySelect').disabled = true;
		frm.lenghtstay_prev.disabled = true;
		frm.lenght_months_prev.disabled = true;
		frm.residencetype_prev.disabled = true;
		frm.lenghtstay_prev.value = '';
		frm.lenght_months_prev.value = 0;
		frm.residencetype_prev.value = 0;
		}
	}
	
function compage(bDay){
 now = new Date()
 bD = bDay.value.split('/');
 if(bD.length==3){
   born = new Date(bD[2], bD[0]*1-1, bD[1]);
   years = Math.floor((now.getTime() - born.getTime()) / (365.25 * 24 * 60 * 60 * 1000));
    document.forms["account"].age.value = years;
 }
}
function comvehage(bDay){
var d = new Date();
var curr_year = d.getFullYear();

frm.veh_yrmodel.value = curr_year - bDay;

}

function yrmodel(yrValue){
frm =document.forms["account"];
var d = new Date();
var curr_year = d.getFullYear();

if (yrValue == 1 || yrValue == 0 ){
	frm.veh_yrmodel.value = curr_year;
	frm.veh_age.value = 0;
	document.getElementById('rowAppraisal').style.display = "none";
	document.getElementById('rowAppraisal2').style.display = "none";

	document.getElementById('vehsellSelect').style.display = "";

	//frm.appraisal_value.value = '';
	frm.waverRequest.checked = false;
	
	

}else {
	frm.veh_yrmodel.value = '';
	frm.veh_age.value = '';
	document.getElementById('rowAppraisal').style.display = "";
	document.getElementById('rowAppraisal2').style.display = "";
	document.getElementById('vehsellSelect').style.display = "none";
	document.getElementById('ci_appraisal_report').value = "";	

	frm.waverRequest.checked = true;

}

}

function srcapp(srcValue){
	frm =document.forms["account"];
if (srcValue == 'Branch'){
	document.getElementById('rowbranch').style.display = "";
	document.getElementById('rowdealer1').style.display = "none";
	document.getElementById('rowdealer2').style.display = "none";
	document.getElementById('rowdealer3').style.display = "none";
	document.getElementById('rowdealer4').style.display = "none";
	frm.dealer.value = '';
	frm.dealer_agent.value = '';
	frm.dealercoordinator.value  = 0;	
	
}
else if(srcValue == 'Dealer'){
	document.getElementById('rowbranch').style.display = "none";
	document.getElementById('rowdealer1').style.display = "";
	document.getElementById('rowdealer2').style.display = "";
	document.getElementById('rowdealer3').style.display = "";
	document.getElementById('rowdealer4').style.display = "";

	frm.branch.value = 0;
	frm.branch_refferror.value = '';
	frm.marketingofficer.value  = 0;
}
}


function datef(formatt){
 var num = formatt.length;
 var frm = document.account;
 if(num == 2){
	 frm.birthdate.value = formatt + '/'; 	 
 }

 if(num == 5){
	 frm.birthdate.value = formatt + '/'; 	 
 }
	
}

function vehdiscount(){

	var frm = document.forms["account"];
	
	var discount = 	(frm.selling_price.value / unformatNumber(frm.selling_price2.options[frm.selling_price2.selectedIndex].value)) * 100;
	var discount2 = 100 - discount;
	frm.veh_discount.value = discount2.toFixed(2);	
}

function copyvehDetail(){
	var whichpost = document.getElementById('selVeh1');
	var whichpost2 = document.getElementById('selVeh2');
	var whichpost3= document.getElementById('selVeh3');
	//tempDealer = document.getElementById('dealer_pricelist2').value;	
	tempBrand = document.getElementById('veh_brand_pricelist').value;	
	tempUnit = document.getElementById('veh_unit_pricelist').value;	
	tempType = document.getElementById('veh_type_pricelist').value;	
	tempPrice = document.getElementById('selling_price_pricelist').value;	
	//targetDealer = document.getElementById('vehdealer');	
	targetBrand = document.getElementById('vehbrandSelect');	
	targetUnit = document.getElementById('vehunitSelect');	
	targetType = document.getElementById('vehtypeSelect');	
	targetPrice = document.getElementById('vehsellSelect');	
	//targetDealer.value = tempDealer;
	targetBrand.value = tempBrand;
	targetUnit.value = tempUnit;
	targetType.value = tempType;
	targetPrice.value = tempPrice;
	whichpost.className="commenthidden";
	whichpost2.className="commenthidden";
	whichpost3.className="commenthidden";
	
	copyunit();
	calcActDownpayment();
	alert (targetUnit.value+' Selected')
}

function togglevehSelect() {
var whichpost = document.getElementById('selVeh1');
var whichpost2 = document.getElementById('selVeh2');
var whichpost3= document.getElementById('selVeh3');

if (whichpost.className=="commentshown") { whichpost.className="commenthidden"; } else { whichpost.className="commentshown"; }

if (whichpost2.className=="commentshown") { whichpost2.className="commenthidden"; } else { whichpost2.className="commentshown"; }

if (whichpost3.className=="commentshown") { whichpost3.className="commenthidden"; } else { whichpost3.className="commentshown"; }
} 


function disableoption(id){
			var select = document.getElementById(id);
			for (var i=0, option; option = select.options[i]; i++)
			{
					option.disabled = true;
			}

		}

 </script>
<script src="<?=$this->baseUrl();?>/js/select-chain.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
.commenthidden {display:none}


</Style>


<SCRIPT language="JavaScript">
function submitform()
{
 if(document.account.onsubmit())
 {//this check triggers the validations
 <? if($this->comakerExist) { ?>
	 document.forms["account"].comaker_accnt_status.value = '<?=$this->loggedInUserType()?> - CMK'; 
<? } ?>
document.account.submit();
	 
 }
}

function saveform()
{
 document.account.submit();
 
}

</SCRIPT> 


  <table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td>&nbsp;<strong>
	  <? if($this->comakerExist) { echo "Co-Maker's"; } else { echo "Borrower's"; } ?> 
	  PROFILE 
	  <?=$this->capno?>
-
<?=$this->borrower->borrower_lname?>

<?=$this->borrower->borrower_fname?>
,
<?=$this->borrower->borrower_mname?>
    </strong>
    

    </td>
	<td align="center" style="border-left:hidden"><b>
	  <?=$this->viewPromo($this->borrower->promo_fid)?>
	</b></td>
	<td style="border-left:hidden">&nbsp;</td>
</tr>
<tr>
  <td width="67%" >
  
  <ul id="nav">
  <li><a href="javascript:submitform()" class="dropdown" onclick="" >SAVE</a>
	<ul>
	<li><a href="javascript:saveform()">Save - Partial</a></li>
    <li><a href="javascript:submitform()">Save - Complete</a></li>   
    </ul>
  </li>
  <? if($this->isComaker($this->capno)) { ?>
  <li><a href="#" class="dropdown" onclick="javascript: if (confirm('Are you sure you want to delete this Co-Maker Detail?')) window.location='<?=$this->baseUrl().'/index/delete/cap/'.$this->capno?>'">DELETE</a></li>
  <? } ?>
</ul>
	</td>
  <td width="25%" align="center" style="border-left:hidden"><a href="#" class="dropdown" onclick="window.open('<?=$this->baseURL();?>/index/deviationlist/cap/<?=$this->capno?>','windowrecon','width=800,height=300,scrollbars=yes,resizable=no, menubar =yes');">
  <?=$this->viewDeviation($this->capno)?>
  </a>
| <b>
	<? if($this->borrower->account_status2 == "RECON") {?>
    <a href="#" class="dropdown" onclick="window.open('<?=$this->baseURL();?>/index/viewrecon/cap/<?=$this->capno?>','mywindow','width=800,height=800,scrollbars=yes,resizable=no, menubar =yes');">
    <?=$this->borrower->account_status2?>
    </a>
    <? } else { echo $this->borrower->account_status2; }?>
| <b>
<?=$this->borrower->application_type?>
</b></b></td>
  <td width="8%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>'">RETURN</td>
</tr>

</table>
  <?=$this->form->profile?>
  <?=$this->multiple?>
<form action="" method="post" name="account">
<?=$this->form->comaker_accnt_status?>

  <div style="display:
  <? if($this->roleAccess('edit_profile','')) { echo " "; } 
	 else { echo "none"; } ?>
  ">
  

  <table width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
    <tr>
      <td width="14%"><?=$this->form->dosri?></td>
      <td width="14%"><?=$this->form->relation?></td>
      <td width="11%">&nbsp;</td>
      <td colspan="5" align="left">&nbsp;&nbsp;</td>
      </tr>
    <tr>
      <td>Cap No.</td>
      <td><?=$this->capno?></td>
      <td colspan="6"><? if($this->comakerExist) { echo "Co-Maker's"; } else { echo "Borrower's"; } ?> Name:
        <?=$this->form->borrower_lname?>
        <?=$this->form->borrower_fname?>
        <?=$this->form->borrower_mname?>        &nbsp;&nbsp;</td>
      </tr>
    <tr>
      <td>Date Created:</td>
      <td><?=$this->application_date?></td>
      <td><? if($this->comakerExist) { echo "Related By :"; } ?></td>
      <td><? if($this->comakerExist) { echo $this->form->comaker_relation; } ?></td>
      <td>TIN ID. </td>
      <td colspan="2"><?=$this->form->tin_id?></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Type of Loan:</td>
      <td><?=$this->viewTypeLoan($this->borrower->loantype)?></td>
      <td colspan="2">Permanent Addresss</td>
      <td width="8%">Landline</td>
      <td colspan="3"><?=$this->form->landline?>
        <?=$this->form->phone_ver?></td>
      </tr>
    <tr>
      <td>Loan Purpose</td>
      <td><?=$this->form->loan_purpose?></td>
      <td>Street :</td>
      <td width="21%"><?=$this->form->borrower_pres_address_st?></td>
      <td>Mobile</td>
      <td colspan="3"><?=$this->form->mobile?></td>
      </tr>
    <tr>
    

      <td>Source of Application</td>
      <td><?=$this->form->source_application?></td>
      <td>Barangay :     </td>
      <td colspan="3"><?=$this->form->borrower_pres_address_brgy?></td>
      <td colspan="2">Total Income</td>
    </tr>
    <tr>
      <td>Marketing Assistant:</td>
      <td><?=$this->viewMa($this->borrower->created_by)?></td>
      <td>City:</td>
      <td><?=$this->form->borrower_pres_address_city?></td>
      <td>Email</td>
      <td width="13%"><?=$this->form->email?></td>
      <td colspan="2"><img src="<?=$this->baseUrl();?>/images/peso_sign.png" width="12%"/>
      <?=$this->totalincome?></td>
    </tr>
    <tr>
      <td>Credit Analyst:</td>
      <td>
	  <? //if($this->loggedInUserType() == 'CA') { 
	   //echo $this->form->creditanalyst;  
	  echo $this->viewMa($this->borrower->submitted_ca); 
	  // } else { } ?>
       </td>
      <td>Province:</td>
      <td><?=$this->form->borrower_pres_address_province?></td>
      <td>Gender </td>
      <td><?=$this->form->gender?></td>
      <td colspan="2">Total Combined Income</td>
    </tr>
    <tr>
      <td>Credit Officer:</td>
      <td><?=$this->viewMa($this->borrower->submitted_co)?></td>
      <td>Zip Code:</td>
      <td><?=$this->form->pres_zipcode?></td>
      <td>Civil Status</td>
      <td><?=$this->form->civilstatus?></td>
      <td colspan="2"><img src="<?=$this->baseUrl();?>/images/peso_sign.png" width="12%"/>
      <?=$this->totalcombinedincome?>
      <?=$this->form->totalcombineincome?></td>
    </tr>
    <tr>
      <td colspan="8">  </td>
    </tr>

  </table>
</div>

	  <div class="tabber" >
       <? if ($this->roleAccess('edit_details','')){ ?>
	  <div class="tabbertab" <?=$this->getVisibility($this->borrower->account_status2)?>>
  <h2>DETAILS</h2>
  <table width="100%" >
    <tr>
      <td width="19%">&nbsp;</td>
      <td width="12%">&nbsp;</td>
      <td width="15%">&nbsp;</td>
      <td width="22%">&nbsp;</td>
      <td width="15%">&nbsp;</td>
      <td width="17%">&nbsp;</td>
    </tr>
    <tr>
      <td>Length of            Stay:</td>
      <td><?=$this->form->lenghtstay?>
        <?=$this->form->lenght_months?></td>
      <td>Date of Birth:</td>
      <td><?=$this->form->birthdate?></td>
      <td>Age:</td>
      <td><?=$this->form->age?></td>
    </tr>
    <tr>
      <td> Residence Type: </td>
      <td><?=$this->form->residencetype?></td>
      <td>Place of Birth:</td>
      <td><?=$this->form->birthplace?></td>
      <td>No. of Dependents:</td>
      <td><?=$this->form->dependentno?></td>
    </tr>
    <tr>
      <td>Neighborhood Type:</td>
      <td><?=$this->form->neighborhoodtype?></td>
      <td>Mother's Maiden:</td>
      <td><?=$this->form->maiden_name?></td>
      <td>Citizenship:</td>
      <td><?=$this->form->citizenship?></td>
    </tr>
    <tr>
      <td colspan="6"></td>
    </tr>
 </table>

 <table width="80%" id="prev_table" <? if($this->prevcounter == ''){ ?>style="display:none" <? }?> >
  <tr>
      <td colspan="4"><strong>Previous Address</strong></td>
    </tr>
    <tr>
      <td width="19%">Length of            Stay:</td>
      <td width="18%"><?=$this->form->lenghtstay_prev?>
        <?=$this->form->lenght_months_prev?></td>
      <td width="18%">Street:</td>
      <td width="45%"><?=$this->form->borrower_prev_address_st?></td>
    </tr>
    <tr>
      <td>Residence Type:</td>
      <td><?=$this->form->residencetype_prev?></td>
      <td>Barangay : </td>
      <td><?=$this->form->borrower_prev_address_brgy?></td>
      </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>City / Municipality: </td>
      <td><?=$this->form->borrower_prev_address_city?></td>
      </tr>
    <tr>
      <td>Zip Code: </td>
      <td><?=$this->form->prev_zipcode?></td>
      <td>Province: </td>
      <td><?=$this->form->borrower_prev_address_province?></td>
    </tr>
 </table>
<input type="button" onclick="javascript:document.getElementById('empbus').contentWindow.location.reload();" value="Reload Frame" />
  <!-- End of Form for Main Details -->
<iframe id="empbus" src ="<?=$this->baseUrl();?>/index/employmentedit/cap/<?=$this->capno?>/relation/<?=$this->borrower->relation?>" width="100%" height="500" frameborder="0">
  <p>Your browser does not support iframes.</p>
</iframe>

	  </div>   
        <? } ?>
 <? if ($this->roleAccess('edit_obligations','')){ ?>
      <div class="tabbertab"  <?=$this->getVisibility($this->borrower->account_status2)?>>
	  <h2>OBLIGATIONS</h2>
      <iframe src ="<?=$this->baseUrl();?>/index/obligationedit/cap/<?=$this->capno?>" width="100%" height="500" frameborder="0">
  <p>Your browser does not support iframes.</p>
</iframe>
	  </div>
      
            <div class="tabbertab"  <?=$this->getVisibility($this->borrower->account_status2)?>>
              <h2>ASSETS</h2>
                    <iframe src ="<?=$this->baseUrl();?>/index/otherassetedit/cap/<?=$this->capno?>" width="100%" height="500" frameborder="0">
                <p>Your browser does not support iframes.</p>
                </iframe>
        </div>
      <? } ?>
   <? if ($this->roleAccess('edit_unit','')){ ?>    
  <div class="tabbertab" <? if($this->comakerExist) { echo "style='display:none'"; }?>>
  <h2>UNIT</h2>
      
      <table width="100%" border="0">
        <tr>
          <td><a aiotitle="click to expand" href="javascript:togglevehSelect()"
 >Add / Edit  Vehicle</a></td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr id="selVeh1" class="commenthidden">
          <td>Main Dealer</td>
          <td><? //$this->form->dealer_pricelist2?>
          <?=$this->form->dealer_pricelist?></td>
          <td>Year</td>
          <td><?=$this->form->listyear_pricelist?></td>
          <td>Month</td>
          <td><?=$this->form->listmonth_pricelist?></td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr id="selVeh2" class="commenthidden">
    <td>Brand </td>
    <td><?=$this->form->veh_brand_pricelist?></td>
    <td>Unit </td>
    <td><?=$this->form->veh_unit_pricelist?></td>
    <td>Type</td>
    <td><?=$this->form->veh_type_pricelist?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
        <tr id="selVeh3" class="commenthidden">
          <td>Price </td>
          <td><?=$this->form->selling_price_pricelist?></td>
          <td><input type="button" name="button" id="button" value="Select Unit" onclick="copyvehDetail();chainselectId();" /></td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
  <tr>
    <td>Dealer 
      &nbsp; &nbsp; &nbsp; &nbsp;</td>
    <td><?=$this->form->dealer?></td>

    <td width="12%" id="rowdealer1" <? if($this->borrower->source_application == 'Branch'){ ?>style="display:none" <? }?>>Dealer Agent</td>
    <td width="11%" id="rowdealer2" <? if($this->borrower->source_application == 'Branch'){ ?>style="display:none" <? }?>><?=$this->form->dealer_agent?></td>
    <td width="12%" height="24" id="rowdealer3" <? if($this->borrower->source_application == 'Branch'){ ?>style="display:none" <? }?>>Dealer Coordinator</td>
    <td width="13%" id="rowdealer4" <? if($this->borrower->source_application == 'Branch'){ ?>style="display:none" <? }?>><?=$this->form->dealercoordinator?></td>
    <td width="11%"><?=$this->form->veh_id?></td>
    <td width="12%">&nbsp;</td>
  </tr>
  <tr id="rowbranch" <? if($this->borrower->source_application == 'Dealer'){ ?>style="display:none" <? }?>>
    <td>Branch</td>
    <td><?=$this->form->branch?></td>
    <td height="24">Branch Referror</td>
    <td><?=$this->form->branch_refferror?></td>
    <td height="24">Marketing Officer</td>
    <td><?=$this->form->marketingofficer?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="16%">Brand</td>
    <td width="13%"><?=$this->form->veh_brand?></td>
    <td height="24">Unit</td>
    <td><?=$this->form->veh_unit?></td>
    <td>Vehicle Type</td>
    <td><?=$this->form->veh_type?></td>
    <td>Year Model</td>
    <td><?=$this->form->veh_yrmodel?></td>
    </tr>
  <tr>
    <td>Vehicle Status</td>
    <td><?=$this->form->veh_status?></td>
    <td>Vehicle Age</td>
    <td><?=$this->form->veh_age?></td>
    <td>Vehicle Use</td>
    <td><?=$this->form->veh_use?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>

  <tr id="rowAppraisal" <? if(($this->borrower->veh_status == 1) || ($this->borrower->veh_status == 0)){ ?>style="display:none" <? }?> >
    <td>Appraisal Value</td>
    <td>P 
       <?=$this->form->appraisal_value?></td>
    <td colspan="2">Request for Waver 
      <?=$this->form->appraisal_waver_request?></td>
    <td colspan="2">Car History 
      <?=$this->form->car_history?></td>
    <td colspan="2">Appraisal Report
      <?=$this->form->ci_appraisal_report?></td>
    </tr>
  <tr id="rowAppraisal2" <? if($this->borrower->veh_status == 1){ ?>style="display:none" <? }?>>
    <td>Appraisal Date</td>
    <td><?=$this->form->appraisal_date?></td>
    <td>Appraise By </td>
    <td><?=$this->form->appraised_by?></td>
    <td colspan="4">Remarks 
      <?=$this->form->remarks_appraisal?></td>
    </tr>

      </table>
 <table width="100%" border="0" style="display:none">
  <tr>
    <td colspan="8">------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</td>
    </tr>
  <tr>
    <td width="12%">Motor No.</td>
    <td width="12%"><?=$this->form->motor_no?></td>
    <td width="11%">Color</td>
    <td width="12%"><?=$this->form->veh_color?></td>
    <td width="13%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="11%">&nbsp;</td>
    <td width="14%">&nbsp;</td>
  </tr>
  <tr>
    <td height="24">Serial No.</td>
    <td><?=$this->form->serial_no?></td>
    <td>Plate No</td>
    <td><?=$this->form->plate_no?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>LTO Off</td>
    <td colspan="3"><?=$this->form->lto_off?></td>
    <td>Ref Doc</td>
    <td><?=$this->form->ref_doc?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>OR No.</td>
    <td><?=$this->form->or_no?></td>
    <td>OR Date</td>
    <td><?=$this->form->or_date?></td>
    <td>Ref No</td>
    <td><?=$this->form->ref_no?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>CR No.</td>
    <td><?=$this->form->cr_no?></td>
    <td>CR Date</td>
    <td><?=$this->form->cr_date?></td>
    <td>Ref Date</td>
    <td><?=$this->form->ref_date?></td>
    <td>UV Date</td>
    <td><?=$this->form->uv_date?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Date Delivered</td>
    <td><?=$this->form->date_delivered?></td>
    <td>Last Seen</td>
    <td><?=$this->form->last_seen?></td>
  </tr>
 </table>

	  </div>
      <? } ?>
      <? if ($this->roleAccess('edit_loan','')){ ?>
      <div class="tabbertab" id="loan" >
	  <h2>LOAN</h2>
      
      <table width="100%" border="0">
  <tr>
    <td colspan="3">LCP
      
      P<?=$this->form->selling_price2?> Discount 
      P<?=$this->form->veh_discount?>
      Selling Price 
      P<?=$this->form->selling_price?></td>
    <td width="26%">Term (mos.)</td>
    <td width="22%">&nbsp;&nbsp;
      <?=$this->form->loanterm?></td>
    </tr>
  <tr>
    <td width="14%">Downpayment</td>
    <td colspan="2">P<?=$this->form->downpayment_actual?> <?=$this->form->downpayment_percent?>%</td>
    <td>Amount of Loan</td>
    <td>P
      <?=$this->form->amountloan?></td>
    </tr>
  <tr>
    <td>Addon Rate</td>
    <td colspan="2"><?=$this->form->rate?>
      %      </td>
    <td>Monthly Amortization</td>
    <td>P
      <?=$this->form->monthly_amortization?></td>
    </tr>
  <tr>
    <td><?=$this->form->addon_rate1?></td>
    <td colspan="2">&nbsp;</td>
    <td>GMI Ratio (<a href="#" onclick="calcGmiRatio();">%</a>)</td>
    <td>&nbsp;&nbsp;
      <?=$this->form->gmi_ratio?> <input name="totalexistloan" type="hidden" id="totalexistloan" /></td>
    </tr>
   <!--
  <tr  <? /*if($this->loggedInUserType() == "MAA") { ?> style="display:none" <? } */?>>
    <td><p>Dealer Incentive Rate</p></td>
    <td colspan="2"><? //$this->form->dealer_incentive?>
      % P
      <? //$this->form->dealer_incentive2?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr <? /*if($this->loggedInUserType() == "MAA") { ?> style="display:none" <? *}*/ ?>>
    <td>Effective Yield</td>
    <td colspan="2"><? //$this->form->effective_yield?>
      %</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
-->
  <script type="text/javascript">
  //calcfields();
 </script>
</table>


	  </div>
  <? }?>
     <? if ($this->roleAccess('edit_cv','')){ ?>
<div class="tabbertab" >
  <h2>CV</h2>
      
      <table width="100%" border="0">
  <tr>
    <td width="23%">&nbsp;</td>
    <td width="15%" align="center">FINDINGS</td>
    <td width="14%" align="center">STATUS</td>
    <td width="10%">&nbsp;</td>
    <td width="10%" align="center">&nbsp;</td>
    <td width="28%">REMARKS</td>
  </tr>
  <tr>
    <td><strong>NFIS / BAP 
      <?=$this->form->date_nfis?>
    </strong></td>
    <td align="center"><?=$this->form->cv_nfis?></td>
    <td align="center"><?=$this->form->cv_nfis2?></td>
    <td><a href="#">NFIS</a></td>
    <td colspan="2"><?=stripslashes($this->form->remarks_nfis)?></td>
    </tr>
  <tr>
    <td height="25"><strong>CMAP 
      
    </strong></td>
    <td align="center"><?=$this->form->cv_cmap?></td>
    <td align="center"><?=$this->form->cv_cmap2?></td>
    <td><a href="#">CMAP</a></td>
    <td colspan="2"><?=stripslashes($this->form->remarks_cmap)?></td>
    </tr>
  <tr>
    <td><strong>SOURCE OF INCOME VERIFICATION</strong></td>
    <td align="center">&nbsp;</td>
    <td align="center">&nbsp;</td>
    <td rowspan="4"><a href="#">CV REPORT</a></td>
    <td align="center">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;&nbsp;EMPLOYMENT VERIFICATION</td>
    <td align="center"><?=$this->form->cv_empver2?></td>
    <td align="center"><?=$this->form->cv_empver?></td>
    <td colspan="2"><? //$this->form->model_cv_empver?>      <?=stripslashes($this->form->remarks_empver)?></td>
    </tr>
  <tr>
    <td>&nbsp;&nbsp;BUSINESS VERIFICATION</td>
    <td align="center"><?=$this->form->cv_busver2?></td>
    <td align="center"><?=$this->form->cv_busver?></td>
    <td colspan="2" align="left"><? //$this->form->model_cv_busver?>      <?=stripslashes($this->form->remarks_busver)?></td>
    </tr>
  <tr>
    <td>&nbsp;&nbsp;TRADE CHECKING</td>
    <td align="center"><?=$this->form->cv_trdchk2?></td>
    <td align="center"><?=$this->form->cv_trdchk?></td>
    <td colspan="2" align="left"><? //$this->form->model_cv_trdchk?>      <?=stripslashes($this->form->remarks_trdchk)?></td>
    </tr>
  <tr>
    <td><strong>BACKGROUND INVESTIGATION</strong></td>
    <td align="center"><?=$this->form->cv_backgrd?></td>
    <td align="center">&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="2"><?=$this->form->model_cv_backgrd?>      <?=stripslashes($this->form->remarks_backgrd)?></td>
    </tr>
  <tr>
    <td><strong>BANK FI REFERENCE CHECKING</strong></td>
    <td align="center"><?=$this->form->cv_bankref?></td>
    <td align="center">&nbsp;</td>
    <td rowspan="2"><a href="#">CV REPORT</a></td>
    <td colspan="2"><?=$this->form->remarks_bankref
?></td>
    </tr>
  <tr>
    <td><strong>CREDIT CHECKING</strong></td>
    <td align="center"><?=$this->form->cv_creditchk?></td>
    <td align="center">&nbsp;</td>
    <td colspan="2"><?=stripslashes($this->form->remarks_creditchk)?></td>
    </tr>
  <tr>
    <td><strong>PAST DEALINGS W/ CBC</strong></td>
    <td align="center"><?=$this->form->cv_pastdealings?></td>
    <td align="center">&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="2"><?=stripslashes($this->form->remarks_pastdealings)?></td>
    </tr>
  <tr>
    <td><strong>INCOME VERIFICATION</strong></td>
    <td align="center"><?=$this->form->cv_income?></td>
    <td align="center"><?=$this->form->cv_income2?></td>
    <td>&nbsp;</td>
    <td colspan="2"><?=stripslashes($this->form->remarks_income)?></td>
    </tr>
      </table>

  </div>
      <? } ?>
           <? if ($this->roleAccess('edit_ci','')){ ?>
      <div class="tabbertab" <?=$this->getVisibility($this->borrower->account_status2)?>>
	  <h2>CI</h2>
	  <table width="100%" border="0">
	    <tr>
	      <td width="23%"><strong>
	        CI Date<?=$this->form->date_ci?>
	      </strong></td>
	      <td width="15%" align="center">FINDINGS</td>
	      <td width="14%" align="center">STATUS</td>
	      <td width="10%">&nbsp;</td>
	      <td width="10%" align="center">&nbsp;</td>
	      <td width="28%">REMARKS</td>
        </tr>
	    <tr>
	      <td><strong>SOURCE OF INCOME VERIFICATION</strong></td>
	      <td align="center">&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td rowspan="4"><a href="#">CV REPORT</a></td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;EMPLOYMENT VERIFICATION</td>
	      <td align="center"><?=$this->form->ci_empver2?></td>
	      <td align="center"><?=$this->form->ci_empver?></td>
	      <td colspan="2"><? //$this->form->model_ci_empver?>	        <?=stripslashes($this->form->remarks_empver_ci)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;BUSINESS VERIFICATION</td>
	      <td align="center"><?=$this->form->ci_busver2?></td>
	      <td align="center"><?=$this->form->ci_busver?></td>
	      <td colspan="2"><? //$this->form->model_ci_busver?>	        <?=stripslashes($this->form->remarks_busver_ci)?></td>
        </tr>
	    <tr>
	      <td>&nbsp;&nbsp;TRADE CHECKING</td>
	      <td align="center"><?=$this->form->ci_trdchk2?></td>
	      <td align="center"><?=$this->form->ci_trdchk?></td>
	      <td colspan="2"><? //$this->form->model_ci_trdchk?>	        <?=stripslashes($this->form->remarks_trdchk_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>BACKGROUND INVESTIGATION</strong></td>
	      <td align="center"><?=$this->form->ci_backgrd2?></td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td colspan="2"><?=$this->form->model_ci_backgrd?>	        <?=stripslashes($this->form->remarks_backgrd_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>RESIDENCE VERIFICATION</strong></td>
	      <td align="center"><?=$this->form->ci_residence2?></td>
	      <td align="center"><?=$this->form->ci_residence?></td>
	      <td>&nbsp;</td>
	      <td colspan="2"><?=stripslashes($this->form->remarks_residence_ci)?></td>
        </tr>
	    <tr>
	      <td><strong>INCOME VERIFICATION</strong></td>
	      <td align="center"><?=$this->form->ci_income?></td>
	      <td align="center"><?=$this->form->ci_income2?></td>
	      <td>&nbsp;</td>
	      <td colspan="2"><?=stripslashes($this->form->remarks_income_ci)?></td>
        </tr>
	    </table>
      </div>
      <? } ?>

           <? if ($this->roleAccess('edit_documents','')){ ?>
      <div class="tabbertab">
  <h2>DOCUMENTS</h2>
	  <table width="100%" border="0">
      <!---
	    <tr style="display:none">
	      <td width="4%" align="center"><?=$this->form->app_form?></td>
	      <td width="14%">CFUSCA</td>
	      <td width="4%" align="center"><?=$this->form->sec_registration?></td>
	      <td width="16%">SEC Registration</td>
	      <td width="5%" align="center"><?=$this->form->pn_chm?></td>
	      <td width="16%">PN with CHM</td>
	      <td width="4%" align="center"><?=$this->form->disclosure_statement?></td>
	      <td width="17%">Disclosure Statement on Loan/Credit Transaction</td>
	      <td width="4%" align="center"><?=$this->form->inspection_report?></td>
	      <td width="16%">Address Verification / Ocular Inspection Report</td>
        </tr>
	    <tr >
	      <td align="center"><?=$this->form->valid_id?></td>
	      <td>Valid ID's</td>
	      <td align="center"><?=$this->form->dti_registration?></td>
	      <td>DTI Registration</td>
	      <td align="center"><?=$this->form->deed_assignment?></td>
	      <td>Deed of Assignment</td>
	      <td align="center"><?=$this->form->insurance_policy?></td>
	      <td>Vehicle Insurance Policy</td>
	      <td align="center"><?=$this->form->power_attorney?></td>
	      <td>Special Power of Attorney</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->latest_itr?></td>
	      <td>Latest ITR</td>
	      <td align="center"><?=$this->form->board_resolution?></td>
	      <td>Board Resolution</td>
	      <td align="center"><?=$this->form->sales_incvoice?></td>
	      <td>Duplicate Sales Invoice</td>
	      <td align="center"><?=$this->form->or_insurance?></td>
	      <td>OR of Insurance Premium Payment</td>
	      <td align="center"><?=$this->form->affidavit_denial?></td>
	      <td>Affidavid of Denial</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->assets_liabilities?></td>
	      <td>Statement of Assets and Liabilities</td>
	      <td align="center"><?=$this->form->secretary_cert?></td>
	      <td>Secretary's Certificate</td>
	      <td align="center"><?=$this->form->delivery_receipt?></td>
	      <td>Duplicate Delivery Report</td>
	      <td align="center"><?=$this->form->appraisal_report?></td>
	      <td>Appraisal Report</td>
	      <td align="center"><?=$this->form->affidavit_same?></td>
	      <td>Affidavid of one and the same</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->tax_cert?></td>
	      <td>Tax Certificate</td>
	      <td align="center"><?=$this->form->partnership_resolution?></td>
	      <td>Partnership Resolution</td>
	      <td align="center"><?=$this->form->receipt_downpayment?></td>
	      <td>Official Receipt of Downpayment</td>
	      <td align="center"><?=$this->form->deed_absolutesale?></td>
	      <td>Deed of Absolute Sale</td>
	      <td align="center"><?=$this->form->affidavit_nontax?></td>
	      <td>Affidavid of Non-Tax Use</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->cert_employment?></td>
	      <td>Certificate of Employment</td>
	      <td align="center"><?=$this->form->financial_statement?></td>
	      <td>Audited Financial Statement</td>
	      <td align="center"><?=$this->form->receipt_fullpayment?></td>
	      <td>Official Receipt of Full Payment</td>
	      <td align="center"><?=$this->form->car_historyreport?></td>
	      <td>Car History Report</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->authority_credit?></td>
	      <td>Authority to Credit</td>
	      <td align="center"><?=$this->form->incorporation_amend?></td>
	      <td>Arcticles of Incorporation and Amendment</td>
	      <td align="center"><?=$this->form->stencils_onionskin?></td>
	      <td>Stencils w/ Onion Skin</td>
	      <td align="center"><?=$this->form->vehicle_clearance?></td>
	      <td>PNP Motor Vehicle Clearance </td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->postdate_check?></td>
	      <td><table cellspacing="0" cellpadding="0">
	        <tr>
	          <td>Post Dated Checks</td>
            </tr>
          </table></td>
	      <td align="center"><?=$this->form->by_laws?></td>
	      <td><table cellspacing="0" cellpadding="0">
	        <tr>
	          <td>By Laws</td>
            </tr>
	        </table></td>
	      <td align="center"><?=$this->form->dealer_undertaking?></td>
	      <td>Dealer Undertaking</td>
	      <td align="center"><?=$this->form->po?></td>
	      <td>PO</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->authority_debt?></td>
	      <td>Authority to Debit</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td align="center"><?=$this->form->lto_cr?></td>
	      <td>LTO CR</td>
	      <td align="center"><?=$this->form->authority_deliver?></td>
	      <td>Authority to DeliverDeliver</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
	    <tr>
	      <td align="center"><?=$this->form->signature_card?></td>
	      <td>L&amp;D Signature Card</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td align="center"><?=$this->form->lto_or?></td>
	      <td>LTO OR</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
	      <td align="center">&nbsp;</td>
	      <td>&nbsp;</td>
        </tr>
        -->
	    <tr>
	      <td align="center">
          <input type="button" name="edocs" id="edocs" value="eDOCS" style="width:120px" onclick = "window.open('<?=$this->baseURL();?>/edocs/account/cap/<?=$this->capno?>','mywindow','width=800,height=600,scrollbars=yes,resizable=no')"/></td>
        </tr>
  </table>

</div>
	<? } ?>
           <? if ($this->roleAccess('edit_appraisal','')){ ?>
      <div class="tabbertab">
	  <h2>APPRAISAL</h2>
	  <table width="100%" border="0">
	    <tr>
	      <td width="2%">&nbsp;</td>
	      <td width="17%">FMV </td>
	      <td width="81%">P<?=$this->form->fmv?> <a href="Z#">FMV Table</a></td>
        </tr>
	    <tr>
	      <td>&nbsp;</td>
	      <td>Appraisal Value</td>
	      <td>P</td>
        </tr>
	    <tr>
	      <td>&nbsp;</td>
	      <td>Car History</td>
	      <td><?=$this->form->car_history?> <a href="#">Appraisal Report</a></td>
        </tr>
	    </table>
</div>
      <? } ?>
           <? if ($this->roleAccess('edit_insurance','')){ ?>
      <div class="tabbertab">
	  <h2>INSURANCE</h2>
      	    <iframe src ="<?=$this->baseUrl();?>/index/insuranceedit/cap/<?=$this->capno?>" width="100%" height="500" frameborder="0">
        <p>Your browser does not support iframes.</p>
        </iframe>
</div>
	<? } ?>
     <? if ($this->roleAccess('edit_craw','')){ ?>
      <div class="tabbertab">
	  <h2>CRAW</h2>
	  <iframe src ="<?=$this->baseUrl();?>/index/crawedit/cap/<?=$this->capno?>" width="100%" height="500" frameborder="0">
      <p>Your browser does not support iframes.</p>
      </iframe>
      </div>
      <? } ?>
      
      
      </div>
<input name="save_profile" type="hidden" value="<?=$this->roleAccess('edit_profile','')?>" />
<input name="save_details" type="hidden" value="<?=$this->roleAccess('edit_details','')?>" />
<input name="save_obligations" type="hidden" value="<?=$this->roleAccess('edit_obligations','')?>"/><input name="save_unit" type="hidden" value="<?=$this->roleAccess('edit_unit','')?>" />
<input name="save_loan" type="hidden" value="<?=$this->roleAccess('edit_loan','')?>" />
<input name="save_cv" type="hidden" value="<?=$this->roleAccess('edit_cv','')?>" />
<input name="save_ci" type="hidden" value="<?=$this->roleAccess('edit_ci','')?>" />
   <input name="save_documents" type="hidden" value="<?=$this->roleAccess('edit_documents','')?>" />   <input name="save_appraisal" type="hidden" value="<?=$this->roleAccess('edit_appraisal','')?>" />   <input name="save_insurance" type="hidden" value="<?=$this->roleAccess('edit_insurance','')?>" />   <input name="save_craw" type="hidden" value="<?=$this->roleAccess('edit_craw','')?>" />
  
  
</form> 
<script language="JavaScript" type="text/javascript">
// Call other js functions here including AJAX
spouseCheck();
</script>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("account")
frmvalidator.EnableMsgsTogether();
<? if($this->comakerExist) { ?>
frmvalidator.addValidation("comaker_relation","req","Co-Maker Relation!!");
<? } ?>
frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
//frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
//frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
//Add to loans and discount
//frmvalidator.addValidation("tin_id","req","Tax Identification No. !!");

//Address Fields
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
//frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");

frmvalidator.addValidation("lenghtstay","req","Years of Residency is Required!!");

frmvalidator.addValidation("dependentno","req","Dependent No. is Required!!");
frmvalidator.addValidation("appraisal_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
<? if($this->loggedInUserType() == 'CA' || $this->loggedInUserType() == 'CO') { ?>
frmvalidator.addValidation("date_nfis","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY NFIS");
frmvalidator.addValidation("date_ci","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY CI Date");
<? } ?>
//Loan Term Tabs 

 function DoCustomValidation()
	{
	  var frm = document.forms["account"];
	    //if (frm.dealercoordinator.value == '0'){
	    	//  sfm_show_error_msg("Please Choose Dealer Coordinator");
			 // return false }
		<? if($this->loggedInUserType() == 'CA' || $this->loggedInUserType() == 'CO') { ?>
		var dateString = frm.date_ci.value;
		var ciDate = new Date(dateString);
		var dateString2 = frm.date_nfis.value;
		var nfisDate = new Date(dateString2);
		<? } ?>			    
		var myDate = new Date();
		var dateString3 = frm.appraisal_date.value;
		var appraisalDate = new Date(dateString3);
	  if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.residencetype.value == '0')
		{
			  sfm_show_error_msg("Please Enter Residence Type");
   			  return false
			
		}
		
		else if (frm.neighborhoodtype.value == '0')
		{
			  sfm_show_error_msg("Please Enter Neighborhood Type");
   			  return false
			
		}
		
		else if (frm.citizenship.value == '0')
		{
			  sfm_show_error_msg("Please Enter Citizenship");
   			  return false
			
		}
	  	  	  else if (frm.age.value <= 15)
	 	 {
	    	  sfm_show_error_msg("Invalid Age");
   			  return false
		  }
		else if (frm.source_application.value == 'Dealer' && frm.dealer.value == '')
		{
			  sfm_show_error_msg("Please Enter Unit : Dealer");
   			  return false
			
		}
			else if (frm.source_application.value == 'Dealer' && frm.dealer_agent.value == '')
		{
	  		  sfm_show_error_msg("Please Enter Unit : Dealer Agent");
   			  return false
			
		}
			else if (frm.source_application.value == 'Branch' && frm.branch.value == 0)
		{
	  		  sfm_show_error_msg("Please Enter Unit : Branch");
   			  return false			
		}
		else if (frm.source_application.value == 'Branch' && frm.branch_refferror.value == '')
		{
	  		  sfm_show_error_msg("Please Enter Unit : Branch Referror");
   			  return false		
		}
			else if (frm.source_application.value == 'Branch' && frm.marketingofficer.value == 0)
		{
	  		  sfm_show_error_msg("Please Enter Unit : Marketing Officer");
   			  return false
		}
		/*
			else if (frm.source_application.value == 'Branch' && frm.dealer.value == '')
		{
	  		  sfm_show_error_msg("Please Enter Unit : Dealer");
   			  return false
		}*/
else if (frm.veh_brand.value == '')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Brand");
   			  return false
			
		}
		else if (frm.veh_status.value == '0')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Status");
   			  return false
			
		}
	  	else if (frm.veh_type.value == '')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Type");
   			  return false
			
		}
		else if (frm.veh_unit.value == '')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Unit");
   			  return false
			
		}
		else if (frm.veh_yrmodel.value == '0')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Year Model");
   			  return false
			
		}
		else if (frm.veh_age.value == '')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Age");
   			  return false
			
		}
		else if (frm.veh_use.value == '0')
		{
			  sfm_show_error_msg("Please Enter Unit : Vehicle Use");
			  return false
			
		}
		else if (frm.selling_price.value == 0.00)
		{
			  sfm_show_error_msg("Please Enter : Selling Price");
			  return false
			
		}
		else if (frm.downpayment_actual.value == 0.00)
		{
			  sfm_show_error_msg("Please Enter Downpayment Actual");
			  return false
			
		}
		else if (frm.downpayment_percent.value == 0)
		{
			  sfm_show_error_msg("Please Enter Downpayment Percent");
			  return false
			
		}
			else if (frm.loanterm.value == 0)
		{
			  sfm_show_error_msg("Please Enter : Loan Term");
			  return false
			
		}

			else if (frm.rate.value == '')
		{
			  sfm_show_error_msg("Please Enter : Rate");
			  return false
			
		}
			else if (frm.amountloan.value == 0.00)
		{
			  sfm_show_error_msg("Please Enter : Amount Loan");
			  return false
			
		}
			else if (frm.monthly_amortization.value == 0.00)
		{
			  sfm_show_error_msg("Please Enter : Monthly Amortization");
			  return false
			
		}
			else if (frm.gmi_ratio.value == 0)
		{
			  sfm_show_error_msg("Please Enter : GMI Ratio");
			  return false
			
		}
			

		else if ((frm.gender.value == 2) && (frm.civilstatus.value != 1) &&
			(frm.borrower_mname.value == ''))
		{
			  sfm_show_error_msg("Middle Name is Required !!");
			  return false
		}	
	else if (frm.age.value <= 15)
	  {
	    	  sfm_show_error_msg("Invalid Age");
   			  return false
	  }

	<? if($this->loggedInUserType() == 'CA' || $this->loggedInUserType() == 'CO') { ?>
	// Only check the previous address when in CA / CO
		else if (frm.lenghtstay.value < 2 && frm.borrower_prev_address_st.value == '' && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Address Street");
   			  return false
		}
		else if (frm.lenghtstay.value < 2 && frm.borrower_prev_address_brgy.value == '' && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Address Barangay");
   			  return false
		}

		
		else if (frm.lenghtstay.value < 2 && frm.borrower_prev_address_province.value == 0 && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Address Province");
   			  return false
		}
		else if (frm.lenghtstay.value < 2 && frm.borrower_prev_address_city.value == 0 && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Address City");
   			  return false
		}
		else if (frm.lenghtstay.value < 2 && frm.prev_zipcode.value == '' && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Zip Code");
   			  return false
		}
else if (frm.lenghtstay.value < 2 && frm.lenghtstay_prev.value == '' && frm.residencetype.value != 1) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Lenght of Stay ");
   			  return false
		}
		else if (frm.lenghtstay.value < 2 && frm.residencetype_prev.value == '0' && frm.residencetype.value != 1 ) 
		{
			 sfm_show_error_msg("Residence Years is less than 2, Please Provide Previous Residence Type ");
   			  return false
		}
		
		<? } ?>

		
		
	<? if($this->loggedInUserType() == 'CA' || $this->loggedInUserType() == 'CO') { ?>
		
			else if (frm.cv_nfis.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - NFIS");
			  return false
		}	
			else if (frm.cv_cmap.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - CMap");
			  return false
		}
	
			else if (frm.cv_empver.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Employment Verification");
			  return false
		}	
			else if (frm.cv_busver.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Business Verification");
			  return false
		}	
			else if (frm.cv_trdchk.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Trade Checking");
			  return false
		}	
			else if (frm.cv_backgrd.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Background");
			  return false
		}	
			else if (frm.cv_bankref.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Bank Reference");
			  return false
		}	
			else if (frm.cv_creditchk.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Credit Check");
			  return false
		}	
			else if (frm.cv_pastdealings.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Past Dealings");
			  return false
		}	
		else if (frm.cv_income.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Income Verification");
			  return false
		}	
		// CV 2 
		
			else if (frm.cv_nfis2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - NFIS 2");
			  return false
		}	
			else if (frm.cv_cmap2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - CMap 2");
			  return false
		}
			else if (frm.cv_empver2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Employment Verification 2");
			  return false
		}	
			else if (frm.cv_busver2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Business Verification 2");
			  return false
		}	
			else if (frm.cv_trdchk2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Trade Checking 2");
			  return false
		}	
			
		else if (frm.cv_income2.value == '')
		{
			  sfm_show_error_msg("Please Enter : CV - Income Verification 2");
			  return false
		}	
		
		
		else if (ciDate>myDate)
	  {
			  sfm_show_error_msg("Ci Date:You cannot input a future date!!");
   			  return false

	  }	 
	  
	  	 else if (nfisDate>myDate)
	  {
			  sfm_show_error_msg("NFIS Date:You cannot input a future date!!");
   			  return false
	  }	 
	<? } ?>
		// Relational Check Start
		else if (frm.civilstatus.value == 2 || frm.civilstatus.value == 4)
		{
			spouseCheck();
			if(spochk == 0){
			sfm_show_error_msg("Error No Spouse Information");
 			 return false
			}
		}	
			else if (frm.civilstatus.value == 1)
		{
			spouseCheck();
			if(spochk == 1){
			sfm_show_error_msg("Error Civil Status:Single Status Has Spouse Information");
 			 return false
			}
		}	
		else if (appraisalDate>myDate)
	  {
			  sfm_show_error_msg("Appraisal Date:You cannot input a future date!!");
   			  return false
	  }	 
		// End of Relational Checks
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>

<script type="text/javascript">

/* Since we specified manualStartup=true, tabber will not run after
   the onload event. Instead let's run it now, to prevent any delay
   while images load.
*/

tabberAutomatic(tabberOptions);

</script>
<center>
<font color="#FFFFFF">
<?
$time = microtime();

$time = explode(" ", $time);

$time = $time[1] + $time[0];

$finish = $time;

$totaltime = ($finish - $start);

printf ("This page took %f seconds to load.", $totaltime);
?>
</font>
</center>