
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="assigntask">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>MA ASSIGNMENTS </strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td height="338"><table width="98%" height="334" align="center">
      <tr>
        <td width="55%" height="328"><table width="92%" border="1" align="left" >
            <tr>
              <td colspan="5" align="left"><strong>MA ASSIGNMENTS </strong></td>
            </tr>
            <tr>
              <td width="18%" align="left"><div align="center"><strong>Cap No </strong></div></td>
              <td width="25%" align="left"><div align="center"><strong>Borrower</strong></div></td>
              <td width="23%" align="left"><div align="center"><strong>Type of App </strong></div></td>
              <td width="17%" align="left"><div align="center"><strong>Sender</strong></div></td>
              <td width="17%" align="left"><div align="center"><strong>Assigned To </strong></div></td>
            </tr>
            <tr>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
            </tr>
            <tr>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
            </tr>
            <tr>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
            </tr>
            <tr>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
            </tr>
            <tr>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
              <td align="left">&nbsp;</td>
            </tr>
        </table></td>
        <td width="45%"><table width="354" border="1" align="right">
            <tr>
              <td colspan="2"><strong>Assign Tasks </strong></td>
              </tr>
            <tr>
              <td colspan="2">&nbsp;</td>
              </tr>
            <tr>
              <td colspan="2">&nbsp;</td>
              </tr>
            <tr>
              <td colspan="2">&nbsp;</td>
              </tr>
            <tr>
              <td colspan="2">&nbsp;</td>
              </tr>
            <tr>
              <td colspan="2">&nbsp;</td>
              </tr>
            <tr>
              <td width="239">&nbsp;</td>
              <td width="99" align="center"><strong>
                <input type="submit" name="button" id="button" value="Assign" />
              </strong></td>
            </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
</table>
</form>
