<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
.style1 {font-family: Verdana, Arial, Helvetica, sans-serif}
</Style>


<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ASSIGN TASK</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>

<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td colspan="6" align="center"><div align="left"><strong>CA ASSIGNMENTS</strong></div></td>
  </tr>
  <tr>
    <td width="10%" align="center"><strong>CAP NO.</strong></td>
    <td width="27%" align="center"><strong>BORROWER</strong></td>
    <td width="16%" align="center"><strong>TYPE OF APPLICATION </strong></td>
    <td width="20%" align="center"><strong>DATE/TIME</strong><strong></strong></td>
    <td width="14%" align="center"><strong>SENDER</strong></td>
    <td width="13%" align="center"><strong>ASSIGNED TO</strong></td>
  </tr>
  <? if ($this->row){?>
  <?php foreach($this->row as $row) : ?>
<form action="" method="post" name="assign-task-ca">
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'">
    <td><?=$row->capno?></td>
    <td onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'"><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$row->application_type?></td>
    <td align="center"><?=date("m/d/Y/ h:ia",strtotime($row->application_date))?></td>
    <td align="center"><?=$this->viewMa($row->created_by)?></td>
    <td><strong><span class="style1">
    <?=$this->form->assigned_to->setValue($row->submitted_ca)?>
    </span></strong>
   <input name="button" type="submit" value="Change"/>
   <input type="hidden" value="<?=$row->capno?>" name="cap"/>
    </td>
   
  </tr>
  </form>
  <?php endforeach; ?>
  <? } ?>

</table>

<p>&nbsp;</p>
