<style type="text/css">
<!--
input.btn {color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
width: 80px;
}
-->
</style>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.masubmit.onsubmit())
 {//this check triggers the validations
    document.masubmit.submit();
	//self.close();
	if (window.opener && !window.opener.closed) {
	window.opener.location='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>';
	}
 }
}
</SCRIPT> 
<center></center>
<form name="masubmit" method="post">


<table width="50%" border="0" align="center">
  <tr>
    <td colspan="2" align="left" valign="top">

</td>
    </tr>
  <tr>
    <td colspan="2" valign="top"><strong>  Last Remarks</strong>:      
      <?=stripslashes($this->lastremarks)?> <br />
      <strong>by: 
      <?=$this->viewMa($this->lastremarksby)?>
      </strong></td>
    </tr>
  <tr>
    <td width="17%" align="right" valign="top"><strong>Remarks</strong></td>
    <td width="83%"><?=stripslashes($this->form->submit_remarks)?></td>
  </tr>
  <tr>
    <td colspan="2" align="center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->detail?></td>
  </tr>
</table><table width="50%" border="0" align="center">
  <tr>
    <td><input type="button" name="score" value="OK" class="btn" onclick="javascript:submitform()" /></td>
    <td align="right"><input type="button" name="score2" value="CANCEL" class="btn" onclick="javascript:self.close()"/></td>
  </tr>
</table>
</form>
<? if($this->isSubmit) { ?>
<script type="text/javascript">
	alert("Submitted");
	self.close();
	setTimeout(refr(),5000);
</script>
<? } ?>
<script type="text/javascript">
//window.onblur=function(){self.close();};
</script>
<!--
javascript:window.close();
if (window.opener && !window.opener.closed) {
	window.opener.location='http://google.com';
}
-->

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("masubmit")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("submit_remarks","req","Submit Remarks is Required!!");

</script>



