
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.decision.onsubmit())
 {//this check triggers the validations
    document.decision.submit();
	self.close();
	setTimeout(refr(),5000);
 }
}

function refr(){
	if (window.opener && !window.opener.closed) {
	window.opener.location='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>';
	}
}


</SCRIPT> 
<form action="" method="post" name="decision">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>CREDIT DECISION</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="self.close()"><strong>
      EXIT
    </strong></td>
</tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td align="center">Decision</td>
  <td align="center">Date</td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td width="16%">&nbsp;</td>
  <td width="15%">CO</td>
  <td width="19%"><?=$this->form->co_name?></td>
  <td><?=$this->form->co_decision?></td>
  <td><?=$this->form->co_date?></td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>CSH</td>
  <td><?=$this->form->csh_name?></td>
  <td><?=$this->form->csh_decision?></td>
  <td><?=$this->form->csh_date?></td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>CMG</td>
  <td><?=$this->form->cmg_name?></td>
  <td width="15%"><?=$this->form->cmg_decision?></td>
  <td width="15%"><?=$this->form->cmg_date?></td>
  <td width="20%">&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>President</td>
  <td><?=$this->form->pres_name?></td>
  <td><?=$this->form->pres_decision?></td>
  <td><?=$this->form->pres_date?></td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td><strong>Sub - Crecom</strong></td>
  <td><?=$this->form->subcrecom_decision?></td>
  <td><?=$this->form->subcrecom_date?></td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td><strong>Crecom</strong></td>
  <td><?=$this->form->crecom_decision?></td>
  <td><?=$this->form->crecom_date?></td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td><strong>Board</strong></td>
  <td><?=$this->form->board_decision?></td>
  <td><?=$this->form->board_date?></td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td colspan="6" align="center"><strong>Overall Decision</strong></td>
  </tr>
<tr>
  <td align="center">&nbsp;</td>
  <td align="center">&nbsp;</td>
  <td><?=$this->form->application_name?></td>
  <td><?=$this->form->application_decision?></td>
  <td><?=$this->form->application_date?></td>
  <td align="center">&nbsp;</td>
</tr>
<tr>
  <td align="center">&nbsp;</td>
  <td colspan="4" align="center"><?=$this->form->submit_remarks?></td>
  <td align="center">&nbsp;</td>
</tr>
</table>
</form>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" RULES=NONE FRAME=BOX>
    <tr>
      <td width="12" align="center"><input type="button" name="button" id="button" value="Submit" onclick="javascript:submitform();"/></td>
    </tr>
</table>
</form>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("decision")
frmvalidator.EnableMsgsTogether();


frmvalidator.addValidation("co_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("csh_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("cmg_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("pres_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("subcrecom_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("crecom_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
frmvalidator.addValidation("board_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");

frmvalidator.addValidation("application_date","req","Final Decision Date Required!!");
frmvalidator.addValidation("application_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");


 function DoCustomValidation()
	{
	  var frm = document.forms["decision"];
	  	    if (frm.application_name.value == '')
	  		{
	    	  sfm_show_error_msg("Please Provide Overall Approve By: ");
   			  return false
	  		}
			else if (frm.application_decision.value == '')
	  		{
	    	  sfm_show_error_msg("Please Provide Overall Decision: ");
   			  return false
	  		}
		  	{
	    return true;
			}
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");

</script>