
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="pending">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>In Process Accounts</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td width="7%" align="center"><strong>CAP NO.</strong></td>
    <td width="23%" align="center"><strong>BORROWER</strong></td>
    <td width="13%" align="center"><strong>TYPE OF APPLICATION </strong></td>
    <td width="11%" align="center"><strong>LAST USER</strong></td>
    <td width="11%" align="center"><strong>PENDING TO</strong></td>
    <td width="18%" align="center"><strong>CURRENT STATUS</strong></td>
    <td width="18%" align="center"><strong>LEVEL</strong></td>
    <td width="17%" align="center"><strong>DATE/TIME</strong></td>
  </tr>
  <? if ($this->accntdetail){?>
  <?php foreach($this->accntdetail as $row) : ?>
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td><?=$row->capno?></td>
    <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$row->application_type?></td>
    <td align="center"><?=$this->viewMa($this->getLastUser($row->capno))?></td>
    <td align="center"><?=$this->getCurrentUser($row->account_status,$row->capno)?></td>
    <td align="center"><b>
      <?=$this->viewAccountStatus($row->account_status)?>
    </b></td>
    <td align="center"><b>
      <?=$this->autoRouteLevel($row->capno,'')?>
    </b></td>
    <td align="center"><?=date("m/d/Y/ h:ia",strtotime($this->getLastDate($row->capno)))?></td>
  </tr>
  <?php endforeach; ?>
  <? } ?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</form>
<p>
  <?= $this->paginationControl($this->accntdetail, 'Sliding', 'pagination.phtml'); ?>
</p>
