<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
.style1 {font-size: 9pt}
</Style>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  

<form action="" method="post" name="with_decision">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>WITH DECISION </strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table width="334" border="0">
  <tr>
    <td width="84"><a href="<?=$this->baseUrl()?>/index/inbox-with-decision/" class="style1">ALL</a></td>
    <td width="113"><a href="<?=$this->baseUrl()?>/index/inbox-with-decision/status/approved" class="style1">APPROVED</a></div></td>
    <td width="123"><a href="<?=$this->baseUrl()?>/index/inbox-with-decision/status/rejected" class="style1">REJECTED</a></td>
  </tr>
</table>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td width="12%" align="center"><strong>CAP NO. </strong></td>
    <td width="25%" align="center"><strong>BORROWER</strong></td>
    <td width="13%" align="center"><strong>TYPE OF APPLICATION </strong></td>
    <td width="12%" align="center"><strong>DECIDED DATE</strong></td>
    <td width="16%" align="center"><strong>DECISION</strong></td>
    </tr>
  <? if ($this->detail){?>
  <?php foreach($this->detail as $row) : ?>
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td><?=$row->capno?></td>
    <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$row->application_type?></td>
    <td align="center"><?=date("d-m-Y",strtotime($row->date_decided))?></td>
    <td align="center"><?=$this->viewAccountStatus($row->account_status)?></td>
    </tr>
  <?php endforeach; ?>
  <? } ?>
  </table>
<p>&nbsp;</p>
</form>
<p>
  <?= $this->paginationControl($this->detail, 'Sliding', 'pagination.phtml'); ?>
</p>