
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<script type="text/javascript">
$(document).ready(function() 
    { 
        $("#myTable").tablesorter(); 
    } 
); 
</script>
<form action="" method="post" name="add">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>RTS</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" id="myTable" class="tablesorter">
    <thead>
  <tr>
    <th width="11%" align="center"><strong>CAP NO.</strong></td>
    <th width="29%" align="center"><strong>BORROWER</strong></td>
    <th width="15%" align="center"><strong>TYPE OF APPLICATION </strong></td>
    <th width="17%" align="center"><strong>DATE/TIME RECEIVED</strong><strong></strong></td>
    <th width="28%" align="center"><strong>RETURNED BY </strong></td>
  </tr>
      </thead>
	<tbody>
  <? if ($this->accntdetail){?>
  <?php foreach($this->accntdetail as $row) : ?>
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white';Tip('<?=$this->getLastRemarks($row->capno)?>')"
  onmouseout="this.style.background='white';this.style.color='black';UnTip();" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td><?=$row->capno?></td>
    <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$row->application_type?></td>
    <td><?=date("m/d/Y/ h:ia",strtotime($this->getRtsdate($row->capno,'ma')))?></td>
    <td><?=$this->viewMa($this->getLastUser($row->capno))?></td>
  </tr>
  <?php endforeach; ?>
  <? } ?>
</tbody>
</table>
</form>
<p>&nbsp;</p>
