
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.decision.onsubmit())
 {//this check triggers the validations
    document.decision.submit();
	self.close();
	setTimeout(refr(),5000);
 }
}

function submitform2()
{
 if(document.application.onsubmit())
 {//this check triggers the validations
    document.application.submit();
	self.close();
	setTimeout(refr(),5000);
 }
}

function refr(){
	if (window.opener && !window.opener.closed) {
	window.opener.location='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>';
	}
}


</SCRIPT> 
<script type="text/javascript">
function popupUnloadHandler() {
	if (window.opener && !window.opener.closed) {
window.opener.location.reload();
}
}
window.onunload = popupUnloadHandler;
</script>
<form action="" method="post" name="decision">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>CREDIT DECISION</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="self.close()"><strong>
      EXIT
    </strong></td>
</tr>
</table>

<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td width="9%" align="center">&nbsp;</td>
  <td width="27%" align="center">&nbsp;</td>
  <td width="20%">&nbsp;</td>
</tr>
<tr>
  <td width="13%">&nbsp;</td>
  <td width="18%">Authority</td>
  <td width="13%">Decision</td>
  <td>Date</td>
  <td>Remarks</td>
  <td>&nbsp;</td>
</tr>
<? foreach($this->history as $details) { ?>
<tr>
  <td>&nbsp;</td>
  <td><?=$this->viewMa($details->approved_by)?></td>
  <td><?=$details->decision?></td>
  <td><?=$details->date_approval?></td>
  <td><?=$details->reason?></td>
  <td><input type="button" name="button" id="button" value="Delete" onclick="javascript: if (confirm('Are you sure you want to delete this?')) window.location='<?=$this->baseUrl().'/index/deldecision/id/'.$details->id.'/red/decision/cap/'.$details->capno?>'"/></td>
</tr>
  <? } ?>
<tr>
  <td>&nbsp;</td>
  <td><?=$this->form->approved_by?></td>
  <td><?=$this->form->decision?></td>
  <td><input type="text" name="date" value="" size="8"/></td>
  <td><?=$this->form->reason?></td>
  <td><input type="submit" name="Submit" id="Submit" value="Add" onclick="chkapproval();return false;"/></td>
</tr>
</table>
</form>
<form name="application" method="post">
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" RULES=NONE FRAME=BOX>
    <tr>
      <td align="center"><strong>Overall Decision</strong></td>
    </tr>
    <tr>
      <td align="center"><?=$this->form->application_name?>
      <?=$this->form->application_decision?></td>
    </tr>
    <tr>
      <td align="center"><?=$this->form->submit_remarks?></td>
    </tr>
    <tr>
      <td width="12" align="center"><center><input type="submit" name="Submit" id="button" value="Submit" onclick="refr();"/></center></td>
    </tr>
</table>
</form>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("application")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("application_name","dontselect=''","Approver Required!!");
frmvalidator.addValidation("application_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");


</script>

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("decision")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("approved_by","dontselect=''","Credit Authority Required!!");
frmvalidator.addValidation("decision","dontselect=''","Decision Required!!");
frmvalidator.addValidation("date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
</script>