<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 9pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 10px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>



<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>Nature of Business</strong></td>
    <td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="javascript:self.close()"><strong> Close </strong></td>
  </tr>
</table>
<table width="85%" height="938" border="0">
  <tr>
    <td colspan="2"><strong>A.  AGRICULTURE, HUNTING AND FORESTRY</strong></td>
  </tr>
  <tr>
    <td width="8%">&nbsp;</td>
    <td width="92%">Growing of crops</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Farming of animals</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Agricultural and animal husbandry  service activities, except  veterinary</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Hunting, trapping and game  propagation including  related service activities</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Forestry, logging and relared service activities</td>
  </tr>
  <tr>
    <td colspan="2"><strong>B.FISHING</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Fishing </td>
  </tr>
  <tr>
    <td colspan="2"><strong>C.</strong><strong>MINING AND  QUARRYING </strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Metallic ore mining</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Non-metallic mining and quarrying</td>
  </tr>
  <tr>
    <td colspan="2"><strong>D.</strong><strong>MANUFACTURING</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of food and products  and beverages</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of tobacco products</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of textiles</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of wearing apparel</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Tanning and dressing of leather;  manufacture of luggage,  handbags and footwear</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of wood, wood products  and cork,except  furniture; manufacture of articles of bamboo,  cane, rattan and the like; manufacture of  plaiting materials</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of paper and paper  products</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Publishing, printing and  reproduction of recordedmedia</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of coke, refined petroleum and other fuel products</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of rubber and plastic products</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of other non-metallic mineral products</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacturing of basic metals</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of fabricated metal products,except machinery and equipment</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of machinery and  equipment, n.e.c</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of office, accounting and computing machinery</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of electrical  machinery and apparatus, n.e.c.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of radio, television and communication equipment and apparatus</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of medical, precision  and optical instrument, watches and clocks</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of motor vehicles, trailers and semi-trailers</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture of other transport  equipment</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacture and repair of furniture</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Recycling </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Manufacturing, n.e.c.</td>
  </tr>
  <tr>
    <td colspan="2"> <strong>E. ELECTRICITY, GAS AND WATER</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Electricity, gas steam and hot water supply</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Collection, purification and  distribution of water</td>
  </tr>
  <tr>
    <td colspan="2"><strong>F. CONSTRUCTION</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Construction</td>
  </tr>
  <tr>
    <td colspan="2"><strong>G. WHOLESALE AND RETAIL  TRADE; REPAIR OF MOTOR    &nbsp; VEHICLES, MOTORCYCLES ANS  PERSONAL AND HOUSEHOLDS GOODS</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Sale, maintenance and repair of motor vehicles and motorcycles, retail sale  of automotive fuel</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Wholesale trade and commission  trade, except of motor vehicles and motorcycles</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Retail trade of motor vehicles and  motorcycles, repair of personal and household goods</td>
  </tr>
  <tr>
    <td colspan="2"><strong>H. HOTEL AND RESTAURANT</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Hotel and restaurants</td>
  </tr>
  <tr>
    <td colspan="2"><strong>I.</strong><strong> TRANSPORT, STORAGE AND COMMUNICATIONS</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Land transportation; transport via pipelines</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Water transport</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Air transport</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Supporting and auxiliary transport activities; activities of travel  agencies</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Postal and telecommunications  services</td>
  </tr>
  <tr>
    <td colspan="2"><strong>J. FINANCIAL INTERMEDIATION</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Banking institutions</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Non-bank financial intermediation</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Insurance and pension funding,  except compulsory social security</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Activities auxiliary to financial  intermediation </td>
  </tr>
  <tr>
    <td colspan="2"><strong>K. REAL ESTATE, RENTING AND BUSINESS ACTIVITIES</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Real estate activities</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Renting of machinery and equipment  without operator;personal and household goods</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Computer and related activities</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Research and development</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Miscellaneous business activities</td>
  </tr>
  <tr>
    <td colspan="2"><strong>L. PUBLIC  ADMINISTRATION AND DEFENSE;COMPULSORY SOCIAL SECURITY </strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Public administration and defense;  compulsory social security</td>
  </tr>
  <tr>
    <td colspan="2"><strong>M. EDUCATION</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Public education services </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Private education services</td>
  </tr>
  <tr>
    <td colspan="2"><strong>N. HEALTH AND SOCIAL WORK</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Health And Social Work</td>
  </tr>
  <tr>
    <td colspan="2"><strong>O. OTHER COMMUNITY,  SOCIAL AND PERSONAL SERVICE ACTIVITIES</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Sewage and refuse disposal, sanitation and similar activities</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Activities of membership  organizations, n.e.c.</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Recreational, cultural and  sporting activities</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Other service activities</td>
  </tr>
  <tr>
    <td colspan="2"><strong>P. PRIVATE HOUSEHOLDS WITH EMPLOYED PERSONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Private households with employed persons</td>
  </tr>
  <tr>
    <td colspan="2"><strong>Q. EXTRA-TERRITORIAL ORGANIZATIONS AND BODIES</strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Extra-territorial organizations and bodies</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
 