     <script type="text/javascript">
    <!--
    $(function () {
        var cat = $('#categorySelect');
        var el = $('#elementSelect');

        // note that we're assigning in reverse order
        // to allow the chaining change trigger to work
        cat.selectChain({
            target: el,
            url: '<?=$this->baseUrl();?>/inc/query.php',
            data: { ajax: true }
        }).trigger('change');

    });
    //-->
 </script>
    <script src="<?=$this->baseUrl();?>/js/select-chain.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<style type="text/css">
.commenthidden {display:none}
.commentshown {display:inline}
</style>
<script type="text/Javascript">
function togglecomments (postid) {
var whichpost = document.getElementById(postid);
if (whichpost.className=="commentshown") { whichpost.className="commenthidden"; } else { whichpost.className="commentshown"; }
} </script>

<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<table border="0" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: white white white white;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td colspan="5" bgcolor="#FF3333"><strong><font color="#FFFF00">Credit Cards Owned</font></strong></td>
  </tr>
</table>
<br />


<table width="100%" border="0">
  <tr align="left">
    <td width="20%" align="center"><strong>CREDIT COMPANY</strong></td>
    <td width="25%" align="center"><strong>CREDIT LIMIT</strong></td>
    <td width="19%" align="center"><strong>Number of Years</strong></td>
    <td width="36%" align="center">&nbsp;</td>
  </tr>
   <?php foreach($this->creditcarddetail as $creditcarddetails) :?>
  <tr align="left">
    <td align="center"><?=$creditcarddetails->company?></td>
    <td align="center">P<?=number_format($creditcarddetails->limit,2)?></td>
    <td align="center"><?=$creditcarddetails->expiry_date?></td>
    <td align="left"><input name="button2" type="button" onclick="javascript: if (confirm('Are you sure you want to delete this Credit Card Detail?')) window.location='<?=$this->baseUrl().'/index/delcreditcard/id/'.$creditcarddetails->id.'/cap/'.$this->capno?>'" value="Delete" /></td>
  </tr>
    <?php endforeach; ?>
</table>
<a aiotitle="click to expand" href="javascript:togglecomments('credit_details')"
 >Add Credit Card Details</a>
<div align="center" id="credit_details" class="commenthidden">

<form name="creditcard" method="post">
<table width="100%" border="0">
<tr align="left">
  <td width="20%" align="center">CREDIT COMPANY</td>
  <td width="25%" align="center">CREDIT LIMIT</td>
  <td width="19%" align="center">NUMBER OF YEARS</td>
  <td width="36%" align="center">&nbsp;</td>
  </tr>
<tr align="left">
  <td align="center"><?=$this->form->creditcomp?></td>
  <td align="center">P
    <?=$this->form->creditlimit?></td>
  <td align="center"><?=$this->form->expiry_date?></td>
  <td align="left"><input name="submit" type="submit" value="Add Credit Card Details" id="submit" /></td>
</tr>
  </tr>

</table>
</form>
</div>
<br />
<table border="0" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: white white white white;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td colspan="5" bgcolor="#FF3333"><strong><font color="#FFFF00">Existing Loans</font></strong></td>
  </tr>
</table>
<br />

<table width="100%" border="0">
  <tr align="left">
    <td width="15%" align="center"><strong>BANK</strong></td>
    <td width="17%" align="center"><strong>TYPE OF FACILITY</strong></td>
    <td width="17%" align="center"><strong>OUTSTANDING BALANCE</strong></td>
    <td width="18%" align="center"><strong>MONTHLY AMORTIZATION</strong></td>
    <td width="18%" align="center"><strong>LOAN AMOUNT</strong></td>
    <td width="24%" align="center"><strong>REMARKS</strong></td>
    <td width="8%" align="center">&nbsp;</td>
  </tr>
  <?php foreach($this->loandetail as $loandetails) :?>
  <tr align="left">
    <td align="center"><?=$loandetails->bank?></td>
    <td align="center"><?=$loandetails->facility_type?></td>
    <td align="center">P<?=number_format($loandetails->amount,2)?></td>
    <td align="center">P<?=number_format($loandetails->monthly_amortization,2)?></td>
    <td align="center">P<?=number_format($loandetails->loan_amount,2)?></td>
    <td align="center"><?=$loandetails->collateral?></td>
    <td align="left"><input name="button3" type="button" onclick="javascript: if (confirm('Are you sure you want to delete this Credit Card Detail?')) window.location='<?=$this->baseUrl().'/index/delexistloan/id/'.$loandetails->id.'/cap/'.$this->capno?>'" value="Delete" /></td>
  </tr>
      <?php endforeach; ?>
</table>
<a aiotitle="click to expand" href="javascript:togglecomments('existloan')"
 >Add Existing Loan Details</a>
<div align="center" id="existloan" class="commenthidden">

<form name="existloan" method="post">
<table width="100%" border="0">
<tr align="left">
  <td width="15%" align="center">BANK</td>
  <td width="17%" align="center">TYPE OF FACILITY</td>
  <td width="17%" align="center">OUTSTANDING BALANCE</td>
  <td width="18%" align="center">MONTHLY AMORTIZATION</td>
  <td width="18%" align="center">LOAN AMOUNT</td>
  <td width="24%" align="center">REMARKS</td>
  <td width="8%" align="center">&nbsp;</td>
  </tr>

<tr align="left">
  <td align="center"><?=$this->form->bank?></td>
  <td align="center"><?=$this->form->facility_type?></td>
  <td align="center"><?=$this->form->amount?></td>
  <td align="center"><?=$this->form->monthly_amortization?></td>
  <td align="center"><?=$this->form->loan_amount?></td>
  <td align="center"><?=$this->form->collateral?></td>
  <td align="left"><input name="submit" type="submit" value="Add Exist Loan Detail" id="submit" /></td>
</tr>


</table>
</form>
</div>

<br />
<table border="0" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: white white white white;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td colspan="5" bgcolor="#FF3333"><strong><font color="#FFFF00">Business Financials</font></strong></td>
  </tr>
</table> </br>
<div align="center" id="bf_liabilities" class="commenthidden">
  <form method="post" name="bf_liabilities" id="bf_liabilities">
    <table width="100%" border="0">
      <tr align="left">
        <td width="26%" align="center">LIABILITIES</td>
        <td width="33%" align="center">EMV</td>
        <td width="30%" align="center">REMARKS</td>
        <td width="11%" align="center">&nbsp;</td>
      </tr>
      <tr align="left">
        <td align="center"><?=$this->form->business_liability?></td>
        <td align="center"> P
          <?=$this->form->business_liability_emv?></td>
        <td align="center"><?=$this->form->business_liability_remarks?></td>
        <td align="left"><input name="submit" type="submit" value="Add Business Liabilities Details" id="submit" /></td>
      </tr>
      <tr>
        <td></tr></td>
      </tr>
    </table>
  </form>
</div>
<table width="100%" border="0">
  <tr align="left">
    <td width="22%" align="center"><strong>LIABILITIES</strong></td>
    <td width="37%" align="center"><strong>EMV</strong></td>
    <td width="30%" align="center"><strong>REMARKS</strong></td>
    <td width="11%" align="center">&nbsp;</td>
  </tr>
  <?php foreach($this->bf_liabilities_detail as $bf_liabilities_details) :?>
  <tr align="left">
    <td height="26" align="center"><?=$bf_liabilities_details->business_liability?></td>
    <td align="center">P
      <?=number_format($bf_liabilities_details->business_liability_emv,2)?></td>
    <td align="center"><?=$bf_liabilities_details->business_liability_remarks?></td>
    <td align="left"><div align="center">
      <input name="button4" type="button" onclick="javascript: if (confirm('Are you sure you want to delete this Business Financial Liability Detail?')) window.location='<?=$this->baseUrl().'/index/delbfliabilities/id/'.$bf_liabilities_details->id.'/cap/'.$this->capno?>'" value="Delete" />
    </div></td>
  </tr>
  <?php endforeach; ?>
</table>
<br />
<a aiotitle="click to expand" href="javascript:togglecomments('bf_liabilities')"
 >Add Business Liabilities Details</a><br />
<p>
  <script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("existloan")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("facility_type","req","Type of Facility is Required!!");
frmvalidator.addValidation("amount","req","Amount is Required!!");
frmvalidator.addValidation("collateral","req","Collateral is Required!!");


 function DoCustomValidationLoan()
	{
	  var frm = document.forms["existloan"];
   	  if (frm.bank.value == '0'){
	    	  sfm_show_error_msg("Please Choose Bank");
			  return false }
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidationLoan");
</script>
</p>
<p>
  <script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("creditcard")
frmvalidator.EnableMsgsTogether();


frmvalidator.addValidation("creditcomp","req","Credit Card Company is Required!!");

//frmvalidator.addValidation("creditlimit","req","Credit Card Limit is Required!!");

//frmvalidator.addValidation("expiry_date","req","Date Opened is Required!!");
//frmvalidator.addValidation("expiry_date","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
/*
 function DoCustomValidationCredit()
	{
	  var frm = document.forms["creditcard"];
   	  if (frm.creditcomp.value == '0'){
	    	  sfm_show_error_msg("Please Choose Credit Card Company");
			  return false }
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidationCredit");
*/
</script>
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("existloan")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("facility_type","req","Type of Facility is Required!!");
//frmvalidator.addValidation("amount","req","Amount is Required!!");



 function DoCustomValidationLoan()
	{
	  var frm = document.forms["existloan"];
   	  if (frm.bank.value == '0'){
	    	  sfm_show_error_msg("Please Choose Bank");
			  return false }
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidationLoan");
</script>
