<style type="text/css">
<!--
input.btn {color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
width: 80px;
}
-->
</style>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.masubmit.onsubmit())
 {//this check triggers the validations
    document.masubmit.submit();
 }
}
 </SCRIPT> 
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<form name="masubmit" method="post">
  <table width="50%" border="0" align="center">
    <tr>
      <td colspan="2">Please check the field/s for Amendment</td>
    </tr>
    <tr>
      <td width="49%"><label>
        <input type="checkbox" name="reconvalues[]" value="dealer" />
        Dealer</label><br /></td>
      <td width="51%"><input type="checkbox" name="reconvalues[]2" value="loanterm"/>
Term </td>
    </tr>
    <tr>
      <td width="49%"><label>
        <input type="checkbox" name="reconvalues[]" value="veh_brand" />
        Brand
      </label></td>
      <td width="51%"><input type="checkbox" name="reconvalues[]" value="rate"/>
        Add on Rate </td>
    </tr>
    <tr>
      <td width="49%">
        <label>
          <input type="checkbox" name="reconvalues[]" value="veh_unit" />
          Unit</label>
</td>
      <td width="51%"><input type="checkbox" name="reconvalues[]" value="addon_rate" />
        Financing Scheme </td>
    </tr>
    <tr>
      <td><input type="checkbox" name="reconvalues[]" value="selling_price"  />
        Selling Price</td>
      <td><!--<input type="checkbox" name="reconvalues[]" value="effective_yield"/>
        Effective Yield--> </td>
    </tr>
    <tr>
      <td><input type="checkbox" name="reconvalues[]" value="downpayment_percent"/>
        Downpayment </td>
      <td><!--<input type="checkbox" name="reconvalues[]" value="dealer_incentive"/>
        Dealer Incentive--></td>
    </tr>
  </table> 
<table width="50%" border="0" align="center">
  <tr>
    <td colspan="2" align="left" valign="top">

</td>
  </tr>
  <tr>
    <td width="17%" align="right" valign="top"><strong>Remarks</strong></td>
    <td width="83%"><?=$this->form->submit_remarks?></td>
  </tr>
  <tr>
    <td colspan="2" align="center">Recon this Application ?</td>
  </tr>
</table><table width="50%" border="0" align="center">
  <tr>
    <td align="center"><input type="button" name="score" value="OK" class="btn" onclick="javascript:submitform()" /></td>
  </tr>
</table>
</form>


<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("masubmit")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("submit_remarks","req","Submit Remarks is Required!!");
</script>



