
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 8px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:8px; color:#660000;}
</Style>

<form action="" method="post" name="add">
<table border=1 width="102%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>REPORT GENERATION</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td width="18%">&nbsp;</td>
</tr>
<tr><td width="2%">&nbsp;</td>
  <td width="10%">&nbsp;</td>
  <td width="21%">&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>Employment</td>
  <td><?=$this->form->employment?></td>
  <td width="15%">Area</td>
  <td width="19%"><?=$this->form->area?></td>
  <td>Score</td>
  <td><?=$this->form->score?></td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td>Actions</td>
  <td><?=$this->form->actions?></td>
  <td>User</td>
  <td><?=$this->form->user?></td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td><div align="left">Period</div></td>
  <td>&nbsp;</td>
  <td>Term</td>
  <td><?=$this->form->term?></td>
  <td>Decision</td>
  <td><?=$this->form->decision?></td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>From <?=$this->form->fromdate?></td>
  <td>To
    <?=$this->form->todate?></td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td><?=$this->form->submit?></td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td colspan="6"><div align="right"><strong>
    <input type="submit" name="button" id="button" value="Print Preview" onclick = "window.open('<?=$this->baseURL();?>/index/reportprint/cap/<?=$this->capno?>','mywindow','width=800,height=600,scrollbars=yes,resizable=no, menubar=yes')" />
  </strong></div></td>
  </tr>
</table>
</form>

<table width="102%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td width="7%" align="center"><strong>CAP NO.</strong></td>
    <td width="23%" align="center"><strong>Borrower</strong></td>
    <td width="12%" align="center"><strong>Employment</strong></td>
    <td width="12%" align="center"><strong>Application Date</strong></td>
    <td width="9%" align="center"><strong>DP</strong></td>
    <td width="8%" align="center"><strong>Term</strong></td>
    <td width="8%" align="center"><strong>Score</strong></td>
    <td width="6%" align="center"><strong>User</strong></td>
    <td width="8%" align="center"><strong>Decision</strong></td>
  </tr>
  <? if ($this->rows){?>
  <?php foreach($this->rows as $row) : ?>  
  <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td align="center"><?=$row->capno?></td>
    <td align="center"><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$row->empbus_status?></td>
    <td align="center"><?=date('M-d-Y',strtotime($row->application_date))?></td>
    <td align="center"><?=$row->downpayment_percent?> %</td>
    <td align="center"><?=$row->loanterm?></td>
    <td>&nbsp;</td>
    <td align="center"><?=$this->viewMa($row->created_by)?></td>
    <td>&nbsp;</td>
  </tr>
  <?php endforeach; ?>
  <? } ?>
</table>
<table width="102%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" RULES=NONE FRAME=BOX>

    <tr>
      <td colspan="11">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="11">Total No. of Accounts
      <?=$this->form->totalaccounts?></td>
    </tr>
    <tr>
      <td colspan="11"><div align="center">Summary</div></td>
    </tr>
    <tr>
      <td height="25"><div align="center"></div></td>
      <td colspan="2">Employment</td>
      <td colspan="2">Actions</td>
      <td colspan="2">Term</td>
      <td colspan="2">Score</td>
      <td colspan="2">Decision</td>
    </tr>
    <tr>
      <td height="25">&nbsp;</td>
      <td>&nbsp;</td>
      <td>Employed:</td>
      <td>&nbsp;</td>
      <td>Submit:</td>
      <td>&nbsp;</td>
      <td>12:</td>
      <td width="1%">&nbsp;</td>
      <td width="13%">F2:</td>
      <td width="1%">&nbsp;</td>
      <td width="18%">Approved:</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>Self - Employed:</td>
      <td>&nbsp;</td>
      <td>Recommend:</td>
      <td>&nbsp;</td>
      <td>24:</td>
      <td>&nbsp;</td>
      <td>F1:</td>
      <td>&nbsp;</td>
      <td>Rejected:</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>32:</td>
      <td>&nbsp;</td>
      <td>P1:</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>48:</td>
      <td>&nbsp;</td>
      <td>P2:</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>60:</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>72:</td>
      <td colspan="3">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td width="4%">&nbsp;</td>
      <td width="2%">&nbsp;</td>
      <td width="23%">&nbsp;</td>
      <td width="1%">&nbsp;</td>
      <td width="16%">&nbsp;</td>
      <td width="1%">&nbsp;</td>
      <td width="20%">&nbsp;</td>
      <td colspan="3">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
</table>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("add")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("borrower_pres_address_no","req","Address No is Required!!");
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");



 function DoCustomValidation()
	{
	  var frm = document.forms["add"];
   	  if (frm.typeloan.value == '0'){
	    	  sfm_show_error_msg("Please Choose Loan Type");
			  return false }
	   else if (frm.source_application.value == '0')
	  {
	    	  sfm_show_error_msg("Please Choose Source Application");
			  return false
	  } 
	    else if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.promo_avail.value == '1' && frm.promo.value == '1')
	  {
	    	  sfm_show_error_msg("Please Choose a Promo");
			  return false
	  }
	  	 else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Last Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_fname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse First Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }
	  	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_mname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }

	  
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>
