
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="add">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>SEARCH ACCOUNT</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table border=0 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="3">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr><td width="2%">&nbsp;</td>
  <td width="9%">&nbsp;</td>
  <td width="21%">&nbsp;</td>
  <td colspan="3"><strong>Date</strong></td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>Cap No.</td>
  <td><?=$this->form->capno?></td>
  <td colspan="5">From
    <?=$this->form->startdate?>    To
    <?=$this->form->enddate?> </td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>Borrower LastName, FirstName</td>
  <td><?=$this->form->borrower_lname?></td>
  <td>Source of Application</td>
  <td colspan="2"><?=$this->form->source_application?></td>
  <td width="15%">Marketing Assistant</td>
  <td width="18%"><?=$this->form->marketingassistant?></td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>Type of Loan</td>
  <td><?=$this->form->typeloan?></td>
  <td>Decision</td>
  <td colspan="2"><?=$this->form->decision?></td>
  <td>Credit Analyst</td>
  <td><?=$this->form->creditanalyst?></td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>Sort By:</td>
  <td><?=$this->form->sortby?></td>
  <td>&nbsp;</td>
  <td width="5%">&nbsp;</td>
  <td width="15%">&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td align="center">&nbsp;</td>
  <td><?=$this->form->submit?></td>
  </tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td colspan="2">&nbsp;</td>
  <td colspan="2" align="center">&nbsp;</td>
</tr>
</table>
</form>

<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" id="hor-zebra">
   <thead> 
  <tr>
    <th width="9%" align="center"><strong>CAP NO.</strong></td>
    <th width="22%" align="center"><strong>Borrower</strong></td>
    <th width="7%" align="center"><strong>Loan Type</strong></td>
    <th width="7%" align="center"><strong>M.A</strong></td>
    <th width="8%" align="center"><strong>C.A</strong></td>
    <th width="9%" align="center"><strong>LAST USER</strong></td>
    <th width="16%" align="center"><strong>ACTION TAKEN</strong></td>
    <th width="16%" align="center"><strong>CURRENT USER    </strong>    
    <th width="12%" align="center"><strong>TIME/DATE</strong></td>
  </tr>
  </thead>
  <? if ($this->rowResult){?>
  <?php foreach($this->rowResult as $row) : 
  $color = $this->getColorSearch($row->account_status,$row->capno);
  ?>  
  
  <tr class ="odd" style="color:<?=$color?>" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='#e8edff';this.style.color='<?=$color?>'" onclick="window.location.href='<?=$this->baseUrl()?>/index/account/cap/<?=$row->capno?>'">
    <td align="center"><?=$row->capno?></td>
    <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
    <td align="center"><?=$this->viewTypeLoan($row->loantype)?></td>
    <td align="center"><?=$this->viewMa($row->created_by)?></td>
    <td align="center"><?=$this->viewMa($row->submitted_ca)?></td>
    <td align="center"><?=$this->viewMa($this->getHistory($row->capno,'by'))?></td>
    <td align="center"><?=$this->viewAccountStatus($row->account_status)?></td>
    <td align="center"><?=$this->getCurrentUser($row->account_status,$row->capno)?></td>
    <td align="center"><?=date("m/d/Y/ h:ia",strtotime($this->getHistory($row->capno,'date')))?></td>
  </tr>
  <?php endforeach; ?>

  <? } ?>
</table>
  <? //$this->paginationControl($this->rowResult, 'Sliding', 'pagination.phtml'); ?>

<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" RULES=NONE FRAME=BOX>

    <tr>
      <td colspan="5" align="center">
      <b><font color='#CFB53B'>&#9608; - Encodes </font></b>&nbsp&nbsp
      <b><font color='#458B00'>&#9608; - In Process </font></b>&nbsp&nbsp
      <b><font color='#FF6347'>&#9608; - Ouright </font></b>&nbsp&nbsp
 <b><font color='#003F87'>&#9608; - Approved </font></b>&nbsp&nbsp
  <b><font color='#CC1100'>&#9608; - Rejected </font></b>&nbsp&nbsp
    <b><font color='#8F8F8F'>&#9608; - Book In Process </font></b>&nbsp&nbsp
     <b><font color='#292421'>&#9608; - Booked </font></b>&nbsp&nbsp

      </td>
    </tr>
    <tr><td width="8%">&nbsp;</td>
      <td colspan="2"><strong>Total No. of Accounts: 
          
      <?=$this->totalaccounts?>
      </strong></td>
      <td colspan="2"><strong>Total Amount of Loan: </strong></td>
    </tr>
</table>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("add")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("borrower_fname","req","Borrower First Name is Required!!");
frmvalidator.addValidation("borrower_fname","alphabetic_space","First Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_lname","req","Borrower Last Name is Required!!");
frmvalidator.addValidation("borrower_lname","alphabetic_space","Last Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("borrower_mname","req","Borrower Middle Name is Required!!");
frmvalidator.addValidation("borrower_mname","alphabetic_space","Middle Name : Alphabetic and Spaces Only !!");
frmvalidator.addValidation("birthdate","req","Date of birth is Required!!");
frmvalidator.addValidation("birthdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("borrower_pres_address_no","req","Address No is Required!!");
frmvalidator.addValidation("borrower_pres_address_st","req","Address Street is Required!!");
frmvalidator.addValidation("borrower_pres_address_brgy","req","Address Barangay is Required!!");
frmvalidator.addValidation("borrower_pres_address_city","req","Address City is Required!!");
frmvalidator.addValidation("borrower_pres_address_province","req","Address Province is Required!!");

frmvalidator.addValidation("landline","regexp=[0-9-]","Invalid Phone Format XX-XXX-XXX");
frmvalidator.addValidation("mobile","regexp=[0-9-]","Invalid Mobile Format XX-XXX-XXX");
frmvalidator.addValidation("email","email","Not a Valid Email Address");



 function DoCustomValidation()
	{
	  var frm = document.forms["add"];
   	  if (frm.typeloan.value == '0'){
	    	  sfm_show_error_msg("Please Choose Loan Type");
			  return false }
	   else if (frm.source_application.value == '0')
	  {
	    	  sfm_show_error_msg("Please Choose Source Application");
			  return false
	  } 
	    else if (frm.gender.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Gender");
   			  return false
	  }	  
	  	else if (frm.civilstatus.value == '0')
	  {
	    	  sfm_show_error_msg("Please Enter Civil Status");
   			  return false
	  }	  
	  	else if (frm.promo_avail.value == '1' && frm.promo.value == '1')
	  {
	    	  sfm_show_error_msg("Please Choose a Promo");
			  return false
	  }
	  	 else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Last Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_fname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse First Name");
   			  return false
	  }
	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_lname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }
	  	  	  else if ((frm.civilstatus.value == '2') && frm.borrower_spouse_mname.value == '')
	  {
	    	  sfm_show_error_msg("Please Enter Spouse Middle Name");
   			  return false
	  }

	  
	  {
	    return true;
	  }
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>
