<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 9pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 10px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>



<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>SPECIAL OCCUPATIONS</strong></td>
  </tr>
</table>
<table width="100%" height="300" border="0">
  <tr>
    <td width="8%"><div align="right">1</div></td>
    <td width="92%">Entertainers such as actors, singers, musicians,  hostesses and masseurs</td>
  </tr>
  <tr>
    <td><div align="right">2</div></td>
    <td>Unless a proof of fixed income is shown, sales  professionals for real estate, insurance, memorial parks, appliances and cars </td>
  </tr>
  <tr>
    <td><div align="right">3</div></td>
    <td> Ambulant peddlers</td>
  </tr>
  <tr>
    <td><div align="right">4</div></td>
    <td>Operators and employees of small beerhouses, sauna,  baths, cocktail lounges, small-scale eateries, placement agencies such as  recruiters of domestic helpers, janitors and security guards</td>
  </tr>
  <tr>
    <td><div align="right">5</div></td>
    <td>Members of the police force and all employees of police  agencies</td>
  </tr>
  <tr>
    <td><div align="right">6</div></td>
    <td>Military men regardless of rank</td>
  </tr>
  <tr>
    <td><div align="right">7.</div></td>
    <td>Lawyers</td>
  </tr>
  <tr>
    <td><div align="right">8.</div></td>
    <td>Media practitioners such as radio commentators,  newspaper columnists and reporters</td>
  </tr>
  <tr>
    <td><div align="right">9.</div></td>
    <td>Politicians</td>
  </tr>
  <tr>
    <td><div align="right">10.</div></td>
    <td>Residents of government or military installations</td>
  </tr>
  <tr>
    <td><div align="right">11.</div></td>
    <td> Labor leaders or arbitrators</td>
  </tr>
  <tr>
    <td><div align="right">12.</div></td>
    <td>Professional athletes</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
 