<style type="text/css">
#Red {
	color: #F00;
}
</style>
<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>Logged in as
        <?=$this->loggedInUser();?>
    </strong></td>
    <td width="15%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/auth/logout'"><strong>Logout</strong></td>
  </tr>
</table>
<center>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</center>
<form action="" method="post"  name="changePassword">
<table width="326" align="center">

<tr>
  <td height="22" colspan="2" id="Red"><strong>Please Change Your Given Password</strong></td>
</tr>
<tr>
<td width="161"><strong>New Password :</strong></td>
<td width="153"><?=$this->form->newpassword2?></td>
</tr>

<tr>
<td><strong>Confirm Password :</strong></td>
<td><?=$this->form->confirmpassword2?></td>
</tr>
<tr>
<td colspan="2" align="center"><input type="submit" name="button" id="button" value="Change Password" /></td>
</tr>
</table>
</form>

<? if($this->errorMessage) {?>
<script type="text/javascript">
alert ("<?=$this->errorMessage?>");
</script>
<? } ?>


<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("changePassword")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("newpassword2","req","Please Enter Your New Password!!");
frmvalidator.addValidation("confirmpassword2","req","Please Confirm Your New Password!!");
frmvalidator.addValidation("newpassword2","minlen=8","Minimum of 8 characters only!!");
frmvalidator.addValidation("newpassword2","maxlen=14","Maximum of 14 characters only!!");
frmvalidator.addValidation("confirmpassword2","minlen=8","Minimum of 8 characters only!!");
frmvalidator.addValidation("confirmpassword2","maxlen=14","Maximum of 14 characters only!!");

 function DoCustomValidation()
	{
	 var frm = document.forms["changePassword"];
	 if (frm.newpassword2.value != frm.confirmpassword2.value){
	    	  sfm_show_error_msg("Password and Confirm Password Do Not Match");
			  return false }
		 {
	    return true;
	 	 }
	
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");

</script>
