<?
$time = microtime();
$time = explode(" ", $time);
$time = $time[1] + $time[0];
$start = $time;
?>
<strong>Loan Origination System - CBS</strong>
<hr  />
<center>
 <strong>Welcome to Loan Origination System</strong>
  <p><img src="<?=$this->baseUrl();?>/images/cbs_logo.jpg" width="400"/></p>
  <p>&nbsp;</p>
</center>
<form action="" method="post" id="signup" name="login">
<table width="369" align="center">
<tr>
<td width="137"><strong>Username</strong><strong>:</strong></td>
<td width="103"><?=$this->form->username?></td>
</tr>

<tr>
<td><strong>Password</strong><strong>:</strong></td>
<td><?=$this->form->password?></td>
</tr>
<tr>
<td colspan="2"></td>
</tr>
<tr>
<td><strong>New Password :</strong></td>
<td><dd><?=$this->form->newpassword?></dd></td>
</tr>

<tr>
<td><strong>Confirm Password :</strong></td>
<td><dd><?=$this->form->confirmpassword?></dd></td>
</tr>
<tr>
<td colspan="2" align="center">
<?=$this->form->submit?>
</td>
</tr>
</table>
</form>

<? if($this->errorMessage) {?>
<script type="text/javascript">
alert ("<?=$this->errorMessage?>");
</script>
<? } ?>
<br />
<br />
<br />
<br />

<center>
<?
$time = microtime();

$time = explode(" ", $time);

$time = $time[1] + $time[0];

$finish = $time;

$totaltime = ($finish - $start);

printf ("This page took %f seconds to load.", $totaltime);
?>
</center>