
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<script type="text/javascript">
checked=false;
function checkedAll () {

	var aa= document.getElementById('update');
	 if (checked == false)
          {
           checked = true
          }
        else
          {
          checked = false
          }
	for (var i =0; i < aa.elements.length; i++) 
	{
	 aa.elements[i].checked = checked;
	}
      }
</script>
<script type="text/javascript">
$(document).ready(function() 
    { 
        $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} ); 
    } 
); 
</script>
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
	<td><strong>ADMIN - PRICELIST - APPROVE</strong></td>
	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'">
    <strong>Return</strong></td>
</tr>
</table>
<br />
<form method="post" name="add" id="add">
<table width="100%" border="0" align="center">
<? if($this->counter == 1) { ?>
  <tr>
    <td colspan="2" align="left"><a href="<?=$this->baseUrl()?>/admin/pricelistupdate">&lt;&lt;Go to Updates</a></td>
  </tr>
<? } ?>
  <tr>
    <td width="1100" colspan="2" align="center"><input type="button" name="viewButton" id="viewButton" value="View Pricelist" onclick = "window.open('<?=$this->baseURL();?>/admin/pricelistview','mywindow','width=980,height=600,scrollbars=yes,resizable=no, menubar=yes')"/></td>
  </tr>
</table>
</form>
<form method="post" name="update" id="update">
<br />
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;" id="myTable" class="tablesorter">
    <thead> 
  <tr>
    <th width="7%" align="center"><strong> By</strong></td>
    <th width="13%" align="center"><strong>DEALER</strong></td>
    <th width="9%" align="center"><strong>MOS-YEAR</strong></td>
    <th width="9%" align="center"><strong>BRAND</strong><strong></strong></td>
    <th width="8%" align="center"><strong>TYPE</strong></td>
    <th width="19%" align="center"><strong>UNIT</strong></td>
    <th width="13%" align="center"><strong>SELLING PRICE</strong></td>
    <th width="11%" align="center"><strong>LAST MONTH</strong></td>
    <td width="11%" align="center"><input type="checkbox" name="chkAll" id="chkAll" onclick='checkedAll()'/></td>
  </tr>
  </thead> 
  <tbody>
  <? if ($this->detail){  ?>
  <? foreach($this->detail as $row) { ?>
   <tr>
    <td align="center"><?=$this->viewMa($row->duplicate_by)?> - 
      <?=$row->duplicate_date?></td>
    <td height="34" align="center"><?=$row->dealer?></td>
    <td align="center"><?=$this->viewMonths($row->month,'shortcut')?> -
      <?=$row->year?></td>
    <td align="center"><?=$row->brand?></td>
    <td align="center"><?=$row->type?></td>
    <td><?=$row->unit?></td>
    <td align="center" bgcolor="<?=$this->getSellPriceDifference($row->id,'color')?>" >P<?=$row->selling_price?></td>
    <td align="center" onmouseover="Tip('<?=$this->getSellPriceDifference($row->id,'monthyear') ?>')" onmouseout="UnTip()"><?=$this->getSellPriceDifference($row->id,'history')?></td>
    <td align="center"> <input type="hidden" name="row[<?=$row->id?>][id]" value="<?=$row->id?>" />    
      <input type="checkbox" name="row[<?=$row->id?>][chkbox]" id="checkall" value="<?=$row->id?>"/> </td>
  </tr>
        <? } ?>
  <? } ?>
  </tbody> 
</table>

<table width="100%">
  <tr>
    <td width="2%">&nbsp;</td>
    <td width="2%" align="center">&nbsp;</td>
    <td width="2%" align="center">&nbsp;</td>
    <td width="2%" align="center">&nbsp;</td>
    <td width="54%" align="center"><span class="c1"><font color="#FF3300">&#9608;</font> - Price Changes <font color="#66FF33">&#9608;</font> - No Changes<font color="#FFCC66"> &#9608;</font> - New Unit</span></td>
    <td width="38%" colspan="3" align="center">
    <? if($this->counter == 0) { ?>
    <input type="submit" name="button" id="button" value="Approve" onclick="return window.confirm('Are you sure you want to Update all checked rows?')"/>
	
    <input type="submit" name="button" id="button" value="Delete" onclick="return window.confirm('Are you sure you want to Delete all checked rows?')"/>
    <? } ?>
	
	</td>
  </tr>
</table>
</form>
<p>&nbsp;</p>
