<style type="text/css">
table.sample {
	border-width: 2px 2px 2px 2px;
	border-spacing: 2px;
	border-style: outset outset outset outset;
	border-color: black black black black;
	border-collapse: collapse;
	background-color: white;
}
table.sample th {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
table.sample td {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
</style>
<form method="post" name="adduser">
<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>ADMIN - USER - RESET DIGITAL PASSWORD</strong></td>
    </tr>
</table>
<br />
<? if(!$this->newpassword) { ?>

<table width="100%" class="sample">
    <tr>
    <td align="center">Reset this user's password ?</td>
  </tr>
  <tr>
    <td width="100%" align="center"><input type="submit" name="button" id="button" value="Yes" />
      <input type="button" name="button2" id="button2" value="No" /></td>
  </tr>
</table>
<? } ?>
<? if($this->newpassword) { ?>
<table width="100%" class="sample">
  <tr>
    <td align="center">Digital Password Reset :
      <?=$this->username?></td>
  </tr>
  <tr>
    <td width="100%" align="center">New Digital Password :
      <?=$this->newpassword?></td>
  </tr>
</table>
<? } ?>
<br />
</form>
