
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
<tr>
	<td><strong>ADMIN - PRICELIST - VIEW</strong></td>
	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/admin'">
    <strong>Return</strong></td>
</tr>
</table>
<br />
<form method="post" name="add" id="add">
<table width="70%" border="0" align="center">
  <tr>
    <td width="550" colspan="2" align="center">Dealer       <?=$this->form->dealer?>
      List Year
      <?=$this->form->listyear?>
      List Month
      <?=$this->form->listmonth?>       Brand&nbsp;<?=$this->form->veh_brand?></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><input type="submit" name="button" id="button" value="View Pricelist"/></td>
  </tr>
</table>
</form>
<form method="post" name="update" id="update">
<br />
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td width="7%" align="center"><strong> By</strong></td>
    <td width="14%" align="center"><strong>DEALER</strong></td>
    <td width="9%" align="center"><strong>MOS-YEAR</strong></td>
    <td width="9%" align="center"><strong>BRAND</strong><strong></strong></td>
    <td width="8%" align="center"><strong>TYPE</strong></td>
    <td width="19%" align="center"><strong>UNIT</strong></td>
    <td width="21%" align="center"><strong>SELLING PRICE</strong></td>
    <td width="13%" align="center"><strong>Status</strong></td>
    </tr>
  <? if ($this->detail){  ?>
  <? foreach($this->detail as $row) { ?>
  <tr>
    <td align="center"><?=$this->viewMa($row->approve_by)?> - 
      <?=$row->approve_date?></td>
    <td height="34" align="center"><?=$row->dealer?></td>
    <td align="center"><?=$this->viewMonths($row->month,'shortcut')?> -
      <?=$row->year?></td>
    <td align="center"><?=$row->brand?></td>
    <td align="center"><?=$row->type?></td>
    <td><?=$row->unit?></td>
    <td align="center">P<?=$row->selling_price?></td>
    <td align="center"><?=$row->status?></td>
    </tr>
        <? } ?>
  <? } ?>
</table>
</form>
<p>
  <? if($this->ifPost){ ?>
</p>
<form method="post" name="duplicate" id="duplicate">
  <table width="100%">
    <tr>
      <td width="5%">&nbsp;</td>
      <td width="5%" align="center">&nbsp;</td>
      <td width="5%" align="center">&nbsp;</td>
      <td width="5%" align="center">&nbsp;</td>
      <td width="41%" align="center">&nbsp;</td>
      <td width="117%" colspan="3" align="center"><input type="submit" name="button" id="button" value="Export as PDF" />
        <input type="hidden" name="dealerTemp" value="<?=$this->dealerTemp?>" />
        <input type="hidden" name="yearTemp" value="<?=$this->yearTemp?>" />
        <input type="hidden" name="monthTemp" value="<?=$this->monthTemp?>" />
      <input type="hidden" name="brandTemp" value="<?=$this->brandTemp?>" /></td>
    </tr>
  </table>
</form>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("duplicate")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("listyear2","dontselect=''","Duplicate Year Required !!");
frmvalidator.addValidation("listmonth2","dontselect=''","Duplicate Month Required!!");
</script>
<? } ?>
