  <form action="" method="post" name="searchdocs" id="searchdocs">
  <table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
      <tr>
        <td><strong>eDOCS - SEARCH</strong></td>
        <td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong> Return </strong></td>
      </tr>
    </table>
    <table border="0" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td colspan="3">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td width="2%">&nbsp;</td>
        <td width="9%">&nbsp;</td>
        <td width="21%">&nbsp;</td>
        <td colspan="3">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><strong>Cap No.</strong></td>
        <td><?=$this->form->capno?></td>
        <td colspan="5">&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td width="15%">&nbsp;</td>
        <td width="5%">&nbsp;</td>
        <td width="15%">&nbsp;</td>
        <td width="15%">&nbsp;</td>
        <td width="18%">&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><strong>Borrower</strong></td>
        <td><?=$this->form->borrower_lname?></td>
        <td>&nbsp;</td>
        <td colspan="2">&nbsp;</td>
        <td colspan="2"><?=$this->form->submit?></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td colspan="2">&nbsp;</td>
        <td colspan="2">&nbsp;</td>
      </tr>
    </table>
  </form>
  <table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
    <tr>
      <td width="11%" align="center"><strong>CAP NO.</strong></td>
      <td width="13%" align="center"><strong>Borrower</strong></td>
      <td width="15%" align="center"><strong>Residence Address</strong></td>
      <td width="6%" align="center"><strong>Type of Loan</strong></td>
      <td width="11%" align="center"><strong>Type of Application</strong></td>
      <td width="6%" align="center"><strong>M.O.</strong></td>
      <td width="6%" align="center"><strong>M.A.</strong></td>
      <td width="9%" align="center"><strong>LAST USER</strong></td>
      <td width="10%" align="center"><strong>ACTION TAKEN</strong></td>
      <td width="13%" align="center"><strong>TIME/DATE</strong></td>
    </tr>
    <? if ($this->rows){?>
    <?php foreach($this->rows as $row) : ?>
    <tr onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/edocs/account/cap/<?=$row->capno?>'">
      <td><?=$row->capno?></td>
      <td><?=$row->borrower_lname.','.$row->borrower_fname.' '.substr($row->borrower_mname, 0,1).'.';?></td>
      <td>&nbsp;</td>
      <td align="center"><?=$this->viewTypeLoan($row->loantype)?></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <?php endforeach; ?>
    <? } ?>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
  

</center>