<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
.amendmentcolorheader {
	color: #666;
}
.requestcolorheader {
	color: #000000;
}
table.sourceheader {
	border-width: 1px;
	border-spacing: 2px;
	border-style: solid;
	border-color: gray;
	border-collapse: separate;
	background-color: white;
}
table.sourceheader th {
	border-width: 1px;
	padding: 1px;
	border-style: none;
	border-color: gray;
	background-color: white;
	-moz-border-radius: 3px 3px 3px 3px;
}
table.sourceheader td {
	border-width: 1px;
	padding: 1px;
	border-style: none;
	border-color: gray;
	background-color: white;
	-moz-border-radius: 3px 3px 3px 3px;
	}
.sourceheader1strow {
	font-size: 8pt;	
	}
table.request {
	border-width: 1px;
	border-spacing: 0px;
	border-style: solid;
	border-color: black;
	border-collapse: separate;
	background-color: white;
}
table.request th {
	border-width: 1px;
	padding: 1px;
	border-style: solid;
	border-color: black;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
table.request td {
	border-width: 1px;
	padding: 1px;
	border-style: solid;
	border-color: black;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}	
	
</Style>
<center>
<table width="95%" border="0">
  <tr>
    <td colspan="2"><img src="<?=$this->baseUrl();?>/images/cbs_craw_logo.jpg" width="314" height="61"/></td>
    <td width="30%"><table width="100%" border="1" class="sourceheader">
      <tr>
        <td class="sourceheader1strow">Source of Application</td>
      </tr>
      <tr>
        <td align="center"><strong>AUTO LOANS</strong></td>
      </tr>
    </table></td>
  </tr>
  </table>
  <form name="ammend" method="post">
<table width="95%" border="0">
  <tr>
    <td width="73%"><strong class="amendmentcolorheader">AMENDMENT FORM</strong></td>
    <td width="27%" align="right" class="sourceheader1strow">Date: <input name="date" type="text" value="<?=date('m-d-Y')?>" size="10" readonly="readonly"/></td>
    </tr>
</table>
<table width="95%" border="1" class="sourceheader">
  <tr>
    <td class="sourceheader1strow">Borrower's Name</td>
    </tr>
  <tr>
    <td><strong><?=$this->detail->borrower_fname.' '.$this->detail->borrower_mname.' '.$this->detail->borrower_lname?></strong> </td>
    </tr>
  <tr>
    <td height="22">Address: 
      <?=$this->detail->pres_address_no.' '.$this->detail->pres_address_st.' '.$this->detail->pres_address_brgy.' '.$this->detail->pres_address_city.' '.$this->detail->pres_address_province. ','.$this->detail->pres_zipcode;?>
   </td>
    </tr>
</table>
<br />
<table width="95%" border="0">
  <tr>
    <td width="73%"><strong class="requestcolorheader">Request:</strong></td>
    <td width="27%" class="sourceheader1strow">&nbsp;</td>
  </tr>
</table>
<table width="95%" border="1" class="request">
  <tr>
    <td width="44%" align="center" ><strong>AMENDMENT ON</strong></td>
    <td width="27%" align="center" ><strong>FROM(<?=$this->oldcap?>)
    </strong></td>
    <td width="29%" align="center" ><strong>TO(<?=$this->capno?>)
    </strong></td>
  </tr>
  <? foreach ($this->amend as $x){ ?>
  <tr>
    <td align="center" ><?=$this->viewFields($x)?></td>
    <td align="center" ><?=$this->viewReconFormat($this->old->$x,$x)?></td>
    <td align="center" ><?=$this->viewReconFormat($this->detail->$x,$x)?></td>
  </tr>
  <? } ?>
</table>
<br />
<table width="95%" border="0">
  <tr>
    <td width="73%"><strong class="requestcolorheader">Recommendation/s:</strong></td>
    <td width="27%" class="sourceheader1strow">&nbsp;</td>
  </tr>
</table>
<table width="95%" border="1" class="sourceheader">
  <tr>
    <td ><?=$this->detail->recon_remarks_ca?></td>
  </tr>
  <tr>
    <td><?=$this->form->submit_remarks?></td>
  </tr>
  <tr>
    <td><input type="submit" name="button" id="button" value="Submit CO Recommendation" /></td>
  </tr>
  <tr>
    <td height="22"><strong>Justification /s</strong></td>
  </tr>
  <tr>
    <td height="22">
      <?=nl2br($this->remark_ca->remarks);?>
    </td>
  </tr>
</table>
<br />

<table width="95%" border="0">
  <tr>
    <td width="73%"><strong class="requestcolorheader">Other Terms and Conditions : </strong></td>
    <td width="27%" class="sourceheader1strow">&nbsp;</td>
  </tr>
</table>
<table width="95%" align="center" class="request">
  <tr>
    <td width="27%" align="left"><strong>Items</strong><strong></strong></td>
    <td width="36%" align="center"><strong>From(
      <?=$this->oldcap?>
      )</strong></td>
    <td width="37%" align="center"><strong>To(
      <?=$this->capno?>
      )</strong></td>
    </tr>
  <tr>
    <td align="left">Dealer</td>
    <td align="center"><?=$this->old->dealer?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->dealer,$this->detail->dealer,'ammend')?>><?=$this->detail->dealer?></td>
    </tr>
  <tr>
    <td align="left">Brand</td>
    <td align="center"><?=$this->old->veh_brand?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->veh_brand,$this->detail->veh_brand,'ammend')?>><?=$this->detail->veh_brand?></td>
    </tr>
  <tr>
    <td align="left">Unit</td>
    <td align="center"><?=$this->old->veh_unit?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->veh_unit,$this->detail->veh_unit,'ammend')?>><?=$this->detail->veh_unit?></td>
    </tr>
  <tr>
    <td align="left">Vehicle Type</td>
    <td align="center"><?=$this->old->veh_type?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->veh_unit,$this->detail->veh_unit,'ammend')?>><?=$this->detail->veh_type?></td>
    </tr>
  <tr>
    <td align="left" >Year Model</td>
    <td align="center"><?=$this->old->veh_yrmodel?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->veh_yrmodel,$this->detail->veh_yrmodel,'ammend')?>><?=$this->detail->veh_yrmodel?></td>
    </tr>
  <tr>
    <td align="left">Vehicle Status</td>
    <td align="center"><?=$this->viewVehStatus($this->old->veh_status)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->veh_status,$this->detail->veh_status,'ammend')?>><?=$this->viewVehStatus($this->detail->veh_status)?></td>
    </tr>
  <tr>
    <td align="left">LCP</td>
    <td align="center">P
      <?=number_format($this->old->lcp,2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->lcp,$this->detail->lcp,'ammend')?>>P
      <?=number_format($this->detail->lcp,2)?></td>
    </tr>
  <tr>
    <td align="left">SRP </td>
    <td align="center">P
      <?=number_format($this->old->selling_price,2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->selling_price,$this->detail->selling_price,'ammend')?>>P
      <?=number_format($this->detail->selling_price,2)?></td>
  </tr>
  <tr>
    <td align="left">Downpayment </td>
    <td align="center"><?=number_format($this->old->downpayment_percent,2)?>
      % P
      <?=number_format($this->old->downpayment_actual,2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->downpayment_actual,$this->detail->downpayment_actual,'ammend')?>><?=number_format($this->detail->downpayment_percent,2)?>
      % P <?=number_format($this->detail->downpayment_actual,2)?></td>
  </tr>
  <tr>
    <td align="left">Amount Financed</td>
    <td align="center">P
      <?=number_format($this->old->amountloan,2)?></td>
    <td align="center"  <?=$this->viewReconCompare($this->old->amountloan,$this->detail->amountloan,'ammend')?>>P
      <?=number_format($this->detail->amountloan,2)?></td>
  </tr>
  <tr>
    <td align="left">Term</td>
    <td align="center"><?=$this->old->loanterm?>
mo/s</td>
    <td align="center"  <?=$this->viewReconCompare($this->old->loanterm,$this->detail->loanterm,'ammend')?>><?=$this->detail->loanterm?>
mo/s</td>
  </tr>
  <tr>
    <td align="left">Addon Rate</td>
    <td align="center"><?=$this->old->rate?>
      %</td>
    <td align="center" <?=$this->viewReconCompare($this->old->rate,$this->detail->rate,'ammend')?>><?=$this->detail->rate?>
      %</td>
  </tr>
  <tr>
    <td align="left">Financing Scheme</td>
    <td align="center"><?=$this->old->addon_rate?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->addon_rate,$this->detail->addon_rate,'ammend')?>><?=$this->detail->addon_rate?></td>
  </tr>
  <tr>
    <td align="left">Net Monthly Installment</td>
    <td align="center">P
      <?=number_format(ceil($this->old->monthly_amortization),2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->monthly_amortization,$this->detail->monthly_amortization,'ammend')?>>P
      <?=number_format(ceil($this->detail->monthly_amortization),2)?></td>
  </tr>
  <tr>
    <td align="left">Gross Monthly Installment</td>
    <td align="center">P
      <?=number_format(ceil($this->oldgross),2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->oldgross,$this->currgross,'ammend')?>>P
      <?=number_format(ceil($this->currgross),2)?></td>
  </tr>
  <tr>
    <td align="left">PN Amount</td>
    <td align="center">P      <?=number_format(ceil($this->oldpn),2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->oldpn,$this->currpn,'ammend')?>>P
      <?=number_format(ceil($this->currpn),2)?></td>
    </tr>
  <tr>
    <td align="left">Dealer Incentive Rate</td>
    <td align="center"><?=$this->old->dealer_incentive?>%
      <?=number_format($this->old->dealer_incentive2,2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->dealer_incentive,$this->detail->dealer_incentive,'ammend')?>><?=$this->detail->dealer_incentive?>%
      <?=number_format($this->detail->dealer_incentive2,2)?></td>
    </tr>
  <tr>
    <td align="left">Total Retention Fee</td>
    <td align="center"><?=number_format($this->old->dealer_incentive2,2)?></td>
    <td align="center" <?=$this->viewReconCompare($this->old->dealer_incentive2,$this->detail->dealer_incentive2,'ammend')?>><?=number_format($this->detail->dealer_incentive2,2)?></td>
    </tr>
  <tr>
    <td align="left">Effective Yield</td>
    <td align="center"><?=$this->old->effective_yield?>
%</td>
    <td align="center" <?=$this->viewReconCompare($this->old->effective_yield,$this->detail->effective_yield,'ammend')?>><?=$this->detail->effective_yield?>
%</td>
  </tr>
  <tr>
    <td align="left">GMI %</td>
    <td align="center"><?=number_format($this->old->gmi_ratio,2);?>
      %</td>
    <td align="center" <?=$this->viewReconCompare($this->old->gmi_ratio,$this->detail->gmi_ratio,'ammend')?>><?=number_format($this->detail->gmi_ratio,2);?>
      %</td>
  </tr>
  <? if ($this->loggedInUserType() == 'MA') { ?>
  <? } ?>
</table>
  </form>
  <br />
  <table width="95%" border="0">
    <tr>
      <td colspan="7" bgcolor="#CCCCCC" style="border-bottom:groove"><strong>APPROVAL SECTION
        
      </strong></td>
    </tr>
    <tr>
      <td><a name="add_approving_auth" id="additional_deviation2"/></a></a></a></td>
      <td width="104"><div align="left"><strong>Decision</strong></div></td>
      <td width="22">&nbsp;</td>
      <td colspan="2"><div align="center"><strong>Approving Authority</strong></div></td>
      <td width="345" ><div align="center"><strong>Remarks</strong></div></td>
      <td width="7" >&nbsp;</td>
    </tr>
    <tr>
      <td width="24">&nbsp;</td>
      <td><div align="left"></div></td>
      <td><div align="center"></div></td>
      <td colspan="2">&nbsp;</td>
      <td ><div align="center"></div></td>
      <td >&nbsp;</td>
    </tr>
    <?php foreach($this->approvaldetail as $approvaldetails) :?>
    <tr>
      <td>&nbsp;</td>
      <td><div align="left">
        <?=$approvaldetails->decision?>
      </div></td>
      <td>by</td>
      <td colspan="2" style="border-top:groove"><div align="center">
        <?=$this->viewAuthority($approvaldetails->approved_by)?>
        <?
              if($approvaldetails->date_approval){
			  echo date('m-d-Y',strtotime($approvaldetails->date_approval));}
			  else{ }
			  ?>
      </div></td>
      <td align="center"><center>
        <?=nl2br(stripslashes($approvaldetails->reason));?>
      </center></td>
      <td>&nbsp;</td>
    </tr>

    <?php endforeach; ?>
  </table>
  <p>&nbsp;</p>
</center>
<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("ammend")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("submit_remarks","req","Submit Remarks is Required!!");
</script>