
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="deviation">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ADMIN - DEVIATION MAINTENANCE </strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<table width="100%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td height="200"><table width="99%" height="217" align="center">
      <tr>
        <td width="48%" height="211"><table width="77%" border="0" align="center" >
          <tr>
            <td width="30%" align="left">Deviation Field </td>
            <td colspan="2" align="left"><strong>
              <?=$this->form->devfield?>
            </strong></td>
            </tr>
          <tr>
            <td align="left"><div align="right"><strong>
              <input type="submit" name="button" id="button" value="Add" />
            </strong></div></td>
            <td colspan="2" align="left"><strong>
              <?=$this->form->add_deviation?>
            </strong></td>
            </tr>
          <tr>
            <td align="left"><div align="right"><strong>
              <input type="submit" name="button2" id="button2" value="Modify" />
            </strong></div></td>
            <td colspan="2" align="left"><strong>
            <?=$this->form->modify_deviation?>
            </strong></td>
            </tr>
          <tr>
            <td width="30%" align="left">Min Value </td>
            <td colspan="2" align="left"><strong>
              <?=$this->form->minval?>
            </strong></td>
            </tr>
          <tr>
            <td height="23" align="left">Max Value </td>
            <td colspan="2" align="left"><strong>
              <?=$this->form->maxval?>
            </strong></td>
            </tr>
          <tr>
            <td align="left">Exact Value</td>
            <td colspan="2" align="left"><strong>
              <?=$this->form->exactval?>
            </strong></td>
            </tr>
          <tr>
            <td align="left"><div align="right"></div></td>
            <td align="left"><div align="center"><strong>
              <input type="submit" name="button3" id="button3" value="Save" />
            </strong></div>
              <div align="right"></div></td>
            <td align="left"><div align="right"></div></td>
          </tr>
        </table>
          <p>&nbsp;</p></td>
        <td width="52%"><table width="96%" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
          <tr>
            <td width="129"><strong>Deviation Fields </strong></td>
            <td width="115"><strong>Minimum Value  </strong></td>
            <td width="113"><strong>Maximum Value </strong></td>
            <td width="83"><strong>Exact Value </strong></td>
          </tr>
          <tr>
            <td><div align="left"><strong>
              <?=$this->form->deviationfields?>
            </strong></div></td>
            <td><div align="left"><strong>
              <?=$this->form->minimum_value?>
            </strong></div></td>
            <td><div align="left"><strong>
              <?=$this->form->maximum_value?>
            </strong></div></td>
            <td><div align="left"><strong>
              <?=$this->form->exact_value?>
            </strong></div></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
        </table></td>
      </tr>
    </table>
      </td>
  </tr>
</table>
</form>
