<style type="text/css">
<!--
input.btn {color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
width: 80px;
}
-->
</style>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/mybic.js"></script>
<script>
	var glo;
	function getdataback() {
		ajaxObj = new XMLHTTP("<?=$this->baseUrl();?>/inc/mybic_server.php");
		// lets turn on debugging so we can see what we're sending and receiving
		//ajaxObj.debug=1;
 		ajaxObj.method="GET";
		 ajaxObj.call("action=getdata&username=<?=$this->loggedInUser();?>",respGetData);
		//alert(getCity());
	}
	
	function respGetData(resp) {
		//document.getElementById('content').innerHTML = resp;
		//return resp;
		//document.writeln(resp);
		glo = resp;
	}
	
</script>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.masubmit.onsubmit())
 {//this check triggers the validations
    document.masubmit.submit();
	//self.close();
 }
}

</SCRIPT> 

<form name="masubmit" method="post">
<script>
getdataback();
</script>

<table width="50%" border="0" align="center">
  <tr>
    <td width="100%" colspan="2" align="left" valign="top">
  </td>
    
  
  <tr>
    <td align="center">Old Password</td>
    <td align="center"><input type="password" name="olddigiPass" id="olddigiPass" /></td>
  </tr>
  <tr>
    <td align="center">New Password :</td>
    <td align="center"><input type="password" name="newdigiPass" id="newdigiPass" /></td>
  </tr>
  <tr>
    <td align="center">Confirm New  Electronic Password:      </td>
    <td align="center"><input type="password" name="confirmdigiPass" id="confirmdigiPass" /></td>
  </tr>
</table>
<table width="50%" border="0" align="center">
  <tr>
    <td align="center"><input type="button" name="score" value="OK" class="btn" onclick="javascript:submitform()" /></td>
    <td align="center"><input type="button" name="score2" value="CANCEL" class="btn" onclick="javascript:self.close()"/></td>
  </tr>
</table>
</form>
<? if($this->success) {?>
<script type="text/javascript">
alert ("<?=$this->success?>");
window.close();
window.opener.location.reload();
</script>
<? } ?>



<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("masubmit")
frmvalidator.EnableMsgsTogether();
frmvalidator.addValidation("confirmdigiPass","req","Please enter password again!!");
frmvalidator.addValidation("newdigiPass","req","Enter new Digital Password!!");
frmvalidator.addValidation("olddigiPass","req","Digital Password Required!!");
frmvalidator.addValidation("confirmdigiPass","maxlen=8","Only 8 Character Word Digital Password!!");
frmvalidator.addValidation("newdigiPass","maxlen=8","Only 8 Character Word for Digital Password!!");
frmvalidator.addValidation("confirmdigiPass","minlen=8","Only 8 Character Word Digital Password!!");
frmvalidator.addValidation("newdigiPass","minlen=8","Only 8 Character Word for Digital Password!!");

 function DoCustomValidation()
	{
	  var frm = document.forms["masubmit"];
	  	    if (calcMD5(frm.olddigiPass.value) !=  glo)
	  		//if (frm.olddigiPass.value !=  glo)
	  		{
	    	  sfm_show_error_msg("Wrong Old Digital Password Please Enter Again");
   			  return false
	  		}
			
			else if (frm.confirmdigiPass.value !=  frm.newdigiPass.value)
	  		{
	    	  sfm_show_error_msg("Password do not match");
   			  return false
	  		}

		  	{
	    return true;
			}
	}
	  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>
