
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>


<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ADMIN - Page</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<p>&nbsp;</p>
<table width="23%" border="0" align="center">
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/users">Manage Users</a></td>
  </tr>
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/role">Roles</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/promo">Promo</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/userrights">User Rights</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/loginattendance">Login Attendance</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/deviation">Deviation</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/weights">Weights 1</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/weights2">Weights 2</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/VehicleList">Vehicle List</a></td>
  </tr>
  <tr>
  <td><a href="<?=$this->baseURL()?>/admin/pricelist">Price List Retrieve</a></td>
  </tr>
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/pricelistupdate">Price List Update</a></td>
  </tr>
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/pricelistapprove">Price List Approve</a></td>
  </tr>
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/dealer">Dealer Maintenance</a></td>
  </tr>
  <tr>
    <td><a href="<?=$this->baseURL()?>/admin/weightmaintenance">Weights Maintenance</a></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>
