
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/tooltip.js"></script>  
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>

<form action="" method="post" name="deviation">
<table border=1 width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">

<tr>
	<td><strong>ADMIN - WEIGHTS MAINTENANCE</strong></td>

	<td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong>
      Return
    </strong></td>
</tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<table width="200" align="center" border="0">
  <tr>
    <td><div align="center"><strong>
      <?=$this->form->weight_field?>
    </strong></div></td>
  </tr>
</table>
&nbsp;
<div align="center">
  <table width="509" border="0">
    <tr>
      <td width="59"><div align="center">ID</div></td>
      <td width="138"><div align="center">Values</div></td>
      <td width="149"><div align="center">Weight</div></td>
      <td width="74">&nbsp;</td>
      <td width="67">&nbsp;</td>
    </tr>
    <tr>
      <td><strong>
        <?=$this->form->id?>
      </strong></td>
      <td><strong>
        <?=$this->form->field_value?>
      </strong></td>
      <td><strong>
        <?=$this->form->field_weight?>
      </strong></td>
      <td><strong>
        <input type="submit" name="button" id="button" value="Add" />
      </strong></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><strong>
        <input type="submit" name="button2" id="button2" value="Update" />
      </strong></td>
      <td><strong>
        <input type="submit" name="button3" id="button3" value="Delete" />
      </strong></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</div>
</form>
