<style type="text/css">
table.sample {
	border-width: 2px 2px 2px 2px;
	border-spacing: 2px;
	border-style: outset outset outset outset;
	border-color: black black black black;
	border-collapse: collapse;
	background-color: white;
}
table.sample th {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
table.sample td {
	border-width: 1px 1px 1px 1px;
	padding: 1px 1px 1px 1px;
	border-style: none none none none;
	border-color: gray gray gray gray;
	background-color: white;
	-moz-border-radius: 0px 0px 0px 0px;
}
</style>
<Style>
BODY, P,TD{ font-family: Arial,Verdana,Helvetica, sans-serif; font-size: 10pt }
A{font-family: Arial,Verdana,Helvetica, sans-serif;}
B {	font-family : Arial, Helvetica, sans-serif;	font-size : 12px;	font-weight : bold;}
.error_strings{ font-family:Verdana; font-size:10px; color:#660000;}
</Style>
<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td><strong>ADMIN - WEIGHTS</strong></td>
    <td width="13%" align="center" onmouseover="this.style.background='red';this.style.cursor='pointer';this.style.color='white'"
        onmouseout="this.style.background='white';this.style.color='black'" onclick="window.location.href='<?=$this->baseUrl()?>/index/'"><strong> Return </strong></td>
  </tr>
</table>
<p>&nbsp;</p>
<table width="200" align="center" border="0">
  <tr>
    <td><div align="center"><strong>FIELDS</strong></div></td>
  </tr>
</table>
&nbsp;
<div align="center">
  <table width="96%"  align="center" border="1" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
    <tr>
      <td width="129"><div align="center"><a href="#">Age</a></div></td>
      <td width="115"><div align="center"><a href="#">Gender</a></div></td>
      <td width="115"><div align="center"><a href="#">Marital Status</a></div></td>
      <td width="113"><div align="center"><a href="#">Citizenship</a></div></td>
      <td width="83"><div align="center"><a href="#">Residence</a></div></td>
    </tr>
    <tr>
      <td><div align="center"><a href="#">Length of Stay</a></div></td>
      <td><div align="center"><a href="#">Neighborhood Type</a></div></td>
      <td><div align="center"><a href="#">Background Investigation</a></div></td>
      <td><div align="center"><a href="#">Past Dealing with Chinabank</a></div></td>
      <td><div align="center"><a href="#">Bank/FI Reference Checking</a></div></td>
    </tr>
    <tr>
      <td><div align="center"><a href="#">Total Combined Income</a></div></td>
      <td><div align="center"><a href="#">Term Loan (months)</a></div></td>
      <td><div align="center"><a href="#">No. of Dependents</a></div></td>
      <td><div align="center"><a href="#">GMI Ratio</a></div></td>
      <td><div align="center"><a href="#">Source of Income Verification</a></div></td>
    </tr>
    <tr>
      <td><div align="center"><a href="#">Employed- Status</a></div></td>
      <td><div align="center"><a href="#">Employed-Rank/ Position</a></div></td>
      <td><div align="center"><a href="#">Employed-Years of Employment</a></div></td>
      <td><div align="center"><a href="#">Self Employed- Years in Business</a></div></td>
      <td><div align="center"><a href="#">Self - Employed - Nature of Business</a></div></td>
    </tr>
    <tr>
      <td><div align="center"><a href="#">Self- Employed - Source of Income</a></div></td>
      <td><div align="center"><a href="#">Downpayment</a></div></td>
      <td><div align="center"><a href="#">Vehicle Status</a></div></td>
      <td><div align="center"><a href="#">Vehicle Type</a></div></td>
      <td><div align="center"><a href="#">Vehicle Brand</a></div></td>
    </tr>
    <tr>
      <td><div align="center"><a href="#">Vehicle Use</a></div></td>
      <td><div align="center"><a href="#">Employer's Industry</a></div></td>
      <td><div align="center"></div></td>
      <td><div align="center"></div></td>
      <td><div align="center"></div></td>
    </tr>
  </table>
</div>