<style type="text/css">
<!--
input.btn {color:#000; 
font: bold 84% 'trebuchet ms',helvetica,sans-serif; 
background-color:#fff; 
border:2px solid; 
border-color: #000 #000 #000 #000; 
width: 80px;
}
-->
</style>
<SCRIPT language="JavaScript">
function submitform()
{
 if(document.masubmit.onsubmit())
 {//this check triggers the validations
    document.masubmit.submit();
	//self.close();
	// setTimeout(refr(),5000);
 }
}

function refr(){
	if (window.opener && !window.opener.closed) {
	window.opener.location='<?=$this->baseUrl()?>/index/account/cap/<?=$this->capno?>';
	}
}
</SCRIPT> 
<form name="masubmit" method="post">
<table border="1" width="100%" style="border-width: 2px 2px 2px 2px;border-spacing: 1px;
	border-style: solid solid solid solid;border-color: black black black black;
	border-collapse: collapse;background-color: white;">
  <tr>
    <td align="left" ><strong>Booking Information</strong></td>
    </tr>
</table>
<br />
<table width="60%" border="0" align="center">
  <tr>
    <td colspan="3" align="left" valign="top">

</td>
    </tr>
  <tr>
    <td width="17%" align="left" valign="top">&nbsp;</td>
    <td width="34%" align="left" valign="top">Name:</td>
    <td width="49%"><?=$this->borrowerName?></td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">Date Booked:</td>
    <td><?=$this->form->bookdate?></td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">PN Amount:</td>
    <td><?=$this->form->pn_amount?></td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">Amount Financed:</td>
    <td><?=$this->form->amount_financed?></td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">PN Number:</td>
    <td><?=$this->form->pn_number?></td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">Term:</td>
    <td><?=$this->form->loanterm?> mos.</td>
  </tr>
  <tr>
    <td align="left" valign="top">&nbsp;</td>
    <td align="left" valign="top">LA Remarks:</td>
    <td><?=$this->remarks_la?></td>
  </tr>
  <? if($this->loggedInUserType() == 'LO' || $this->loggedInUserType() == 'LDH') { ?> 
    <? } ?>
  <tr>
    <td colspan="3" align="center">&nbsp;<strong>Remarks</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
  </tr>
</table><table width="60%" border="0" align="center">
  <tr>
    <td colspan="2" align="center"><?=$this->form->submit_remarks?></td>
  </tr>
  
  <tr>
    <td colspan="2" align="center"><?=$this->detail?></td>
    </tr>
    
  <tr>
    <td align="center"><input type="button" name="score" 
    value="<? if ($this->loggedInUserType() == 'LO' || $this->loggedInUserType() == 'LDH') {
		echo "BOOK"; }
		else{ echo "SUBMIT"; }?>" class="btn" onclick="javascript:submitform()" /></td>
    <td align="center"><input type="button" name="score2" value="CANCEL" class="btn" onclick="javascript:self.close()"/></td>
  </tr>
</table>
</form>
<? if($this->isSubmit) { ?>
<script type="text/javascript">
	alert("Done");
	self.close();
	setTimeout(refr(),5000);

</script>
<? } ?>
<script type="text/javascript">
//window.onblur=function(){self.close();};
</script>
<!--
javascript:window.close();
if (window.opener && !window.opener.closed) {
	window.opener.location='http://google.com';
}
-->

<script language="JavaScript" type="text/javascript">

var frmvalidator = new Validator("masubmit")
frmvalidator.EnableMsgsTogether();

frmvalidator.addValidation("submit_remarks","req","Submit Remarks is Required!!");
frmvalidator.addValidation("bookdate","regexp=(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)[0-9]{2}","Invalid Date Format MM/DD/YYYY");
//Address Fields
frmvalidator.addValidation("pn_amount","req","PN Amount is Required!!");
frmvalidator.addValidation("amount_financed","req","Amount Financed is Required!!");
frmvalidator.addValidation("pn_number","req","PN Number is Required!!");
frmvalidator.addValidation("pn_number","numeric","PN Number Invalid Format!!");
frmvalidator.addValidation("loanterm","numeric","Loan Term Invalid Format!!");
</script>



